// Auto-generated by Java-to-Swift wrapper generator.
import AndroidOS
import JavaKit
import JavaRuntime

extension AssetFileDescriptor {
  @JavaClass("android.content.res.AssetFileDescriptor$AutoCloseInputStream")
  open class AutoCloseInputStream: ParcelFileDescriptor.AutoCloseInputStream {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: AssetFileDescriptor?, environment: JNIEnvironment? = nil) throws

  @JavaMethod
  open override func reset() throws

  @JavaMethod
  open override func mark(_ arg0: Int32)

  @JavaMethod
  open override func read(_ arg0: [Int8]) throws -> Int32

  @JavaMethod
  open override func read() throws -> Int32

  @JavaMethod
  open override func read(_ arg0: [Int8], _ arg1: Int32, _ arg2: Int32) throws -> Int32

  @JavaMethod
  open override func skip(_ arg0: Int64) throws -> Int64

  @JavaMethod
  open override func available() throws -> Int32

  @JavaMethod
  open override func markSupported() -> Bool
  }
}
