// Auto-generated by Java-to-Swift wrapper generator.
import AndroidJavaIO
import JavaKit
import JavaRuntime

@JavaClass("android.content.AsyncTaskLoader")
open class AsyncTaskLoader: Loader {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: Context?, environment: JNIEnvironment? = nil)

  @JavaMethod
  open override func onCancelLoad() -> Bool

  @JavaMethod
  open override func onForceLoad()

  @JavaMethod
  open func loadInBackground() -> JavaObject!

  @JavaMethod
  open func cancelLoadInBackground()

  @JavaMethod
  open func onCanceled(_ arg0: JavaObject?)

  @JavaMethod
  open func setUpdateThrottle(_ arg0: Int64)

  @JavaMethod
  open func onLoadInBackground() -> JavaObject!

  @JavaMethod
  open func isLoadInBackgroundCanceled() -> Bool
}
