// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava
import CSwiftJavaJNI

extension CapabilityParams {
  @JavaClass("android.content.pm.CapabilityParams$Builder")
  open class Builder: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: String, _ arg1: String, environment: JNIEnvironment? = nil)

  @JavaMethod
  open func addAlias(_ arg0: String) -> CapabilityParams.Builder!

  @JavaMethod
  open func build() -> CapabilityParams!
  }
}
