// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava
import CSwiftJavaJNI

extension DialogInterface {
  @JavaInterface("android.content.DialogInterface$OnMultiChoiceClickListener")
  public struct OnMultiChoiceClickListener {
  @JavaMethod
  public func onClick(_ arg0: DialogInterface?, _ arg1: Int32, _ arg2: Bool)
  }
}
