// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

extension DialogInterface {
  @JavaInterface("android.content.DialogInterface$OnDismissListener")
  public struct OnDismissListener {
  @JavaMethod
  public func onDismiss(_ arg0: DialogInterface?)
  }
}
