// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava
import CSwiftJavaJNI

extension DialogInterface {
  @JavaInterface("android.content.DialogInterface$OnShowListener")
  public struct OnShowListener {
  @JavaMethod
  public func onShow(_ arg0: DialogInterface?)
  }
}
