// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

extension IntentFilter {
  @JavaClass("android.content.IntentFilter$AuthorityEntry")
  open class AuthorityEntry: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: String, _ arg1: String, environment: JNIEnvironment? = nil)

  @JavaMethod
  open override func equals(_ arg0: JavaObject?) -> Bool

  @JavaMethod
  open func getHost() -> String

  @JavaMethod
  open func getPort() -> Int32
  }
}
