// Auto-generated by Java-to-Swift wrapper generator.
import AndroidOS
import JavaKit
import JavaRuntime

extension PackageManager {
  @JavaClass("android.content.pm.PackageManager$ComponentEnabledSetting", implements: Parcelable.self)
  open class ComponentEnabledSetting: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: ComponentName?, _ arg1: Int32, _ arg2: Int32, environment: JNIEnvironment? = nil)

  @JavaMethod
  open func describeContents() -> Int32

  @JavaMethod
  open func writeToParcel(_ arg0: Parcel?, _ arg1: Int32)

  @JavaMethod
  open func getComponentName() -> ComponentName!

  @JavaMethod
  open func getEnabledState() -> Int32

  @JavaMethod
  open func getEnabledFlags() -> Int32
  }
}
extension JavaClass<PackageManager.ComponentEnabledSetting> {
  @JavaStaticField(isFinal: true)
  public var CREATOR: Parcelable.Creator<PackageManager.ComponentEnabledSetting>!

  @JavaStaticField(isFinal: true)
  public var CONTENTS_FILE_DESCRIPTOR: Int32

  @JavaStaticField(isFinal: true)
  public var PARCELABLE_WRITE_RETURN_VALUE: Int32
}
