// Auto-generated by Java-to-Swift wrapper generator.
import AndroidOS
import JavaKit
import JavaKitCollection
import JavaRuntime

@JavaClass("android.content.RestrictionsManager")
open class RestrictionsManager: JavaObject {
  @JavaMethod
  open func getApplicationRestrictions() -> Bundle!

  @JavaMethod
  open func hasRestrictionsProvider() -> Bool

  @JavaMethod
  open func requestPermission(_ arg0: String, _ arg1: String, _ arg2: PersistableBundle?)

  @JavaMethod
  open func createLocalApprovalIntent() -> Intent!

  @JavaMethod
  open func notifyPermissionResponse(_ arg0: String, _ arg1: PersistableBundle?)

  @JavaMethod
  open func getManifestRestrictions(_ arg0: String) -> List<RestrictionEntry>!
}
extension JavaClass<RestrictionsManager> {
  @JavaStaticField(isFinal: true)
  public var ACTION_PERMISSION_RESPONSE_RECEIVED: String

  @JavaStaticField(isFinal: true)
  public var ACTION_REQUEST_LOCAL_APPROVAL: String

  @JavaStaticField(isFinal: true)
  public var ACTION_REQUEST_PERMISSION: String

  @JavaStaticField(isFinal: true)
  public var EXTRA_PACKAGE_NAME: String

  @JavaStaticField(isFinal: true)
  public var EXTRA_REQUEST_BUNDLE: String

  @JavaStaticField(isFinal: true)
  public var EXTRA_REQUEST_ID: String

  @JavaStaticField(isFinal: true)
  public var EXTRA_REQUEST_TYPE: String

  @JavaStaticField(isFinal: true)
  public var EXTRA_RESPONSE_BUNDLE: String

  @JavaStaticField(isFinal: true)
  public var META_DATA_APP_RESTRICTIONS: String

  @JavaStaticField(isFinal: true)
  public var REQUEST_KEY_APPROVE_LABEL: String

  @JavaStaticField(isFinal: true)
  public var REQUEST_KEY_DATA: String

  @JavaStaticField(isFinal: true)
  public var REQUEST_KEY_DENY_LABEL: String

  @JavaStaticField(isFinal: true)
  public var REQUEST_KEY_ICON: String

  @JavaStaticField(isFinal: true)
  public var REQUEST_KEY_ID: String

  @JavaStaticField(isFinal: true)
  public var REQUEST_KEY_MESSAGE: String

  @JavaStaticField(isFinal: true)
  public var REQUEST_KEY_NEW_REQUEST: String

  @JavaStaticField(isFinal: true)
  public var REQUEST_KEY_TITLE: String

  @JavaStaticField(isFinal: true)
  public var REQUEST_TYPE_APPROVAL: String

  @JavaStaticField(isFinal: true)
  public var RESPONSE_KEY_ERROR_CODE: String

  @JavaStaticField(isFinal: true)
  public var RESPONSE_KEY_MESSAGE: String

  @JavaStaticField(isFinal: true)
  public var RESPONSE_KEY_RESPONSE_TIMESTAMP: String

  @JavaStaticField(isFinal: true)
  public var RESPONSE_KEY_RESULT: String

  @JavaStaticField(isFinal: true)
  public var RESULT_APPROVED: Int32

  @JavaStaticField(isFinal: true)
  public var RESULT_DENIED: Int32

  @JavaStaticField(isFinal: true)
  public var RESULT_ERROR: Int32

  @JavaStaticField(isFinal: true)
  public var RESULT_ERROR_BAD_REQUEST: Int32

  @JavaStaticField(isFinal: true)
  public var RESULT_ERROR_INTERNAL: Int32

  @JavaStaticField(isFinal: true)
  public var RESULT_ERROR_NETWORK: Int32

  @JavaStaticField(isFinal: true)
  public var RESULT_NO_RESPONSE: Int32

  @JavaStaticField(isFinal: true)
  public var RESULT_UNKNOWN_REQUEST: Int32

  @JavaStaticMethod
  public func convertRestrictionsToBundle(_ arg0: List<RestrictionEntry>?) -> Bundle!
}
