// Auto-generated by Java-to-Swift wrapper generator.
import AndroidOS
import JavaKit
import JavaRuntime

@JavaClass("android.content.pm.Signature", implements: Parcelable.self)
open class Signature: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: [Int8], environment: JNIEnvironment? = nil)

  @JavaMethod
  @_nonoverride public convenience init(_ arg0: String, environment: JNIEnvironment? = nil)

  @JavaMethod
  open func describeContents() -> Int32

  @JavaMethod
  open func writeToParcel(_ arg0: Parcel?, _ arg1: Int32)

  @JavaMethod
  open func toCharsString() -> String

  @JavaMethod
  open override func equals(_ arg0: JavaObject?) -> Bool

  @JavaMethod
  open override func hashCode() -> Int32

  @JavaMethod
  open func toChars() -> [UInt16]

  @JavaMethod
  open func toChars(_ arg0: [UInt16], _ arg1: [Int32]) -> [UInt16]

  @JavaMethod
  open func toByteArray() -> [Int8]
}
extension JavaClass<Signature> {
  @JavaStaticField(isFinal: true)
  public var CREATOR: Parcelable.Creator<Signature>!

  @JavaStaticField(isFinal: true)
  public var CONTENTS_FILE_DESCRIPTOR: Int32

  @JavaStaticField(isFinal: true)
  public var PARCELABLE_WRITE_RETURN_VALUE: Int32
}
