// Auto-generated by Java-to-Swift wrapper generator.
import AndroidOS
import JavaKit
import JavaRuntime

@JavaClass("android.content.SyncInfo", implements: Parcelable.self)
open class SyncInfo: JavaObject {
  @JavaField(isFinal: true)
  public var authority: String

  @JavaField(isFinal: true)
  public var startTime: Int64

  @JavaMethod
  open func describeContents() -> Int32

  @JavaMethod
  open func writeToParcel(_ arg0: Parcel?, _ arg1: Int32)
}
extension JavaClass<SyncInfo> {
  @JavaStaticField(isFinal: true)
  public var CONTENTS_FILE_DESCRIPTOR: Int32

  @JavaStaticField(isFinal: true)
  public var PARCELABLE_WRITE_RETURN_VALUE: Int32
}
