// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

@JavaClass("android.content.UriMatcher")
open class UriMatcher: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: Int32, environment: JNIEnvironment? = nil)

  @JavaMethod
  open func addURI(_ arg0: String, _ arg1: String, _ arg2: Int32)
}
extension JavaClass<UriMatcher> {
  @JavaStaticField(isFinal: true)
  public var NO_MATCH: Int32
}
