// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

extension AbsListView {
  @JavaInterface("android.widget.AbsListView$OnScrollListener")
  public struct OnScrollListener {
  @JavaMethod
  public func onScrollStateChanged(_ arg0: AbsListView?, _ arg1: Int32)

  @JavaMethod
  public func onScroll(_ arg0: AbsListView?, _ arg1: Int32, _ arg2: Int32, _ arg3: Int32)
  }
}
extension JavaClass<AbsListView.OnScrollListener> {
  @JavaStaticField(isFinal: true)
  public var SCROLL_STATE_FLING: Int32

  @JavaStaticField(isFinal: true)
  public var SCROLL_STATE_IDLE: Int32

  @JavaStaticField(isFinal: true)
  public var SCROLL_STATE_TOUCH_SCROLL: Int32
}
