// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava
import CSwiftJavaJNI

extension AutoCompleteTextView {
  @JavaInterface("android.widget.AutoCompleteTextView$OnDismissListener")
  public struct OnDismissListener {
  @JavaMethod
  public func onDismiss()
  }
}
