// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

extension CalendarView {
  @JavaInterface("android.widget.CalendarView$OnDateChangeListener")
  public struct OnDateChangeListener {
  @JavaMethod
  public func onSelectedDayChange(_ arg0: CalendarView?, _ arg1: Int32, _ arg2: Int32, _ arg3: Int32)
  }
}
