// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

extension ExpandableListView {
  @JavaInterface("android.widget.ExpandableListView$OnGroupClickListener")
  public struct OnGroupClickListener {

  }
}
