// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

extension Filter {
  @JavaInterface("android.widget.Filter$FilterListener")
  public struct FilterListener {
  @JavaMethod
  public func onFilterComplete(_ arg0: Int32)
  }
}
