// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

extension MediaController {
  @JavaInterface("android.widget.MediaController$MediaPlayerControl")
  public struct MediaPlayerControl {
  @JavaMethod
  public func start()

  @JavaMethod
  public func getDuration() -> Int32

  @JavaMethod
  public func getBufferPercentage() -> Int32

  @JavaMethod
  public func pause()

  @JavaMethod
  public func getCurrentPosition() -> Int32

  @JavaMethod
  public func seekTo(_ arg0: Int32)

  @JavaMethod
  public func isPlaying() -> Bool

  @JavaMethod
  public func canPause() -> Bool

  @JavaMethod
  public func canSeekBackward() -> Bool

  @JavaMethod
  public func canSeekForward() -> Bool

  @JavaMethod
  public func getAudioSessionId() -> Int32
  }
}
