// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

@JavaClass("android.widget.OverScroller")
open class OverScroller: JavaObject {
  @JavaMethod
  open func computeScrollOffset() -> Bool

  @JavaMethod
  open func notifyHorizontalEdgeReached(_ arg0: Int32, _ arg1: Int32, _ arg2: Int32)

  @JavaMethod
  open func notifyVerticalEdgeReached(_ arg0: Int32, _ arg1: Int32, _ arg2: Int32)

  @JavaMethod
  open func isFinished() -> Bool

  @JavaMethod
  open func forceFinished(_ arg0: Bool)

  @JavaMethod
  open func getCurrX() -> Int32

  @JavaMethod
  open func getCurrY() -> Int32

  @JavaMethod
  open func getCurrVelocity() -> Float

  @JavaMethod
  open func getStartX() -> Int32

  @JavaMethod
  open func getStartY() -> Int32

  @JavaMethod
  open func getFinalX() -> Int32

  @JavaMethod
  open func getFinalY() -> Int32

  @JavaMethod
  open func startScroll(_ arg0: Int32, _ arg1: Int32, _ arg2: Int32, _ arg3: Int32, _ arg4: Int32)

  @JavaMethod
  open func startScroll(_ arg0: Int32, _ arg1: Int32, _ arg2: Int32, _ arg3: Int32)

  @JavaMethod
  open func springBack(_ arg0: Int32, _ arg1: Int32, _ arg2: Int32, _ arg3: Int32, _ arg4: Int32, _ arg5: Int32) -> Bool

  @JavaMethod
  open func isOverScrolled() -> Bool

  @JavaMethod
  open func abortAnimation()

  @JavaMethod
  open func fling(_ arg0: Int32, _ arg1: Int32, _ arg2: Int32, _ arg3: Int32, _ arg4: Int32, _ arg5: Int32, _ arg6: Int32, _ arg7: Int32, _ arg8: Int32, _ arg9: Int32)

  @JavaMethod
  open func fling(_ arg0: Int32, _ arg1: Int32, _ arg2: Int32, _ arg3: Int32, _ arg4: Int32, _ arg5: Int32, _ arg6: Int32, _ arg7: Int32)

  @JavaMethod
  open func setFriction(_ arg0: Float)
}
