// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava
import CSwiftJavaJNI

extension PopupMenu {
  @JavaInterface("android.widget.PopupMenu$OnDismissListener")
  public struct OnDismissListener {
  @JavaMethod
  public func onDismiss(_ arg0: PopupMenu?)
  }
}
