// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

extension RadioGroup {
  @JavaClass("android.widget.RadioGroup$LayoutParams")
  open class LayoutParams: LinearLayout.LayoutParams {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: ViewSwitcher.MarginLayoutParams?, environment: JNIEnvironment? = nil)

  @JavaMethod
  @_nonoverride public convenience init(_ arg0: ViewSwitcher.LayoutParams?, environment: JNIEnvironment? = nil)

  @JavaMethod
  @_nonoverride public convenience init(_ arg0: Int32, _ arg1: Int32, _ arg2: Float, environment: JNIEnvironment? = nil)

  @JavaMethod
  @_nonoverride public convenience init(_ arg0: Int32, _ arg1: Int32, environment: JNIEnvironment? = nil)
  }
}
extension JavaClass<RadioGroup.LayoutParams> {
  @JavaStaticField(isFinal: true)
  public var FILL_PARENT: Int32

  @JavaStaticField(isFinal: true)
  public var MATCH_PARENT: Int32

  @JavaStaticField(isFinal: true)
  public var WRAP_CONTENT: Int32
}
