// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

extension RemoteViews {
  @JavaClass("android.widget.RemoteViews$RemoteCollectionItems")
  open class RemoteCollectionItems: JavaObject {
  @JavaMethod
  open func getItemView(_ arg0: Int32) -> RemoteViews!

  @JavaMethod
  open func getItemCount() -> Int32

  @JavaMethod
  open func getViewTypeCount() -> Int32

  @JavaMethod
  open func describeContents() -> Int32

  @JavaMethod
  open func getItemId(_ arg0: Int32) -> Int64

  @JavaMethod
  open func hasStableIds() -> Bool
  }
}
extension JavaClass<RemoteViews.RemoteCollectionItems> {
  @JavaStaticField(isFinal: true)
  public var CONTENTS_FILE_DESCRIPTOR: Int32

  @JavaStaticField(isFinal: true)
  public var PARCELABLE_WRITE_RETURN_VALUE: Int32
}
