// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

@JavaInterface("android.widget.SectionIndexer")
public struct SectionIndexer {
  @JavaMethod
  public func getPositionForSection(_ arg0: Int32) -> Int32

  @JavaMethod
  public func getSectionForPosition(_ arg0: Int32) -> Int32

  @JavaMethod
  public func getSections() -> [JavaObject?]
}
