// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

extension SeekBar {
  @JavaInterface("android.widget.SeekBar$OnSeekBarChangeListener")
  public struct OnSeekBarChangeListener {
  @JavaMethod
  public func onStartTrackingTouch(_ arg0: SeekBar?)

  @JavaMethod
  public func onStopTrackingTouch(_ arg0: SeekBar?)

  @JavaMethod
  public func onProgressChanged(_ arg0: SeekBar?, _ arg1: Int32, _ arg2: Bool)
  }
}
