// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

extension SimpleCursorAdapter {
  @JavaInterface("android.widget.SimpleCursorAdapter$CursorToStringConverter")
  public struct CursorToStringConverter {

  }
}
