// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

@JavaClass("android.widget.SimpleExpandableListAdapter")
open class SimpleExpandableListAdapter: BaseExpandableListAdapter {
  @JavaMethod
  open func getChild(_ arg0: Int32, _ arg1: Int32) -> JavaObject!

  @JavaMethod
  open func getChildId(_ arg0: Int32, _ arg1: Int32) -> Int64

  @JavaMethod
  open func getChildrenCount(_ arg0: Int32) -> Int32

  @JavaMethod
  open func getGroup(_ arg0: Int32) -> JavaObject!

  @JavaMethod
  open func getGroupCount() -> Int32

  @JavaMethod
  open func getGroupId(_ arg0: Int32) -> Int64

  @JavaMethod
  open func isChildSelectable(_ arg0: Int32, _ arg1: Int32) -> Bool

  @JavaMethod
  open func hasStableIds() -> Bool
}
