// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

extension Toolbar {
  @JavaInterface("android.widget.Toolbar$OnMenuItemClickListener")
  public struct OnMenuItemClickListener {

  }
}
