// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaKitCollection
import JavaKitFunction
import JavaRuntime

@JavaInterface("java.lang.Iterable")
public struct Iterable<T: AnyJavaObject> {
  @JavaMethod
  public func iterator() -> JavaIterator<T>!

  @JavaMethod
  public func forEach(_ arg0: JavaConsumer<T>?)
}
