// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava
import CSwiftJavaJNI

@JavaInterface("android.webkit.ValueCallback")
public struct ValueCallback<T: AnyJavaObject> {
  @JavaMethod
  public func onReceiveValue(_ arg0: T?)
}
