// Auto-generated by Java-to-Swift wrapper generator.
import AndroidJavaIO
import AndroidJavaLang
import JavaKit
import JavaRuntime

@JavaClass("android.webkit.WebBackForwardList", implements: Cloneable.self, Serializable.self)
open class WebBackForwardList: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(environment: JNIEnvironment? = nil)

  @JavaMethod
  open override func clone() -> WebBackForwardList!

  @JavaMethod
  open func getSize() -> Int32

  @JavaMethod
  open func getCurrentItem() -> WebHistoryItem!

  @JavaMethod
  open func getCurrentIndex() -> Int32

  @JavaMethod
  open func getItemAtIndex(_ arg0: Int32) -> WebHistoryItem!
}
