// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava
import CSwiftJavaJNI

extension WebView {
  @JavaInterface("android.webkit.WebView$FindListener")
  public struct FindListener {
  @JavaMethod
  public func onFindResultReceived(_ arg0: Int32, _ arg1: Int32, _ arg2: Bool)
  }
}
