// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava
import SwiftJavaJNICore

@JavaClass("android.nfc.tech.MifareClassic", implements: TagTechnology.self)
open class MifareClassic: JavaObject {
  /// Java method `setTimeout`.
  ///
  /// ### Java method signature
  /// ```java
  /// public void android.nfc.tech.MifareClassic.setTimeout(int)
  /// ```
@JavaMethod
  open func setTimeout(_ arg0: Int32)

  /// Java method `getTimeout`.
  ///
  /// ### Java method signature
  /// ```java
  /// public int android.nfc.tech.MifareClassic.getTimeout()
  /// ```
@JavaMethod
  open func getTimeout() -> Int32

  /// Java method `transceive`.
  ///
  /// ### Java method signature
  /// ```java
  /// public byte[] android.nfc.tech.MifareClassic.transceive(byte[]) throws java.io.IOException
  /// ```
@JavaMethod
  open func transceive(_ arg0: [Int8]) throws -> [Int8]

  /// Java method `isConnected`.
  ///
  /// ### Java method signature
  /// ```java
  /// public boolean android.nfc.tech.MifareClassic.isConnected()
  /// ```
@JavaMethod
  open func isConnected() -> Bool

  /// Java method `getTag`.
  ///
  /// ### Java method signature
  /// ```java
  /// public android.nfc.Tag android.nfc.tech.MifareClassic.getTag()
  /// ```
@JavaMethod
  open func getTag() -> Tag!

  /// Java method `connect`.
  ///
  /// ### Java method signature
  /// ```java
  /// public void android.nfc.tech.MifareClassic.connect() throws java.io.IOException
  /// ```
@JavaMethod
  open func connect() throws

  /// Java method `getSectorCount`.
  ///
  /// ### Java method signature
  /// ```java
  /// public int android.nfc.tech.MifareClassic.getSectorCount()
  /// ```
@JavaMethod
  open func getSectorCount() -> Int32

  /// Java method `getBlockCount`.
  ///
  /// ### Java method signature
  /// ```java
  /// public int android.nfc.tech.MifareClassic.getBlockCount()
  /// ```
@JavaMethod
  open func getBlockCount() -> Int32

  /// Java method `blockToSector`.
  ///
  /// ### Java method signature
  /// ```java
  /// public int android.nfc.tech.MifareClassic.blockToSector(int)
  /// ```
@JavaMethod
  open func blockToSector(_ arg0: Int32) -> Int32

  /// Java method `sectorToBlock`.
  ///
  /// ### Java method signature
  /// ```java
  /// public int android.nfc.tech.MifareClassic.sectorToBlock(int)
  /// ```
@JavaMethod
  open func sectorToBlock(_ arg0: Int32) -> Int32

  /// Java method `readBlock`.
  ///
  /// ### Java method signature
  /// ```java
  /// public byte[] android.nfc.tech.MifareClassic.readBlock(int) throws java.io.IOException
  /// ```
@JavaMethod
  open func readBlock(_ arg0: Int32) throws -> [Int8]

  /// Java method `writeBlock`.
  ///
  /// ### Java method signature
  /// ```java
  /// public void android.nfc.tech.MifareClassic.writeBlock(int,byte[]) throws java.io.IOException
  /// ```
@JavaMethod
  open func writeBlock(_ arg0: Int32, _ arg1: [Int8]) throws

  /// Java method `restore`.
  ///
  /// ### Java method signature
  /// ```java
  /// public void android.nfc.tech.MifareClassic.restore(int) throws java.io.IOException
  /// ```
@JavaMethod
  open func restore(_ arg0: Int32) throws

  /// Java method `getMaxTransceiveLength`.
  ///
  /// ### Java method signature
  /// ```java
  /// public int android.nfc.tech.MifareClassic.getMaxTransceiveLength()
  /// ```
@JavaMethod
  open func getMaxTransceiveLength() -> Int32

  /// Java method `getBlockCountInSector`.
  ///
  /// ### Java method signature
  /// ```java
  /// public int android.nfc.tech.MifareClassic.getBlockCountInSector(int)
  /// ```
@JavaMethod
  open func getBlockCountInSector(_ arg0: Int32) -> Int32

  /// Java method `authenticateSectorWithKeyA`.
  ///
  /// ### Java method signature
  /// ```java
  /// public boolean android.nfc.tech.MifareClassic.authenticateSectorWithKeyA(int,byte[]) throws java.io.IOException
  /// ```
@JavaMethod
  open func authenticateSectorWithKeyA(_ arg0: Int32, _ arg1: [Int8]) throws -> Bool

  /// Java method `authenticateSectorWithKeyB`.
  ///
  /// ### Java method signature
  /// ```java
  /// public boolean android.nfc.tech.MifareClassic.authenticateSectorWithKeyB(int,byte[]) throws java.io.IOException
  /// ```
@JavaMethod
  open func authenticateSectorWithKeyB(_ arg0: Int32, _ arg1: [Int8]) throws -> Bool

  /// Java method `increment`.
  ///
  /// ### Java method signature
  /// ```java
  /// public void android.nfc.tech.MifareClassic.increment(int,int) throws java.io.IOException
  /// ```
@JavaMethod
  open func increment(_ arg0: Int32, _ arg1: Int32) throws

  /// Java method `close`.
  ///
  /// ### Java method signature
  /// ```java
  /// public void android.nfc.tech.MifareClassic.close() throws java.io.IOException
  /// ```
@JavaMethod
  open func close() throws

  /// Java method `getType`.
  ///
  /// ### Java method signature
  /// ```java
  /// public int android.nfc.tech.MifareClassic.getType()
  /// ```
@JavaMethod
  open func getType() -> Int32

  /// Java method `getSize`.
  ///
  /// ### Java method signature
  /// ```java
  /// public int android.nfc.tech.MifareClassic.getSize()
  /// ```
@JavaMethod
  open func getSize() -> Int32

  /// Java method `transfer`.
  ///
  /// ### Java method signature
  /// ```java
  /// public void android.nfc.tech.MifareClassic.transfer(int) throws java.io.IOException
  /// ```
@JavaMethod
  open func transfer(_ arg0: Int32) throws

  /// Java method `decrement`.
  ///
  /// ### Java method signature
  /// ```java
  /// public void android.nfc.tech.MifareClassic.decrement(int,int) throws java.io.IOException
  /// ```
@JavaMethod
  open func decrement(_ arg0: Int32, _ arg1: Int32) throws
}
extension JavaClass<MifareClassic> {
  @JavaStaticField(isFinal: true)
  public var BLOCK_SIZE: Int32

  @JavaStaticField(isFinal: true)
  public var KEY_DEFAULT: [Int8]

  @JavaStaticField(isFinal: true)
  public var KEY_MIFARE_APPLICATION_DIRECTORY: [Int8]

  @JavaStaticField(isFinal: true)
  public var KEY_NFC_FORUM: [Int8]

  @JavaStaticField(isFinal: true)
  public var SIZE_1K: Int32

  @JavaStaticField(isFinal: true)
  public var SIZE_2K: Int32

  @JavaStaticField(isFinal: true)
  public var SIZE_4K: Int32

  @JavaStaticField(isFinal: true)
  public var SIZE_MINI: Int32

  @JavaStaticField(isFinal: true)
  public var TYPE_CLASSIC: Int32

  @JavaStaticField(isFinal: true)
  public var TYPE_PLUS: Int32

  @JavaStaticField(isFinal: true)
  public var TYPE_PRO: Int32

  @JavaStaticField(isFinal: true)
  public var TYPE_UNKNOWN: Int32

    /// Java method `get`.
    ///
    /// ### Java method signature
    /// ```java
    /// public static android.nfc.tech.MifareClassic android.nfc.tech.MifareClassic.get(android.nfc.Tag)
    /// ```
  @JavaStaticMethod
  public func get(_ arg0: Tag?) -> MifareClassic!
}
