// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava
import SwiftJavaJNICore

@available(Android 24, *)
extension NfcAdapter {
  /// Listener invoked when a previously ignored NFC tag is removed from the field.
  ///
  /// Pass to `NfcAdapter.ignore(_:_:_:_:)`.
  @JavaInterface("android.nfc.NfcAdapter$OnTagRemovedListener")
  public struct OnTagRemovedListener {
    /// Called when the ignored tag leaves the NFC field.
    @JavaMethod
    public func onTagRemoved()
  }
}
