// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

extension ActivityManager.TaskDescription {
  @JavaClass("android.app.ActivityManager$TaskDescription$Builder")
  open class Builder: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(environment: JNIEnvironment? = nil)

  @JavaMethod
  open func setIcon(_ arg0: Int32) -> ActivityManager.TaskDescription.Builder!

  @JavaMethod
  open func setLabel(_ arg0: String) -> ActivityManager.TaskDescription.Builder!

  @JavaMethod
  open func setPrimaryColor(_ arg0: Int32) -> ActivityManager.TaskDescription.Builder!

  @JavaMethod
  open func setBackgroundColor(_ arg0: Int32) -> ActivityManager.TaskDescription.Builder!

  @JavaMethod
  open func setStatusBarColor(_ arg0: Int32) -> ActivityManager.TaskDescription.Builder!

  @JavaMethod
  open func setNavigationBarColor(_ arg0: Int32) -> ActivityManager.TaskDescription.Builder!

  @JavaMethod
  open func build() -> ActivityManager.TaskDescription!
  }
}
