// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

extension ActionBar {
  @JavaInterface("android.app.ActionBar$OnNavigationListener")
  public struct OnNavigationListener {
  @JavaMethod
  public func onNavigationItemSelected(_ arg0: Int32, _ arg1: Int64) -> Bool
  }
}
