// Auto-generated by Java-to-Swift wrapper generator.
import AndroidJavaIO
import JavaKit
import JavaRuntime

@JavaClass("android.app.ApplicationExitInfo")
open class ApplicationExitInfo: JavaObject {
  @JavaMethod
  open func describeContents() -> Int32

  @JavaMethod
  open func getPid() -> Int32

  @JavaMethod
  open func getRealUid() -> Int32

  @JavaMethod
  open func getPackageUid() -> Int32

  @JavaMethod
  open func getDefiningUid() -> Int32

  @JavaMethod
  open func getStatus() -> Int32

  @JavaMethod
  open func getPss() -> Int64

  @JavaMethod
  open func getRss() -> Int64

  @JavaMethod
  open func getProcessStateSummary() -> [Int8]

  @JavaMethod
  open func getTraceInputStream() throws -> InputStream!

  @JavaMethod
  open func getDescription() -> String

  @JavaMethod
  open func getImportance() -> Int32

  @JavaMethod
  open func getProcessName() -> String

  @JavaMethod
  open override func equals(_ arg0: JavaObject?) -> Bool

  @JavaMethod
  open override func toString() -> String

  @JavaMethod
  open override func hashCode() -> Int32

  @JavaMethod
  open func getTimestamp() -> Int64

  @JavaMethod
  open func getReason() -> Int32
}
extension JavaClass<ApplicationExitInfo> {
  @JavaStaticField(isFinal: true)
  public var REASON_ANR: Int32

  @JavaStaticField(isFinal: true)
  public var REASON_CRASH: Int32

  @JavaStaticField(isFinal: true)
  public var REASON_CRASH_NATIVE: Int32

  @JavaStaticField(isFinal: true)
  public var REASON_DEPENDENCY_DIED: Int32

  @JavaStaticField(isFinal: true)
  public var REASON_EXCESSIVE_RESOURCE_USAGE: Int32

  @JavaStaticField(isFinal: true)
  public var REASON_EXIT_SELF: Int32

  @JavaStaticField(isFinal: true)
  public var REASON_FREEZER: Int32

  @JavaStaticField(isFinal: true)
  public var REASON_INITIALIZATION_FAILURE: Int32

  @JavaStaticField(isFinal: true)
  public var REASON_LOW_MEMORY: Int32

  @JavaStaticField(isFinal: true)
  public var REASON_OTHER: Int32

  @JavaStaticField(isFinal: true)
  public var REASON_PERMISSION_CHANGE: Int32

  @JavaStaticField(isFinal: true)
  public var REASON_SIGNALED: Int32

  @JavaStaticField(isFinal: true)
  public var REASON_UNKNOWN: Int32

  @JavaStaticField(isFinal: true)
  public var REASON_USER_REQUESTED: Int32

  @JavaStaticField(isFinal: true)
  public var REASON_USER_STOPPED: Int32

  @JavaStaticField(isFinal: true)
  public var CONTENTS_FILE_DESCRIPTOR: Int32

  @JavaStaticField(isFinal: true)
  public var PARCELABLE_WRITE_RETURN_VALUE: Int32
}
