// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

extension ApplicationErrorReport {
  @JavaClass("android.app.ApplicationErrorReport$CrashInfo")
  open class CrashInfo: JavaObject {
  @JavaField(isFinal: false)
  public var exceptionClassName: String

  @JavaField(isFinal: false)
  public var exceptionMessage: String

  @JavaField(isFinal: false)
  public var stackTrace: String

  @JavaField(isFinal: false)
  public var throwClassName: String

  @JavaField(isFinal: false)
  public var throwFileName: String

  @JavaField(isFinal: false)
  public var throwLineNumber: Int32

  @JavaField(isFinal: false)
  public var throwMethodName: String

  @JavaMethod
  @_nonoverride public convenience init(_ arg0: Throwable?, environment: JNIEnvironment? = nil)

  @JavaMethod
  @_nonoverride public convenience init(environment: JNIEnvironment? = nil)
  }
}
