// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

extension AppOpsManager {
  @JavaInterface("android.app.AppOpsManager$OnOpChangedListener")
  public struct OnOpChangedListener {
  @JavaMethod
  public func onOpChanged(_ arg0: String, _ arg1: String)
  }
}
