// Auto-generated by Java-to-Swift wrapper generator.
import AndroidJavaIO
import JavaKit
import JavaRuntime

extension BlobStoreManager {
  @JavaClass("android.app.blob.BlobStoreManager$Session", implements: Closeable.self)
  open class Session: JavaObject {
  @JavaMethod
  open func abandon() throws

  @JavaMethod
  open func allowPackageAccess(_ arg0: String, _ arg1: [Int8]) throws

  @JavaMethod
  open func isPackageAccessAllowed(_ arg0: String, _ arg1: [Int8]) throws -> Bool

  @JavaMethod
  open func allowPublicAccess() throws

  @JavaMethod
  open func allowSameSignatureAccess() throws

  @JavaMethod
  open func isSameSignatureAccessAllowed() throws -> Bool

  @JavaMethod
  open func isPublicAccessAllowed() throws -> Bool

  @JavaMethod
  open func close() throws

  @JavaMethod
  open func getSize() throws -> Int64
  }
}
