// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava
import CSwiftJavaJNI

@JavaClass("android.app.backup.FileBackupHelper", implements: BackupHelper.self)
open class FileBackupHelper: JavaObject {
  @JavaMethod
  open func restoreEntity(_ arg0: BackupDataInputStream?)
}
