// Auto-generated by Java-to-Swift wrapper generator.
import JavaIO
import JavaLangIO
import SwiftJava
import CSwiftJavaJNI

@JavaClass("android.app.appsearch.GlobalSearchSession", implements: Closeable.self)
open class GlobalSearchSession: JavaObject {
  @JavaMethod
  open func unregisterObserverCallback(_ arg0: String, _ arg1: ObserverCallback?) throws

  @JavaMethod
  open func close()

  @JavaMethod
  open func search(_ arg0: String, _ arg1: SearchSpec?) -> SearchResults!
}
