// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

@JavaClass("android.app.job.JobInfo")
open class JobInfo: JavaObject {
  @JavaMethod
  open func describeContents() -> Int32

  @JavaMethod
  open func getClipGrantFlags() -> Int32

  @JavaMethod
  open func isRequireCharging() -> Bool

  @JavaMethod
  open func isRequireBatteryNotLow() -> Bool

  @JavaMethod
  open func isRequireDeviceIdle() -> Bool

  @JavaMethod
  open func isRequireStorageNotLow() -> Bool

  @JavaMethod
  open func getTriggerContentUris() -> [JobInfo.TriggerContentUri?]

  @JavaMethod
  open func getTriggerContentUpdateDelay() -> Int64

  @JavaMethod
  open func getTriggerContentMaxDelay() -> Int64

  @JavaMethod
  open func getNetworkType() -> Int32

  @JavaMethod
  open func getEstimatedNetworkDownloadBytes() -> Int64

  @JavaMethod
  open func getEstimatedNetworkUploadBytes() -> Int64

  @JavaMethod
  open func getMinimumNetworkChunkBytes() -> Int64

  @JavaMethod
  open func getMinLatencyMillis() -> Int64

  @JavaMethod
  open func getMaxExecutionDelayMillis() -> Int64

  @JavaMethod
  open func isPeriodic() -> Bool

  @JavaMethod
  open func getIntervalMillis() -> Int64

  @JavaMethod
  open func getFlexMillis() -> Int64

  @JavaMethod
  open func getInitialBackoffMillis() -> Int64

  @JavaMethod
  open func getBackoffPolicy() -> Int32

  @JavaMethod
  open func isExpedited() -> Bool

  @JavaMethod
  open func isImportantWhileForeground() -> Bool

  @JavaMethod
  open func isPrefetch() -> Bool

  @JavaMethod
  open func isPersisted() -> Bool

  @JavaMethod
  open override func equals(_ arg0: JavaObject?) -> Bool

  @JavaMethod
  open override func toString() -> String

  @JavaMethod
  open override func hashCode() -> Int32

  @JavaMethod
  open func getPriority() -> Int32

  @JavaMethod
  open func getId() -> Int32
}
extension JavaClass<JobInfo> {
  @JavaStaticField(isFinal: true)
  public var BACKOFF_POLICY_EXPONENTIAL: Int32

  @JavaStaticField(isFinal: true)
  public var BACKOFF_POLICY_LINEAR: Int32

  @JavaStaticField(isFinal: true)
  public var DEFAULT_INITIAL_BACKOFF_MILLIS: Int64

  @JavaStaticField(isFinal: true)
  public var MAX_BACKOFF_DELAY_MILLIS: Int64

  @JavaStaticField(isFinal: true)
  public var NETWORK_BYTES_UNKNOWN: Int32

  @JavaStaticField(isFinal: true)
  public var NETWORK_TYPE_ANY: Int32

  @JavaStaticField(isFinal: true)
  public var NETWORK_TYPE_CELLULAR: Int32

  @JavaStaticField(isFinal: true)
  public var NETWORK_TYPE_METERED: Int32

  @JavaStaticField(isFinal: true)
  public var NETWORK_TYPE_NONE: Int32

  @JavaStaticField(isFinal: true)
  public var NETWORK_TYPE_NOT_ROAMING: Int32

  @JavaStaticField(isFinal: true)
  public var NETWORK_TYPE_UNMETERED: Int32

  @JavaStaticField(isFinal: true)
  public var PRIORITY_DEFAULT: Int32

  @JavaStaticField(isFinal: true)
  public var PRIORITY_HIGH: Int32

  @JavaStaticField(isFinal: true)
  public var PRIORITY_LOW: Int32

  @JavaStaticField(isFinal: true)
  public var PRIORITY_MAX: Int32

  @JavaStaticField(isFinal: true)
  public var PRIORITY_MIN: Int32

  @JavaStaticField(isFinal: true)
  public var CONTENTS_FILE_DESCRIPTOR: Int32

  @JavaStaticField(isFinal: true)
  public var PARCELABLE_WRITE_RETURN_VALUE: Int32

  @JavaStaticMethod
  public func getMinPeriodMillis() -> Int64

  @JavaStaticMethod
  public func getMinFlexMillis() -> Int64
}
