// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava
import CSwiftJavaJNI

extension KeyguardManager {
  @JavaInterface("android.app.KeyguardManager$OnKeyguardExitResult")
  public struct OnKeyguardExitResult {
  @JavaMethod
  public func onKeyguardExitResult(_ arg0: Bool)
  }
}
