// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

extension LauncherActivity {
  @JavaClass("android.app.LauncherActivity$IconResizer")
  open class IconResizer: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: LauncherActivity?, environment: JNIEnvironment? = nil)
  }
}
