// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

@JavaClass("android.app.admin.NetworkEvent")
open class NetworkEvent: JavaObject {
  @JavaMethod
  open func describeContents() -> Int32

  @JavaMethod
  open func getPackageName() -> String

  @JavaMethod
  open func getId() -> Int64

  @JavaMethod
  open func getTimestamp() -> Int64
}
extension JavaClass<NetworkEvent> {
  @JavaStaticField(isFinal: true)
  public var CONTENTS_FILE_DESCRIPTOR: Int32

  @JavaStaticField(isFinal: true)
  public var PARCELABLE_WRITE_RETURN_VALUE: Int32
}
