// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava
import CSwiftJavaJNI

extension Notification {
  @JavaClass("android.app.Notification$DecoratedCustomViewStyle")
  open class DecoratedCustomViewStyle: Notification.Style {
  @JavaMethod
  @_nonoverride public convenience init(environment: JNIEnvironment? = nil)
  }
}
