// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

extension Notification {
  @JavaClass("android.app.Notification$MediaStyle")
  open class MediaStyle: Notification.Style {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: Notification.Builder?, environment: JNIEnvironment? = nil)

  @JavaMethod
  @_nonoverride public convenience init(environment: JNIEnvironment? = nil)

  @JavaMethod
  open func setShowActionsInCompactView(_ arg0: [Int32]) -> Notification.MediaStyle!
  }
}
