// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava
import CSwiftJavaJNI

@JavaInterface("android.app.appsearch.observer.ObserverCallback")
public struct ObserverCallback {
  @JavaMethod
  public func onSchemaChanged(_ arg0: SchemaChangeInfo?)

  @JavaMethod
  public func onDocumentChanged(_ arg0: DocumentChangeInfo?)
}
