// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

@JavaClass("android.app.PendingIntent")
open class PendingIntent: JavaObject {
  @JavaMethod
  open func send(_ arg0: Int32) throws

  @JavaMethod
  open func send() throws

  @JavaMethod
  open func getTargetPackage() -> String

  @JavaMethod
  open func getCreatorPackage() -> String

  @JavaMethod
  open func getCreatorUid() -> Int32

  @JavaMethod
  open func isActivity() -> Bool

  @JavaMethod
  open func isForegroundService() -> Bool

  @JavaMethod
  open func isService() -> Bool

  @JavaMethod
  open func isBroadcast() -> Bool

  @JavaMethod
  open func describeContents() -> Int32

  @JavaMethod
  open override func equals(_ arg0: JavaObject?) -> Bool

  @JavaMethod
  open override func toString() -> String

  @JavaMethod
  open override func hashCode() -> Int32

  @JavaMethod
  open func cancel()

  @JavaMethod
  open func isImmutable() -> Bool
}
extension JavaClass<PendingIntent> {
  @JavaStaticField(isFinal: true)
  public var FLAG_CANCEL_CURRENT: Int32

  @JavaStaticField(isFinal: true)
  public var FLAG_IMMUTABLE: Int32

  @JavaStaticField(isFinal: true)
  public var FLAG_MUTABLE: Int32

  @JavaStaticField(isFinal: true)
  public var FLAG_NO_CREATE: Int32

  @JavaStaticField(isFinal: true)
  public var FLAG_ONE_SHOT: Int32

  @JavaStaticField(isFinal: true)
  public var FLAG_UPDATE_CURRENT: Int32

  @JavaStaticField(isFinal: true)
  public var CONTENTS_FILE_DESCRIPTOR: Int32

  @JavaStaticField(isFinal: true)
  public var PARCELABLE_WRITE_RETURN_VALUE: Int32
}
