// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava
import CSwiftJavaJNI

extension PendingIntent {
  @JavaInterface("android.app.PendingIntent$OnFinished")
  public struct OnFinished {

  }
}
