// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaKitCollection
import JavaRuntime

@JavaClass("android.app.PictureInPictureParams")
open class PictureInPictureParams: JavaObject {
  @JavaMethod
  open func describeContents() -> Int32

  @JavaMethod
  open func getTitle() -> CharSequence!

  @JavaMethod
  open func getCloseAction() -> RemoteAction!

  @JavaMethod
  open func isAutoEnterEnabled() -> Bool

  @JavaMethod
  open func isSeamlessResizeEnabled() -> Bool

  @JavaMethod
  open func getSubtitle() -> CharSequence!

  @JavaMethod
  open override func equals(_ arg0: JavaObject?) -> Bool

  @JavaMethod
  open override func toString() -> String

  @JavaMethod
  open override func hashCode() -> Int32

  @JavaMethod
  open func getActions() -> List<RemoteAction>!
}
extension JavaClass<PictureInPictureParams> {
  @JavaStaticField(isFinal: true)
  public var CONTENTS_FILE_DESCRIPTOR: Int32

  @JavaStaticField(isFinal: true)
  public var PARCELABLE_WRITE_RETURN_VALUE: Int32
}
