// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava
import CSwiftJavaJNI

@JavaClass("android.app.appsearch.RemoveByDocumentIdRequest")
open class RemoveByDocumentIdRequest: JavaObject {
  @JavaMethod
  open func getIds() -> JavaSet<JavaString>!

  @JavaMethod
  open func getNamespace() -> String
}
