// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

extension SearchManager {
  @JavaInterface("android.app.SearchManager$OnDismissListener")
  public struct OnDismissListener {
  @JavaMethod
  public func onDismiss()
  }
}
