// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

extension SearchResult {
  @JavaClass("android.app.appsearch.SearchResult$MatchInfo")
  open class MatchInfo: JavaObject {
  @JavaMethod
  open func getPropertyPath() -> String

  @JavaMethod
  open func getFullText() -> String

  @JavaMethod
  open func getExactMatchRange() -> SearchResult.MatchRange!

  @JavaMethod
  open func getExactMatch() -> CharSequence!

  @JavaMethod
  open func getSubmatchRange() -> SearchResult.MatchRange!

  @JavaMethod
  open func getSubmatch() -> CharSequence!

  @JavaMethod
  open func getSnippetRange() -> SearchResult.MatchRange!

  @JavaMethod
  open func getSnippet() -> CharSequence!
  }
}
