// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava
import CSwiftJavaJNI

extension TimePickerDialog {
  @JavaInterface("android.app.TimePickerDialog$OnTimeSetListener")
  public struct OnTimeSetListener {

  }
}
