// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaKitCollection
import JavaRuntime

@JavaClass("java.nio.file.attribute.AclEntry")
open class AclEntry: JavaObject {
  @JavaMethod
  open func principal() -> UserPrincipal!

  @JavaMethod
  open func type() -> AclEntryType!

  @JavaMethod
  open override func equals(_ arg0: JavaObject?) -> Bool

  @JavaMethod
  open override func toString() -> String

  @JavaMethod
  open func flags() -> JavaSet<AclEntryFlag>!

  @JavaMethod
  open override func hashCode() -> Int32

  @JavaMethod
  open func permissions() -> JavaSet<AclEntryPermission>!
}
extension JavaClass<AclEntry> {
  @JavaStaticMethod
  public func newBuilder(_ arg0: AclEntry?) -> AclEntry.Builder!

  @JavaStaticMethod
  public func newBuilder() -> AclEntry.Builder!
}
