// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

@JavaClass("java.nio.charset.CharsetDecoder")
open class CharsetDecoder: JavaObject {
  @JavaMethod
  open func averageCharsPerByte() -> Float

  @JavaMethod
  open func decodeLoop(_ arg0: ByteBuffer?, _ arg1: CharBuffer?) -> CoderResult!

  @JavaMethod
  open func isAutoDetecting() -> Bool

  @JavaMethod
  open func isCharsetDetected() -> Bool

  @JavaMethod
  open func detectedCharset() -> Charset!

  @JavaMethod
  open func reset() -> CharsetDecoder!

  @JavaMethod
  open func maxCharsPerByte() -> Float

  @JavaMethod
  open func onMalformedInput(_ arg0: CodingErrorAction?) -> CharsetDecoder!

  @JavaMethod
  open func onUnmappableCharacter(_ arg0: CodingErrorAction?) -> CharsetDecoder!

  @JavaMethod
  open func decode(_ arg0: ByteBuffer?, _ arg1: CharBuffer?, _ arg2: Bool) -> CoderResult!

  @JavaMethod
  open func decode(_ arg0: ByteBuffer?) throws -> CharBuffer!

  @JavaMethod
  open func flush(_ arg0: CharBuffer?) -> CoderResult!

  @JavaMethod
  open func charset() -> Charset!

  @JavaMethod
  open func replacement() -> String

  @JavaMethod
  open func implFlush(_ arg0: CharBuffer?) -> CoderResult!

  @JavaMethod
  open func malformedInputAction() -> CodingErrorAction!

  @JavaMethod
  open func unmappableCharacterAction() -> CodingErrorAction!

  @JavaMethod
  open func replaceWith(_ arg0: String) -> CharsetDecoder!

  @JavaMethod
  open func implReplaceWith(_ arg0: String)

  @JavaMethod
  open func implOnMalformedInput(_ arg0: CodingErrorAction?)

  @JavaMethod
  open func implOnUnmappableCharacter(_ arg0: CodingErrorAction?)

  @JavaMethod
  open func implReset()
}
