// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

@JavaInterface("java.nio.channels.CompletionHandler")
public struct CompletionHandler<V: AnyJavaObject, A: AnyJavaObject> {
  @JavaMethod
  public func failed(_ arg0: Throwable?, _ arg1: JavaObject?)

  @JavaMethod
  public func completed(_ arg0: JavaObject?, _ arg1: JavaObject?)
}
