// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

@JavaInterface("java.nio.file.attribute.DosFileAttributeView", extends: BasicFileAttributeView.self)
public struct DosFileAttributeView {
  @JavaMethod
  public func setHidden(_ arg0: Bool) throws

  @JavaMethod
  public func setSystem(_ arg0: Bool) throws

  @JavaMethod
  public func setArchive(_ arg0: Bool) throws

  @JavaMethod
  public func name() -> String

  @JavaMethod
  public func setReadOnly(_ arg0: Bool) throws

  @JavaMethod
  public func readAttributes() throws -> DosFileAttributes!

  @JavaMethod
  public func readAttributes() throws -> BasicFileAttributes!

  @JavaMethod
  public func setTimes(_ arg0: FileTime?, _ arg1: FileTime?, _ arg2: FileTime?) throws
}
