// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

@JavaClass("java.nio.charset.MalformedInputException")
open class MalformedInputException: CharacterCodingException {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: Int32, environment: JNIEnvironment? = nil)

  @JavaMethod
  open func getInputLength() -> Int32

  @JavaMethod
  open override func getMessage() -> String
}
