// Auto-generated by Java-to-Swift wrapper generator.
import AndroidContent
import SwiftJava
import SwiftJavaJNICore

@available(*, deprecated)
@JavaClass("android.net.rtp.AudioGroup")
open class AudioGroup: JavaObject {
  @available(*, deprecated)
  @JavaMethod
  @_nonoverride public convenience init(environment: JNIEnvironment? = nil)

  @available(*, deprecated)
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: Context?, environment: JNIEnvironment? = nil)

    /// Java method `getStreams`.
    ///
    /// ### Java method signature
    /// ```java
    /// public android.net.rtp.AudioStream[] android.net.rtp.AudioGroup.getStreams()
    /// ```
  @available(*, deprecated)
  @JavaMethod
  open func getStreams() -> [AudioStream?]

    /// Java method `getMode`.
    ///
    /// ### Java method signature
    /// ```java
    /// public int android.net.rtp.AudioGroup.getMode()
    /// ```
  @available(*, deprecated)
  @JavaMethod
  open func getMode() -> Int32

    /// Java method `setMode`.
    ///
    /// ### Java method signature
    /// ```java
    /// public void android.net.rtp.AudioGroup.setMode(int)
    /// ```
  @available(*, deprecated)
  @JavaMethod
  open func setMode(_ arg0: Int32)

    /// Java method `sendDtmf`.
    ///
    /// ### Java method signature
    /// ```java
    /// public void android.net.rtp.AudioGroup.sendDtmf(int)
    /// ```
  @available(*, deprecated)
  @JavaMethod
  open func sendDtmf(_ arg0: Int32)

    /// Java method `finalize`.
    ///
    /// ### Java method signature
    /// ```java
    /// protected void android.net.rtp.AudioGroup.finalize() throws java.lang.Throwable
    /// ```
  @available(*, deprecated)
  @JavaMethod
  open override func finalize() throws

    /// Java method `clear`.
    ///
    /// ### Java method signature
    /// ```java
    /// public void android.net.rtp.AudioGroup.clear()
    /// ```
  @available(*, deprecated)
  @JavaMethod
  open func clear()
}
extension JavaClass<AudioGroup> {
  @available(*, deprecated)
  @JavaStaticField(isFinal: true)
  public var MODE_ECHO_SUPPRESSION: Int32

  @available(*, deprecated)
  @JavaStaticField(isFinal: true)
  public var MODE_MUTED: Int32

  @available(*, deprecated)
  @JavaStaticField(isFinal: true)
  public var MODE_NORMAL: Int32

  @available(*, deprecated)
  @JavaStaticField(isFinal: true)
  public var MODE_ON_HOLD: Int32
}
