// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava
import SwiftJavaJNICore

extension ChildSaProposal {
  @JavaClass("android.net.ipsec.ike.ChildSaProposal$Builder")
  open class Builder: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(environment: JNIEnvironment? = nil)

    /// Java method `addDhGroup`.
    ///
    /// ### Java method signature
    /// ```java
    /// public android.net.ipsec.ike.ChildSaProposal$Builder android.net.ipsec.ike.ChildSaProposal$Builder.addDhGroup(int)
    /// ```
  @JavaMethod
  open func addDhGroup(_ arg0: Int32) -> ChildSaProposal.Builder!

    /// Java method `addEncryptionAlgorithm`.
    ///
    /// ### Java method signature
    /// ```java
    /// public android.net.ipsec.ike.ChildSaProposal$Builder android.net.ipsec.ike.ChildSaProposal$Builder.addEncryptionAlgorithm(int,int)
    /// ```
  @JavaMethod
  open func addEncryptionAlgorithm(_ arg0: Int32, _ arg1: Int32) -> ChildSaProposal.Builder!

    /// Java method `addIntegrityAlgorithm`.
    ///
    /// ### Java method signature
    /// ```java
    /// public android.net.ipsec.ike.ChildSaProposal$Builder android.net.ipsec.ike.ChildSaProposal$Builder.addIntegrityAlgorithm(int)
    /// ```
  @JavaMethod
  open func addIntegrityAlgorithm(_ arg0: Int32) -> ChildSaProposal.Builder!

    /// Java method `build`.
    ///
    /// ### Java method signature
    /// ```java
    /// public android.net.ipsec.ike.ChildSaProposal android.net.ipsec.ike.ChildSaProposal$Builder.build()
    /// ```
  @JavaMethod
  open func build() -> ChildSaProposal!
  }
}
