// Auto-generated by Java-to-Swift wrapper generator.
import AndroidOS
import SwiftJava
import SwiftJavaJNICore

@available(Android 30, *)
extension ConnectivityDiagnosticsManager {
  @JavaClass("android.net.ConnectivityDiagnosticsManager$DataStallReport", implements: Parcelable.self)
  open class DataStallReport: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: Network?, _ arg1: Int64, _ arg2: Int32, _ arg3: LinkProperties?, _ arg4: NetworkCapabilities?, _ arg5: PersistableBundle?, environment: JNIEnvironment? = nil)

    /// Java method `getNetworkCapabilities`.
    ///
    /// ### Java method signature
    /// ```java
    /// public android.net.NetworkCapabilities android.net.ConnectivityDiagnosticsManager$DataStallReport.getNetworkCapabilities()
    /// ```
  @JavaMethod
  open func getNetworkCapabilities() -> NetworkCapabilities!

    /// Java method `describeContents`.
    ///
    /// ### Java method signature
    /// ```java
    /// public int android.net.ConnectivityDiagnosticsManager$DataStallReport.describeContents()
    /// ```
  @JavaMethod
  open func describeContents() -> Int32

    /// Java method `writeToParcel`.
    ///
    /// ### Java method signature
    /// ```java
    /// public void android.net.ConnectivityDiagnosticsManager$DataStallReport.writeToParcel(android.os.Parcel,int)
    /// ```
  @JavaMethod
  open func writeToParcel(_ arg0: Parcel?, _ arg1: Int32)

    /// Java method `getReportTimestamp`.
    ///
    /// ### Java method signature
    /// ```java
    /// public long android.net.ConnectivityDiagnosticsManager$DataStallReport.getReportTimestamp()
    /// ```
  @JavaMethod
  open func getReportTimestamp() -> Int64

    /// Java method `getLinkProperties`.
    ///
    /// ### Java method signature
    /// ```java
    /// public android.net.LinkProperties android.net.ConnectivityDiagnosticsManager$DataStallReport.getLinkProperties()
    /// ```
  @JavaMethod
  open func getLinkProperties() -> LinkProperties!

    /// Java method `getDetectionMethod`.
    ///
    /// ### Java method signature
    /// ```java
    /// public int android.net.ConnectivityDiagnosticsManager$DataStallReport.getDetectionMethod()
    /// ```
  @JavaMethod
  open func getDetectionMethod() -> Int32

    /// Java method `getStallDetails`.
    ///
    /// ### Java method signature
    /// ```java
    /// public android.os.PersistableBundle android.net.ConnectivityDiagnosticsManager$DataStallReport.getStallDetails()
    /// ```
  @JavaMethod
  open func getStallDetails() -> PersistableBundle!

    /// Java method `getNetwork`.
    ///
    /// ### Java method signature
    /// ```java
    /// public android.net.Network android.net.ConnectivityDiagnosticsManager$DataStallReport.getNetwork()
    /// ```
  @JavaMethod
  open func getNetwork() -> Network!

    /// Java method `equals`.
    ///
    /// ### Java method signature
    /// ```java
    /// public boolean android.net.ConnectivityDiagnosticsManager$DataStallReport.equals(java.lang.Object)
    /// ```
  @JavaMethod
  open override func equals(_ arg0: JavaObject?) -> Bool

    /// Java method `hashCode`.
    ///
    /// ### Java method signature
    /// ```java
    /// public int android.net.ConnectivityDiagnosticsManager$DataStallReport.hashCode()
    /// ```
  @JavaMethod
  open override func hashCode() -> Int32
  }
}
@available(Android 30, *)
extension JavaClass<ConnectivityDiagnosticsManager.DataStallReport> {
  @JavaStaticField(isFinal: true)
  public var CREATOR: Parcelable.Creator<ConnectivityDiagnosticsManager.DataStallReport>!

  @JavaStaticField(isFinal: true)
  public var DETECTION_METHOD_DNS_EVENTS: Int32

  @JavaStaticField(isFinal: true)
  public var DETECTION_METHOD_TCP_METRICS: Int32

  @JavaStaticField(isFinal: true)
  public var KEY_DNS_CONSECUTIVE_TIMEOUTS: String

  @JavaStaticField(isFinal: true)
  public var KEY_TCP_METRICS_COLLECTION_PERIOD_MILLIS: String

  @JavaStaticField(isFinal: true)
  public var KEY_TCP_PACKET_FAIL_RATE: String
}
