// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava
import SwiftJavaJNICore

@JavaClass("android.net.Credentials")
open class Credentials: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: Int32, _ arg1: Int32, _ arg2: Int32, environment: JNIEnvironment? = nil)

    /// Java method `getPid`.
    ///
    /// ### Java method signature
    /// ```java
    /// public int android.net.Credentials.getPid()
    /// ```
  @JavaMethod
  open func getPid() -> Int32

    /// Java method `getUid`.
    ///
    /// ### Java method signature
    /// ```java
    /// public int android.net.Credentials.getUid()
    /// ```
  @JavaMethod
  open func getUid() -> Int32

    /// Java method `getGid`.
    ///
    /// ### Java method signature
    /// ```java
    /// public int android.net.Credentials.getGid()
    /// ```
  @JavaMethod
  open func getGid() -> Int32
}
