// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava
import SwiftJavaJNICore

@JavaClass("android.net.ipsec.ike.exceptions.IkeInternalException")
open class IkeInternalException: IkeNonProtocolException {

}
