// Auto-generated by Java-to-Swift wrapper generator.
import JavaLangNet
import SwiftJava
import SwiftJavaJNICore

@JavaClass("android.net.ipsec.ike.IkeTrafficSelector")
open class IkeTrafficSelector: JavaObject {
  @JavaField(isFinal: true)
  public var endPort: Int32

  @JavaField(isFinal: true)
  public var endingAddress: InetAddress!

  @JavaField(isFinal: true)
  public var startPort: Int32

  @JavaField(isFinal: true)
  public var startingAddress: InetAddress!

  @JavaMethod
  @_nonoverride public convenience init(_ arg0: Int32, _ arg1: Int32, _ arg2: InetAddress?, _ arg3: InetAddress?, environment: JNIEnvironment? = nil)

    /// Java method `equals`.
    ///
    /// ### Java method signature
    /// ```java
    /// public boolean android.net.ipsec.ike.IkeTrafficSelector.equals(java.lang.Object)
    /// ```
  @JavaMethod
  open override func equals(_ arg0: JavaObject?) -> Bool

    /// Java method `hashCode`.
    ///
    /// ### Java method signature
    /// ```java
    /// public int android.net.ipsec.ike.IkeTrafficSelector.hashCode()
    /// ```
  @JavaMethod
  open override func hashCode() -> Int32
}
