// Auto-generated by Java-to-Swift wrapper generator.
import AndroidContent
import SwiftJava
import SwiftJavaJNICore

@JavaClass("android.net.Proxy")
open class Proxy: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(environment: JNIEnvironment? = nil)
}
extension JavaClass<Proxy> {
  @JavaStaticField(isFinal: true)
  public var PROXY_CHANGE_ACTION: String

    /// Java method `getDefaultHost`.
    ///
    /// ### Java method signature
    /// ```java
    /// public static java.lang.String android.net.Proxy.getDefaultHost()
    /// ```
  @available(*, deprecated)
  @JavaStaticMethod
  public func getDefaultHost() -> String

    /// Java method `getHost`.
    ///
    /// ### Java method signature
    /// ```java
    /// public static java.lang.String android.net.Proxy.getHost(android.content.Context)
    /// ```
  @available(*, deprecated)
  @JavaStaticMethod
  public func getHost(_ arg0: Context?) -> String

    /// Java method `getPort`.
    ///
    /// ### Java method signature
    /// ```java
    /// public static int android.net.Proxy.getPort(android.content.Context)
    /// ```
  @available(*, deprecated)
  @JavaStaticMethod
  public func getPort(_ arg0: Context?) -> Int32

    /// Java method `getDefaultPort`.
    ///
    /// ### Java method signature
    /// ```java
    /// public static int android.net.Proxy.getDefaultPort()
    /// ```
  @available(*, deprecated)
  @JavaStaticMethod
  public func getDefaultPort() -> Int32
}
