// Auto-generated by Java-to-Swift wrapper generator.
import AndroidOS
import SwiftJava
import SwiftJavaJNICore

@available(Android 28, *)
@JavaClass("android.net.wifi.rtt.RangingRequest", implements: Parcelable.self)
open class RangingRequest: JavaObject {
  /// Java method `describeContents`.
  ///
  /// ### Java method signature
  /// ```java
  /// public int android.net.wifi.rtt.RangingRequest.describeContents()
  /// ```
@JavaMethod
  open func describeContents() -> Int32

  /// Java method `writeToParcel`.
  ///
  /// ### Java method signature
  /// ```java
  /// public void android.net.wifi.rtt.RangingRequest.writeToParcel(android.os.Parcel,int)
  /// ```
@JavaMethod
  open func writeToParcel(_ arg0: Parcel?, _ arg1: Int32)

  /// Java method `getRttBurstSize`.
  ///
  /// ### Java method signature
  /// ```java
  /// public int android.net.wifi.rtt.RangingRequest.getRttBurstSize()
  /// ```
@JavaMethod
  open func getRttBurstSize() -> Int32

  /// Java method `equals`.
  ///
  /// ### Java method signature
  /// ```java
  /// public boolean android.net.wifi.rtt.RangingRequest.equals(java.lang.Object)
  /// ```
@JavaMethod
  open override func equals(_ arg0: JavaObject?) -> Bool

  /// Java method `toString`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.lang.String android.net.wifi.rtt.RangingRequest.toString()
  /// ```
@JavaMethod
  open override func toString() -> String

  /// Java method `hashCode`.
  ///
  /// ### Java method signature
  /// ```java
  /// public int android.net.wifi.rtt.RangingRequest.hashCode()
  /// ```
@JavaMethod
  open override func hashCode() -> Int32
}
@available(Android 28, *)
extension JavaClass<RangingRequest> {
  @JavaStaticField(isFinal: true)
  public var CREATOR: Parcelable.Creator<RangingRequest>!

    /// Java method `getDefaultRttBurstSize`.
    ///
    /// ### Java method signature
    /// ```java
    /// public static int android.net.wifi.rtt.RangingRequest.getDefaultRttBurstSize()
    /// ```
  @JavaStaticMethod
  public func getDefaultRttBurstSize() -> Int32

    /// Java method `getMaxPeers`.
    ///
    /// ### Java method signature
    /// ```java
    /// public static int android.net.wifi.rtt.RangingRequest.getMaxPeers()
    /// ```
  @JavaStaticMethod
  public func getMaxPeers() -> Int32

    /// Java method `getMinRttBurstSize`.
    ///
    /// ### Java method signature
    /// ```java
    /// public static int android.net.wifi.rtt.RangingRequest.getMinRttBurstSize()
    /// ```
  @JavaStaticMethod
  public func getMinRttBurstSize() -> Int32

    /// Java method `getMaxRttBurstSize`.
    ///
    /// ### Java method signature
    /// ```java
    /// public static int android.net.wifi.rtt.RangingRequest.getMaxRttBurstSize()
    /// ```
  @JavaStaticMethod
  public func getMaxRttBurstSize() -> Int32
}
