// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava
import SwiftJavaJNICore

@available(Android 29, *)
@JavaClass("android.net.SocketKeepalive")
open class SocketKeepalive: JavaObject {
  /// Java method `start`.
  ///
  /// ### Java method signature
  /// ```java
  /// public final void android.net.SocketKeepalive.start(int)
  /// ```
@JavaMethod
  open func start(_ arg0: Int32)

  /// Java method `stop`.
  ///
  /// ### Java method signature
  /// ```java
  /// public final void android.net.SocketKeepalive.stop()
  /// ```
@JavaMethod
  open func stop()

  /// Java method `close`.
  ///
  /// ### Java method signature
  /// ```java
  /// public final void android.net.SocketKeepalive.close()
  /// ```
@JavaMethod
  open func close()
}
@available(Android 29, *)
extension JavaClass<SocketKeepalive> {
  @JavaStaticField(isFinal: true)
  public var ERROR_HARDWARE_ERROR: Int32

  @JavaStaticField(isFinal: true)
  public var ERROR_INSUFFICIENT_RESOURCES: Int32

  @JavaStaticField(isFinal: true)
  public var ERROR_INVALID_INTERVAL: Int32

  @JavaStaticField(isFinal: true)
  public var ERROR_INVALID_IP_ADDRESS: Int32

  @JavaStaticField(isFinal: true)
  public var ERROR_INVALID_LENGTH: Int32

  @JavaStaticField(isFinal: true)
  public var ERROR_INVALID_NETWORK: Int32

  @JavaStaticField(isFinal: true)
  public var ERROR_INVALID_PORT: Int32

  @JavaStaticField(isFinal: true)
  public var ERROR_INVALID_SOCKET: Int32

  @JavaStaticField(isFinal: true)
  public var ERROR_SOCKET_NOT_IDLE: Int32

  @JavaStaticField(isFinal: true)
  public var ERROR_UNSUPPORTED: Int32
}
