// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava
import SwiftJavaJNICore

extension TelephonyNetworkSpecifier {
  @JavaClass("android.net.TelephonyNetworkSpecifier$Builder")
  open class Builder: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(environment: JNIEnvironment? = nil)

    /// Java method `setSubscriptionId`.
    ///
    /// ### Java method signature
    /// ```java
    /// public android.net.TelephonyNetworkSpecifier$Builder android.net.TelephonyNetworkSpecifier$Builder.setSubscriptionId(int)
    /// ```
  @JavaMethod
  open func setSubscriptionId(_ arg0: Int32) -> TelephonyNetworkSpecifier.Builder!

    /// Java method `build`.
    ///
    /// ### Java method signature
    /// ```java
    /// public android.net.TelephonyNetworkSpecifier android.net.TelephonyNetworkSpecifier$Builder.build()
    /// ```
  @JavaMethod
  open func build() -> TelephonyNetworkSpecifier!
  }
}
