// Auto-generated by Java-to-Swift wrapper generator.
import JavaLangNet
import SwiftJava
import SwiftJavaJNICore

extension TunnelModeChildSessionParams {
  @JavaClass("android.net.ipsec.ike.TunnelModeChildSessionParams$Builder")
  open class Builder: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(environment: JNIEnvironment? = nil)

  @JavaMethod
  @_nonoverride public convenience init(_ arg0: TunnelModeChildSessionParams?, environment: JNIEnvironment? = nil)

    /// Java method `setLifetimeSeconds`.
    ///
    /// ### Java method signature
    /// ```java
    /// public android.net.ipsec.ike.TunnelModeChildSessionParams$Builder android.net.ipsec.ike.TunnelModeChildSessionParams$Builder.setLifetimeSeconds(int,int)
    /// ```
  @JavaMethod
  open func setLifetimeSeconds(_ arg0: Int32, _ arg1: Int32) -> TunnelModeChildSessionParams.Builder!

    /// Java method `addChildSaProposal`.
    ///
    /// ### Java method signature
    /// ```java
    /// public android.net.ipsec.ike.TunnelModeChildSessionParams$Builder android.net.ipsec.ike.TunnelModeChildSessionParams$Builder.addChildSaProposal(android.net.ipsec.ike.ChildSaProposal)
    /// ```
  @JavaMethod
  open func addChildSaProposal(_ arg0: ChildSaProposal?) -> TunnelModeChildSessionParams.Builder!

    /// Java method `addInboundTrafficSelectors`.
    ///
    /// ### Java method signature
    /// ```java
    /// public android.net.ipsec.ike.TunnelModeChildSessionParams$Builder android.net.ipsec.ike.TunnelModeChildSessionParams$Builder.addInboundTrafficSelectors(android.net.ipsec.ike.IkeTrafficSelector)
    /// ```
  @JavaMethod
  open func addInboundTrafficSelectors(_ arg0: IkeTrafficSelector?) -> TunnelModeChildSessionParams.Builder!

    /// Java method `addOutboundTrafficSelectors`.
    ///
    /// ### Java method signature
    /// ```java
    /// public android.net.ipsec.ike.TunnelModeChildSessionParams$Builder android.net.ipsec.ike.TunnelModeChildSessionParams$Builder.addOutboundTrafficSelectors(android.net.ipsec.ike.IkeTrafficSelector)
    /// ```
  @JavaMethod
  open func addOutboundTrafficSelectors(_ arg0: IkeTrafficSelector?) -> TunnelModeChildSessionParams.Builder!

    /// Java method `addInternalAddressRequest`.
    ///
    /// ### Java method signature
    /// ```java
    /// public android.net.ipsec.ike.TunnelModeChildSessionParams$Builder android.net.ipsec.ike.TunnelModeChildSessionParams$Builder.addInternalAddressRequest(java.net.Inet4Address)
    /// ```
  @JavaMethod
  open func addInternalAddressRequest(_ arg0: Inet4Address?) -> TunnelModeChildSessionParams.Builder!

    /// Java method `addInternalAddressRequest`.
    ///
    /// ### Java method signature
    /// ```java
    /// public android.net.ipsec.ike.TunnelModeChildSessionParams$Builder android.net.ipsec.ike.TunnelModeChildSessionParams$Builder.addInternalAddressRequest(java.net.Inet6Address,int)
    /// ```
  @JavaMethod
  open func addInternalAddressRequest(_ arg0: Inet6Address?, _ arg1: Int32) -> TunnelModeChildSessionParams.Builder!

    /// Java method `addInternalAddressRequest`.
    ///
    /// ### Java method signature
    /// ```java
    /// public android.net.ipsec.ike.TunnelModeChildSessionParams$Builder android.net.ipsec.ike.TunnelModeChildSessionParams$Builder.addInternalAddressRequest(int)
    /// ```
  @JavaMethod
  open func addInternalAddressRequest(_ arg0: Int32) -> TunnelModeChildSessionParams.Builder!

    /// Java method `addInternalDnsServerRequest`.
    ///
    /// ### Java method signature
    /// ```java
    /// public android.net.ipsec.ike.TunnelModeChildSessionParams$Builder android.net.ipsec.ike.TunnelModeChildSessionParams$Builder.addInternalDnsServerRequest(int)
    /// ```
  @JavaMethod
  open func addInternalDnsServerRequest(_ arg0: Int32) -> TunnelModeChildSessionParams.Builder!

    /// Java method `addInternalDhcpServerRequest`.
    ///
    /// ### Java method signature
    /// ```java
    /// public android.net.ipsec.ike.TunnelModeChildSessionParams$Builder android.net.ipsec.ike.TunnelModeChildSessionParams$Builder.addInternalDhcpServerRequest(int)
    /// ```
  @JavaMethod
  open func addInternalDhcpServerRequest(_ arg0: Int32) -> TunnelModeChildSessionParams.Builder!

    /// Java method `build`.
    ///
    /// ### Java method signature
    /// ```java
    /// public android.net.ipsec.ike.TunnelModeChildSessionParams android.net.ipsec.ike.TunnelModeChildSessionParams$Builder.build()
    /// ```
  @JavaMethod
  open func build() -> TunnelModeChildSessionParams!
  }
}
