// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava
import SwiftJavaJNICore

@available(Android 31, *)
extension TunnelModeChildSessionParams {
  @JavaInterface("android.net.ipsec.ike.TunnelModeChildSessionParams$TunnelModeChildConfigRequest")
  public struct TunnelModeChildConfigRequest {

  }
}
