// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava
import SwiftJavaJNICore

@available(Android 14, *)
@JavaClass("android.net.wifi.p2p.nsd.WifiP2pUpnpServiceRequest")
open class WifiP2pUpnpServiceRequest: WifiP2pServiceRequest {

}
@available(Android 14, *)
extension JavaClass<WifiP2pUpnpServiceRequest> {
  /// Java method `newInstance`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static android.net.wifi.p2p.nsd.WifiP2pUpnpServiceRequest android.net.wifi.p2p.nsd.WifiP2pUpnpServiceRequest.newInstance()
  /// ```
@JavaStaticMethod
  public func newInstance() -> WifiP2pUpnpServiceRequest!

  /// Java method `newInstance`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static android.net.wifi.p2p.nsd.WifiP2pUpnpServiceRequest android.net.wifi.p2p.nsd.WifiP2pUpnpServiceRequest.newInstance(java.lang.String)
  /// ```
@JavaStaticMethod
  public func newInstance(_ arg0: String) -> WifiP2pUpnpServiceRequest!
}
