// Auto-generated by Java-to-Swift wrapper generator.
import AndroidOS
import SwiftJava
import SwiftJavaJNICore

extension WifiNetworkSuggestion {
  @JavaClass("android.net.wifi.WifiNetworkSuggestion$Builder")
  open class Builder: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(environment: JNIEnvironment? = nil)

    /// Java method `setSsid`.
    ///
    /// ### Java method signature
    /// ```java
    /// public android.net.wifi.WifiNetworkSuggestion$Builder android.net.wifi.WifiNetworkSuggestion$Builder.setSsid(java.lang.String)
    /// ```
  @JavaMethod
  open func setSsid(_ arg0: String) -> WifiNetworkSuggestion.Builder!

    /// Java method `setBssid`.
    ///
    /// ### Java method signature
    /// ```java
    /// public android.net.wifi.WifiNetworkSuggestion$Builder android.net.wifi.WifiNetworkSuggestion$Builder.setBssid(android.net.MacAddress)
    /// ```
  @JavaMethod
  open func setBssid(_ arg0: MacAddress?) -> WifiNetworkSuggestion.Builder!

    /// Java method `setSubscriptionId`.
    ///
    /// ### Java method signature
    /// ```java
    /// public android.net.wifi.WifiNetworkSuggestion$Builder android.net.wifi.WifiNetworkSuggestion$Builder.setSubscriptionId(int)
    /// ```
  @JavaMethod
  open func setSubscriptionId(_ arg0: Int32) -> WifiNetworkSuggestion.Builder!

    /// Java method `setWpa2EnterpriseConfig`.
    ///
    /// ### Java method signature
    /// ```java
    /// public android.net.wifi.WifiNetworkSuggestion$Builder android.net.wifi.WifiNetworkSuggestion$Builder.setWpa2EnterpriseConfig(android.net.wifi.WifiEnterpriseConfig)
    /// ```
  @JavaMethod
  open func setWpa2EnterpriseConfig(_ arg0: WifiEnterpriseConfig?) -> WifiNetworkSuggestion.Builder!

    /// Java method `setWpa3EnterpriseConfig`.
    ///
    /// ### Java method signature
    /// ```java
    /// public android.net.wifi.WifiNetworkSuggestion$Builder android.net.wifi.WifiNetworkSuggestion$Builder.setWpa3EnterpriseConfig(android.net.wifi.WifiEnterpriseConfig)
    /// ```
  @available(*, deprecated)
  @JavaMethod
  open func setWpa3EnterpriseConfig(_ arg0: WifiEnterpriseConfig?) -> WifiNetworkSuggestion.Builder!

    /// Java method `setWpa3Enterprise192BitModeConfig`.
    ///
    /// ### Java method signature
    /// ```java
    /// public android.net.wifi.WifiNetworkSuggestion$Builder android.net.wifi.WifiNetworkSuggestion$Builder.setWpa3Enterprise192BitModeConfig(android.net.wifi.WifiEnterpriseConfig)
    /// ```
  @JavaMethod
  open func setWpa3Enterprise192BitModeConfig(_ arg0: WifiEnterpriseConfig?) -> WifiNetworkSuggestion.Builder!

    /// Java method `setWpa3EnterpriseStandardModeConfig`.
    ///
    /// ### Java method signature
    /// ```java
    /// public android.net.wifi.WifiNetworkSuggestion$Builder android.net.wifi.WifiNetworkSuggestion$Builder.setWpa3EnterpriseStandardModeConfig(android.net.wifi.WifiEnterpriseConfig)
    /// ```
  @JavaMethod
  open func setWpa3EnterpriseStandardModeConfig(_ arg0: WifiEnterpriseConfig?) -> WifiNetworkSuggestion.Builder!

    /// Java method `setIsEnhancedOpen`.
    ///
    /// ### Java method signature
    /// ```java
    /// public android.net.wifi.WifiNetworkSuggestion$Builder android.net.wifi.WifiNetworkSuggestion$Builder.setIsEnhancedOpen(boolean)
    /// ```
  @JavaMethod
  open func setIsEnhancedOpen(_ arg0: Bool) -> WifiNetworkSuggestion.Builder!

    /// Java method `setWpa2Passphrase`.
    ///
    /// ### Java method signature
    /// ```java
    /// public android.net.wifi.WifiNetworkSuggestion$Builder android.net.wifi.WifiNetworkSuggestion$Builder.setWpa2Passphrase(java.lang.String)
    /// ```
  @JavaMethod
  open func setWpa2Passphrase(_ arg0: String) -> WifiNetworkSuggestion.Builder!

    /// Java method `setWpa3Passphrase`.
    ///
    /// ### Java method signature
    /// ```java
    /// public android.net.wifi.WifiNetworkSuggestion$Builder android.net.wifi.WifiNetworkSuggestion$Builder.setWpa3Passphrase(java.lang.String)
    /// ```
  @JavaMethod
  open func setWpa3Passphrase(_ arg0: String) -> WifiNetworkSuggestion.Builder!

    /// Java method `setIsHiddenSsid`.
    ///
    /// ### Java method signature
    /// ```java
    /// public android.net.wifi.WifiNetworkSuggestion$Builder android.net.wifi.WifiNetworkSuggestion$Builder.setIsHiddenSsid(boolean)
    /// ```
  @JavaMethod
  open func setIsHiddenSsid(_ arg0: Bool) -> WifiNetworkSuggestion.Builder!

    /// Java method `setMacRandomizationSetting`.
    ///
    /// ### Java method signature
    /// ```java
    /// public android.net.wifi.WifiNetworkSuggestion$Builder android.net.wifi.WifiNetworkSuggestion$Builder.setMacRandomizationSetting(int)
    /// ```
  @JavaMethod
  open func setMacRandomizationSetting(_ arg0: Int32) -> WifiNetworkSuggestion.Builder!

    /// Java method `setSubscriptionGroup`.
    ///
    /// ### Java method signature
    /// ```java
    /// public android.net.wifi.WifiNetworkSuggestion$Builder android.net.wifi.WifiNetworkSuggestion$Builder.setSubscriptionGroup(android.os.ParcelUuid)
    /// ```
  @JavaMethod
  open func setSubscriptionGroup(_ arg0: ParcelUuid?) -> WifiNetworkSuggestion.Builder!

    /// Java method `setWapiEnterpriseConfig`.
    ///
    /// ### Java method signature
    /// ```java
    /// public android.net.wifi.WifiNetworkSuggestion$Builder android.net.wifi.WifiNetworkSuggestion$Builder.setWapiEnterpriseConfig(android.net.wifi.WifiEnterpriseConfig)
    /// ```
  @JavaMethod
  open func setWapiEnterpriseConfig(_ arg0: WifiEnterpriseConfig?) -> WifiNetworkSuggestion.Builder!

    /// Java method `setIsAppInteractionRequired`.
    ///
    /// ### Java method signature
    /// ```java
    /// public android.net.wifi.WifiNetworkSuggestion$Builder android.net.wifi.WifiNetworkSuggestion$Builder.setIsAppInteractionRequired(boolean)
    /// ```
  @JavaMethod
  open func setIsAppInteractionRequired(_ arg0: Bool) -> WifiNetworkSuggestion.Builder!

    /// Java method `setIsUserInteractionRequired`.
    ///
    /// ### Java method signature
    /// ```java
    /// public android.net.wifi.WifiNetworkSuggestion$Builder android.net.wifi.WifiNetworkSuggestion$Builder.setIsUserInteractionRequired(boolean)
    /// ```
  @JavaMethod
  open func setIsUserInteractionRequired(_ arg0: Bool) -> WifiNetworkSuggestion.Builder!

    /// Java method `setCredentialSharedWithUser`.
    ///
    /// ### Java method signature
    /// ```java
    /// public android.net.wifi.WifiNetworkSuggestion$Builder android.net.wifi.WifiNetworkSuggestion$Builder.setCredentialSharedWithUser(boolean)
    /// ```
  @JavaMethod
  open func setCredentialSharedWithUser(_ arg0: Bool) -> WifiNetworkSuggestion.Builder!

    /// Java method `setIsInitialAutojoinEnabled`.
    ///
    /// ### Java method signature
    /// ```java
    /// public android.net.wifi.WifiNetworkSuggestion$Builder android.net.wifi.WifiNetworkSuggestion$Builder.setIsInitialAutojoinEnabled(boolean)
    /// ```
  @JavaMethod
  open func setIsInitialAutojoinEnabled(_ arg0: Bool) -> WifiNetworkSuggestion.Builder!

    /// Java method `setIsWpa3SaeH2eOnlyModeEnabled`.
    ///
    /// ### Java method signature
    /// ```java
    /// public android.net.wifi.WifiNetworkSuggestion$Builder android.net.wifi.WifiNetworkSuggestion$Builder.setIsWpa3SaeH2eOnlyModeEnabled(boolean)
    /// ```
  @JavaMethod
  open func setIsWpa3SaeH2eOnlyModeEnabled(_ arg0: Bool) -> WifiNetworkSuggestion.Builder!

    /// Java method `setWifiSsid`.
    ///
    /// ### Java method signature
    /// ```java
    /// public android.net.wifi.WifiNetworkSuggestion$Builder android.net.wifi.WifiNetworkSuggestion$Builder.setWifiSsid(android.net.wifi.WifiSsid)
    /// ```
  @JavaMethod
  open func setWifiSsid(_ arg0: WifiSsid?) -> WifiNetworkSuggestion.Builder!

    /// Java method `setPasspointConfig`.
    ///
    /// ### Java method signature
    /// ```java
    /// public android.net.wifi.WifiNetworkSuggestion$Builder android.net.wifi.WifiNetworkSuggestion$Builder.setPasspointConfig(android.net.wifi.hotspot2.PasspointConfiguration)
    /// ```
  @JavaMethod
  open func setPasspointConfig(_ arg0: PasspointConfiguration?) -> WifiNetworkSuggestion.Builder!

    /// Java method `setPriorityGroup`.
    ///
    /// ### Java method signature
    /// ```java
    /// public android.net.wifi.WifiNetworkSuggestion$Builder android.net.wifi.WifiNetworkSuggestion$Builder.setPriorityGroup(int)
    /// ```
  @JavaMethod
  open func setPriorityGroup(_ arg0: Int32) -> WifiNetworkSuggestion.Builder!

    /// Java method `setWapiPassphrase`.
    ///
    /// ### Java method signature
    /// ```java
    /// public android.net.wifi.WifiNetworkSuggestion$Builder android.net.wifi.WifiNetworkSuggestion$Builder.setWapiPassphrase(java.lang.String)
    /// ```
  @JavaMethod
  open func setWapiPassphrase(_ arg0: String) -> WifiNetworkSuggestion.Builder!

    /// Java method `setIsMetered`.
    ///
    /// ### Java method signature
    /// ```java
    /// public android.net.wifi.WifiNetworkSuggestion$Builder android.net.wifi.WifiNetworkSuggestion$Builder.setIsMetered(boolean)
    /// ```
  @JavaMethod
  open func setIsMetered(_ arg0: Bool) -> WifiNetworkSuggestion.Builder!

    /// Java method `setUntrusted`.
    ///
    /// ### Java method signature
    /// ```java
    /// public android.net.wifi.WifiNetworkSuggestion$Builder android.net.wifi.WifiNetworkSuggestion$Builder.setUntrusted(boolean)
    /// ```
  @JavaMethod
  open func setUntrusted(_ arg0: Bool) -> WifiNetworkSuggestion.Builder!

    /// Java method `setRestricted`.
    ///
    /// ### Java method signature
    /// ```java
    /// public android.net.wifi.WifiNetworkSuggestion$Builder android.net.wifi.WifiNetworkSuggestion$Builder.setRestricted(boolean)
    /// ```
  @JavaMethod
  open func setRestricted(_ arg0: Bool) -> WifiNetworkSuggestion.Builder!

    /// Java method `setWifi7Enabled`.
    ///
    /// ### Java method signature
    /// ```java
    /// public android.net.wifi.WifiNetworkSuggestion$Builder android.net.wifi.WifiNetworkSuggestion$Builder.setWifi7Enabled(boolean)
    /// ```
  @JavaMethod
  open func setWifi7Enabled(_ arg0: Bool) -> WifiNetworkSuggestion.Builder!

    /// Java method `setCarrierMerged`.
    ///
    /// ### Java method signature
    /// ```java
    /// public android.net.wifi.WifiNetworkSuggestion$Builder android.net.wifi.WifiNetworkSuggestion$Builder.setCarrierMerged(boolean)
    /// ```
  @JavaMethod
  open func setCarrierMerged(_ arg0: Bool) -> WifiNetworkSuggestion.Builder!

    /// Java method `setPriority`.
    ///
    /// ### Java method signature
    /// ```java
    /// public android.net.wifi.WifiNetworkSuggestion$Builder android.net.wifi.WifiNetworkSuggestion$Builder.setPriority(int)
    /// ```
  @JavaMethod
  open func setPriority(_ arg0: Int32) -> WifiNetworkSuggestion.Builder!

    /// Java method `build`.
    ///
    /// ### Java method signature
    /// ```java
    /// public android.net.wifi.WifiNetworkSuggestion android.net.wifi.WifiNetworkSuggestion$Builder.build()
    /// ```
  @JavaMethod
  open func build() -> WifiNetworkSuggestion!
  }
}
