// Auto-generated by Java-to-Swift wrapper generator.
import AndroidOS
import SwiftJava
import SwiftJavaJNICore

@available(Android 28, *)
@JavaClass("android.net.wifi.rtt.WifiRttManager")
open class WifiRttManager: JavaObject {
  /// Java method `getRttCharacteristics`.
  ///
  /// ### Java method signature
  /// ```java
  /// public android.os.Bundle android.net.wifi.rtt.WifiRttManager.getRttCharacteristics()
  /// ```
@JavaMethod
  open func getRttCharacteristics() -> Bundle!

  /// Java method `isAvailable`.
  ///
  /// ### Java method signature
  /// ```java
  /// public boolean android.net.wifi.rtt.WifiRttManager.isAvailable()
  /// ```
@JavaMethod
  open func isAvailable() -> Bool
}
@available(Android 28, *)
extension JavaClass<WifiRttManager> {
  @JavaStaticField(isFinal: true)
  public var ACTION_WIFI_RTT_STATE_CHANGED: String

  @JavaStaticField(isFinal: true)
  public var CHARACTERISTICS_KEY_BOOLEAN_LCI: String

  @JavaStaticField(isFinal: true)
  public var CHARACTERISTICS_KEY_BOOLEAN_LCR: String

  @JavaStaticField(isFinal: true)
  public var CHARACTERISTICS_KEY_BOOLEAN_NTB_INITIATOR: String

  @JavaStaticField(isFinal: true)
  public var CHARACTERISTICS_KEY_BOOLEAN_ONE_SIDED_RTT: String

  @JavaStaticField(isFinal: true)
  public var CHARACTERISTICS_KEY_BOOLEAN_STA_RESPONDER: String
}
