// Auto-generated by Java-to-Swift wrapper generator.
import AndroidOS
import JavaLangNet
import SwiftJava
import SwiftJavaJNICore

@JavaClass("android.net.wifi.WifiManager")
open class WifiManager: JavaObject {
  /// Java method `addNetworkPrivileged`.
  ///
  /// ### Java method signature
  /// ```java
  /// public android.net.wifi.WifiManager$AddNetworkResult android.net.wifi.WifiManager.addNetworkPrivileged(android.net.wifi.WifiConfiguration)
  /// ```
@JavaMethod
  open func addNetworkPrivileged(_ arg0: WifiConfiguration?) -> WifiManager.AddNetworkResult!

  /// Java method `addOrUpdatePasspointConfiguration`.
  ///
  /// ### Java method signature
  /// ```java
  /// public void android.net.wifi.WifiManager.addOrUpdatePasspointConfiguration(android.net.wifi.hotspot2.PasspointConfiguration)
  /// ```
@JavaMethod
  open func addOrUpdatePasspointConfiguration(_ arg0: PasspointConfiguration?)

  /// Java method `removePasspointConfiguration`.
  ///
  /// ### Java method signature
  /// ```java
  /// public void android.net.wifi.WifiManager.removePasspointConfiguration(java.lang.String)
  /// ```
@available(*, deprecated)
  @JavaMethod
  open func removePasspointConfiguration(_ arg0: String)

  /// Java method `removeNonCallerConfiguredNetworks`.
  ///
  /// ### Java method signature
  /// ```java
  /// public boolean android.net.wifi.WifiManager.removeNonCallerConfiguredNetworks()
  /// ```
@JavaMethod
  open func removeNonCallerConfiguredNetworks() -> Bool

  /// Java method `isStaApConcurrencySupported`.
  ///
  /// ### Java method signature
  /// ```java
  /// public boolean android.net.wifi.WifiManager.isStaApConcurrencySupported()
  /// ```
@JavaMethod
  open func isStaApConcurrencySupported() -> Bool

  /// Java method `isDeviceToApRttSupported`.
  ///
  /// ### Java method signature
  /// ```java
  /// public boolean android.net.wifi.WifiManager.isDeviceToApRttSupported()
  /// ```
@available(*, deprecated)
  @JavaMethod
  open func isDeviceToApRttSupported() -> Bool

  /// Java method `isPreferredNetworkOffloadSupported`.
  ///
  /// ### Java method signature
  /// ```java
  /// public boolean android.net.wifi.WifiManager.isPreferredNetworkOffloadSupported()
  /// ```
@JavaMethod
  open func isPreferredNetworkOffloadSupported() -> Bool

  /// Java method `isEnhancedPowerReportingSupported`.
  ///
  /// ### Java method signature
  /// ```java
  /// public boolean android.net.wifi.WifiManager.isEnhancedPowerReportingSupported()
  /// ```
@JavaMethod
  open func isEnhancedPowerReportingSupported() -> Bool

  /// Java method `is24GHzBandSupported`.
  ///
  /// ### Java method signature
  /// ```java
  /// public boolean android.net.wifi.WifiManager.is24GHzBandSupported()
  /// ```
@JavaMethod
  open func is24GHzBandSupported() -> Bool

  /// Java method `is5GHzBandSupported`.
  ///
  /// ### Java method signature
  /// ```java
  /// public boolean android.net.wifi.WifiManager.is5GHzBandSupported()
  /// ```
@JavaMethod
  open func is5GHzBandSupported() -> Bool

  /// Java method `is60GHzBandSupported`.
  ///
  /// ### Java method signature
  /// ```java
  /// public boolean android.net.wifi.WifiManager.is60GHzBandSupported()
  /// ```
@JavaMethod
  open func is60GHzBandSupported() -> Bool

  /// Java method `is6GHzBandSupported`.
  ///
  /// ### Java method signature
  /// ```java
  /// public boolean android.net.wifi.WifiManager.is6GHzBandSupported()
  /// ```
@JavaMethod
  open func is6GHzBandSupported() -> Bool

  /// Java method `isWifiStandardSupported`.
  ///
  /// ### Java method signature
  /// ```java
  /// public boolean android.net.wifi.WifiManager.isWifiStandardSupported(int)
  /// ```
@JavaMethod
  open func isWifiStandardSupported(_ arg0: Int32) -> Bool

  /// Java method `isStaBridgedApConcurrencySupported`.
  ///
  /// ### Java method signature
  /// ```java
  /// public boolean android.net.wifi.WifiManager.isStaBridgedApConcurrencySupported()
  /// ```
@JavaMethod
  open func isStaBridgedApConcurrencySupported() -> Bool

  /// Java method `isBridgedApConcurrencySupported`.
  ///
  /// ### Java method signature
  /// ```java
  /// public boolean android.net.wifi.WifiManager.isBridgedApConcurrencySupported()
  /// ```
@JavaMethod
  open func isBridgedApConcurrencySupported() -> Bool

  /// Java method `isD2dSupportedWhenInfraStaDisabled`.
  ///
  /// ### Java method signature
  /// ```java
  /// public boolean android.net.wifi.WifiManager.isD2dSupportedWhenInfraStaDisabled()
  /// ```
@JavaMethod
  open func isD2dSupportedWhenInfraStaDisabled() -> Bool

  /// Java method `isScanAlwaysAvailable`.
  ///
  /// ### Java method signature
  /// ```java
  /// public boolean android.net.wifi.WifiManager.isScanAlwaysAvailable()
  /// ```
@available(*, deprecated)
  @JavaMethod
  open func isScanAlwaysAvailable() -> Bool

  /// Java method `calculateSignalLevel`.
  ///
  /// ### Java method signature
  /// ```java
  /// public int android.net.wifi.WifiManager.calculateSignalLevel(int)
  /// ```
@JavaMethod
  open func calculateSignalLevel(_ arg0: Int32) -> Int32

  /// Java method `validateSoftApConfiguration`.
  ///
  /// ### Java method signature
  /// ```java
  /// public boolean android.net.wifi.WifiManager.validateSoftApConfiguration(android.net.wifi.SoftApConfiguration)
  /// ```
@JavaMethod
  open func validateSoftApConfiguration(_ arg0: SoftApConfiguration?) -> Bool

  /// Java method `startLocalOnlyHotspot`.
  ///
  /// ### Java method signature
  /// ```java
  /// public void android.net.wifi.WifiManager.startLocalOnlyHotspot(android.net.wifi.WifiManager$LocalOnlyHotspotCallback,android.os.Handler)
  /// ```
@JavaMethod
  open func startLocalOnlyHotspot(_ arg0: WifiManager.LocalOnlyHotspotCallback?, _ arg1: Handler?)

  /// Java method `setTdlsEnabledWithMacAddress`.
  ///
  /// ### Java method signature
  /// ```java
  /// public void android.net.wifi.WifiManager.setTdlsEnabledWithMacAddress(java.lang.String,boolean)
  /// ```
@JavaMethod
  open func setTdlsEnabledWithMacAddress(_ arg0: String, _ arg1: Bool)

  /// Java method `allowAutojoinGlobal`.
  ///
  /// ### Java method signature
  /// ```java
  /// public void android.net.wifi.WifiManager.allowAutojoinGlobal(boolean)
  /// ```
@JavaMethod
  open func allowAutojoinGlobal(_ arg0: Bool)

  /// Java method `createMulticastLock`.
  ///
  /// ### Java method signature
  /// ```java
  /// public android.net.wifi.WifiManager$MulticastLock android.net.wifi.WifiManager.createMulticastLock(java.lang.String)
  /// ```
@JavaMethod
  open func createMulticastLock(_ arg0: String) -> WifiManager.MulticastLock!

  /// Java method `isWpa3SuiteBSupported`.
  ///
  /// ### Java method signature
  /// ```java
  /// public boolean android.net.wifi.WifiManager.isWpa3SuiteBSupported()
  /// ```
@JavaMethod
  open func isWpa3SuiteBSupported() -> Bool

  /// Java method `isEnhancedOpenSupported`.
  ///
  /// ### Java method signature
  /// ```java
  /// public boolean android.net.wifi.WifiManager.isEnhancedOpenSupported()
  /// ```
@JavaMethod
  open func isEnhancedOpenSupported() -> Bool

  /// Java method `isEasyConnectSupported`.
  ///
  /// ### Java method signature
  /// ```java
  /// public boolean android.net.wifi.WifiManager.isEasyConnectSupported()
  /// ```
@JavaMethod
  open func isEasyConnectSupported() -> Bool

  /// Java method `isWpa3SaePublicKeySupported`.
  ///
  /// ### Java method signature
  /// ```java
  /// public boolean android.net.wifi.WifiManager.isWpa3SaePublicKeySupported()
  /// ```
@JavaMethod
  open func isWpa3SaePublicKeySupported() -> Bool

  /// Java method `isWpa3SaeH2eSupported`.
  ///
  /// ### Java method signature
  /// ```java
  /// public boolean android.net.wifi.WifiManager.isWpa3SaeH2eSupported()
  /// ```
@JavaMethod
  open func isWpa3SaeH2eSupported() -> Bool

  /// Java method `isWifiDisplayR2Supported`.
  ///
  /// ### Java method signature
  /// ```java
  /// public boolean android.net.wifi.WifiManager.isWifiDisplayR2Supported()
  /// ```
@JavaMethod
  open func isWifiDisplayR2Supported() -> Bool

  /// Java method `isDecoratedIdentitySupported`.
  ///
  /// ### Java method signature
  /// ```java
  /// public boolean android.net.wifi.WifiManager.isDecoratedIdentitySupported()
  /// ```
@JavaMethod
  open func isDecoratedIdentitySupported() -> Bool

  /// Java method `isTrustOnFirstUseSupported`.
  ///
  /// ### Java method signature
  /// ```java
  /// public boolean android.net.wifi.WifiManager.isTrustOnFirstUseSupported()
  /// ```
@JavaMethod
  open func isTrustOnFirstUseSupported() -> Bool

  /// Java method `isEasyConnectDppAkmSupported`.
  ///
  /// ### Java method signature
  /// ```java
  /// public boolean android.net.wifi.WifiManager.isEasyConnectDppAkmSupported()
  /// ```
@JavaMethod
  open func isEasyConnectDppAkmSupported() -> Bool

  /// Java method `isTlsMinimumVersionSupported`.
  ///
  /// ### Java method signature
  /// ```java
  /// public boolean android.net.wifi.WifiManager.isTlsMinimumVersionSupported()
  /// ```
@JavaMethod
  open func isTlsMinimumVersionSupported() -> Bool

  /// Java method `isDualBandSimultaneousSupported`.
  ///
  /// ### Java method signature
  /// ```java
  /// public boolean android.net.wifi.WifiManager.isDualBandSimultaneousSupported()
  /// ```
@JavaMethod
  open func isDualBandSimultaneousSupported() -> Bool

  /// Java method `isWpaPersonalSupported`.
  ///
  /// ### Java method signature
  /// ```java
  /// public boolean android.net.wifi.WifiManager.isWpaPersonalSupported()
  /// ```
@JavaMethod
  open func isWpaPersonalSupported() -> Bool

  /// Java method `unregisterScanResultsCallback`.
  ///
  /// ### Java method signature
  /// ```java
  /// public void android.net.wifi.WifiManager.unregisterScanResultsCallback(android.net.wifi.WifiManager$ScanResultsCallback)
  /// ```
@JavaMethod
  open func unregisterScanResultsCallback(_ arg0: WifiManager.ScanResultsCallback?)

  /// Java method `isScanThrottleEnabled`.
  ///
  /// ### Java method signature
  /// ```java
  /// public boolean android.net.wifi.WifiManager.isScanThrottleEnabled()
  /// ```
@JavaMethod
  open func isScanThrottleEnabled() -> Bool

  /// Java method `isAutoWakeupEnabled`.
  ///
  /// ### Java method signature
  /// ```java
  /// public boolean android.net.wifi.WifiManager.isAutoWakeupEnabled()
  /// ```
@JavaMethod
  open func isAutoWakeupEnabled() -> Bool

  /// Java method `isCarrierNetworkOffloadEnabled`.
  ///
  /// ### Java method signature
  /// ```java
  /// public boolean android.net.wifi.WifiManager.isCarrierNetworkOffloadEnabled(int,boolean)
  /// ```
@JavaMethod
  open func isCarrierNetworkOffloadEnabled(_ arg0: Int32, _ arg1: Bool) -> Bool

  /// Java method `flushPasspointAnqpCache`.
  ///
  /// ### Java method signature
  /// ```java
  /// public void android.net.wifi.WifiManager.flushPasspointAnqpCache()
  /// ```
@JavaMethod
  open func flushPasspointAnqpCache()

  /// Java method `isWifiPasspointEnabled`.
  ///
  /// ### Java method signature
  /// ```java
  /// public boolean android.net.wifi.WifiManager.isWifiPasspointEnabled()
  /// ```
@JavaMethod
  open func isWifiPasspointEnabled() -> Bool

  /// Java method `setSendDhcpHostnameRestriction`.
  ///
  /// ### Java method signature
  /// ```java
  /// public void android.net.wifi.WifiManager.setSendDhcpHostnameRestriction(int)
  /// ```
@JavaMethod
  open func setSendDhcpHostnameRestriction(_ arg0: Int32)

  /// Java method `isAggressiveRoamingModeSupported`.
  ///
  /// ### Java method signature
  /// ```java
  /// public boolean android.net.wifi.WifiManager.isAggressiveRoamingModeSupported()
  /// ```
@JavaMethod
  open func isAggressiveRoamingModeSupported() -> Bool

  /// Java method `setPerSsidRoamingMode`.
  ///
  /// ### Java method signature
  /// ```java
  /// public void android.net.wifi.WifiManager.setPerSsidRoamingMode(android.net.wifi.WifiSsid,int)
  /// ```
@JavaMethod
  open func setPerSsidRoamingMode(_ arg0: WifiSsid?, _ arg1: Int32)

  /// Java method `removePerSsidRoamingMode`.
  ///
  /// ### Java method signature
  /// ```java
  /// public void android.net.wifi.WifiManager.removePerSsidRoamingMode(android.net.wifi.WifiSsid)
  /// ```
@JavaMethod
  open func removePerSsidRoamingMode(_ arg0: WifiSsid?)

  /// Java method `addNetwork`.
  ///
  /// ### Java method signature
  /// ```java
  /// public int android.net.wifi.WifiManager.addNetwork(android.net.wifi.WifiConfiguration)
  /// ```
@available(*, deprecated)
  @JavaMethod
  open func addNetwork(_ arg0: WifiConfiguration?) -> Int32

  /// Java method `updateNetwork`.
  ///
  /// ### Java method signature
  /// ```java
  /// public int android.net.wifi.WifiManager.updateNetwork(android.net.wifi.WifiConfiguration)
  /// ```
@available(*, deprecated)
  @JavaMethod
  open func updateNetwork(_ arg0: WifiConfiguration?) -> Int32

  /// Java method `removeNetwork`.
  ///
  /// ### Java method signature
  /// ```java
  /// public boolean android.net.wifi.WifiManager.removeNetwork(int)
  /// ```
@available(*, deprecated)
  @JavaMethod
  open func removeNetwork(_ arg0: Int32) -> Bool

  /// Java method `enableNetwork`.
  ///
  /// ### Java method signature
  /// ```java
  /// public boolean android.net.wifi.WifiManager.enableNetwork(int,boolean)
  /// ```
@available(*, deprecated)
  @JavaMethod
  open func enableNetwork(_ arg0: Int32, _ arg1: Bool) -> Bool

  /// Java method `disableNetwork`.
  ///
  /// ### Java method signature
  /// ```java
  /// public boolean android.net.wifi.WifiManager.disableNetwork(int)
  /// ```
@available(*, deprecated)
  @JavaMethod
  open func disableNetwork(_ arg0: Int32) -> Bool

  /// Java method `disconnect`.
  ///
  /// ### Java method signature
  /// ```java
  /// public boolean android.net.wifi.WifiManager.disconnect()
  /// ```
@available(*, deprecated)
  @JavaMethod
  open func disconnect() -> Bool

  /// Java method `reconnect`.
  ///
  /// ### Java method signature
  /// ```java
  /// public boolean android.net.wifi.WifiManager.reconnect()
  /// ```
@available(*, deprecated)
  @JavaMethod
  open func reconnect() -> Bool

  /// Java method `reassociate`.
  ///
  /// ### Java method signature
  /// ```java
  /// public boolean android.net.wifi.WifiManager.reassociate()
  /// ```
@available(*, deprecated)
  @JavaMethod
  open func reassociate() -> Bool

  /// Java method `pingSupplicant`.
  ///
  /// ### Java method signature
  /// ```java
  /// public boolean android.net.wifi.WifiManager.pingSupplicant()
  /// ```
@available(*, deprecated)
  @JavaMethod
  open func pingSupplicant() -> Bool

  /// Java method `isP2pSupported`.
  ///
  /// ### Java method signature
  /// ```java
  /// public boolean android.net.wifi.WifiManager.isP2pSupported()
  /// ```
@JavaMethod
  open func isP2pSupported() -> Bool

  /// Java method `isTdlsSupported`.
  ///
  /// ### Java method signature
  /// ```java
  /// public boolean android.net.wifi.WifiManager.isTdlsSupported()
  /// ```
@JavaMethod
  open func isTdlsSupported() -> Bool

  /// Java method `startScan`.
  ///
  /// ### Java method signature
  /// ```java
  /// public boolean android.net.wifi.WifiManager.startScan()
  /// ```
@available(*, deprecated)
  @JavaMethod
  open func startScan() -> Bool

  /// Java method `getConnectionInfo`.
  ///
  /// ### Java method signature
  /// ```java
  /// public android.net.wifi.WifiInfo android.net.wifi.WifiManager.getConnectionInfo()
  /// ```
@available(*, deprecated)
  @JavaMethod
  open func getConnectionInfo() -> WifiInfo!

  /// Java method `saveConfiguration`.
  ///
  /// ### Java method signature
  /// ```java
  /// public boolean android.net.wifi.WifiManager.saveConfiguration()
  /// ```
@available(*, deprecated)
  @JavaMethod
  open func saveConfiguration() -> Bool

  /// Java method `getDhcpInfo`.
  ///
  /// ### Java method signature
  /// ```java
  /// public android.net.DhcpInfo android.net.wifi.WifiManager.getDhcpInfo()
  /// ```
@available(*, deprecated)
  @JavaMethod
  open func getDhcpInfo() -> DhcpInfo!

  /// Java method `setWifiEnabled`.
  ///
  /// ### Java method signature
  /// ```java
  /// public boolean android.net.wifi.WifiManager.setWifiEnabled(boolean)
  /// ```
@available(*, deprecated)
  @JavaMethod
  open func setWifiEnabled(_ arg0: Bool) -> Bool

  /// Java method `getWifiState`.
  ///
  /// ### Java method signature
  /// ```java
  /// public int android.net.wifi.WifiManager.getWifiState()
  /// ```
@JavaMethod
  open func getWifiState() -> Int32

  /// Java method `isWifiEnabled`.
  ///
  /// ### Java method signature
  /// ```java
  /// public boolean android.net.wifi.WifiManager.isWifiEnabled()
  /// ```
@JavaMethod
  open func isWifiEnabled() -> Bool

  /// Java method `getMaxSignalLevel`.
  ///
  /// ### Java method signature
  /// ```java
  /// public int android.net.wifi.WifiManager.getMaxSignalLevel()
  /// ```
@JavaMethod
  open func getMaxSignalLevel() -> Int32

  /// Java method `setTdlsEnabled`.
  ///
  /// ### Java method signature
  /// ```java
  /// public void android.net.wifi.WifiManager.setTdlsEnabled(java.net.InetAddress,boolean)
  /// ```
@JavaMethod
  open func setTdlsEnabled(_ arg0: InetAddress?, _ arg1: Bool)

  /// Java method `startWps`.
  ///
  /// ### Java method signature
  /// ```java
  /// public void android.net.wifi.WifiManager.startWps(android.net.wifi.WpsInfo,android.net.wifi.WifiManager$WpsCallback)
  /// ```
@available(*, deprecated)
  @JavaMethod
  open func startWps(_ arg0: WpsInfo?, _ arg1: WifiManager.WpsCallback?)

  /// Java method `cancelWps`.
  ///
  /// ### Java method signature
  /// ```java
  /// public void android.net.wifi.WifiManager.cancelWps(android.net.wifi.WifiManager$WpsCallback)
  /// ```
@available(*, deprecated)
  @JavaMethod
  open func cancelWps(_ arg0: WifiManager.WpsCallback?)

  /// Java method `createWifiLock`.
  ///
  /// ### Java method signature
  /// ```java
  /// public android.net.wifi.WifiManager$WifiLock android.net.wifi.WifiManager.createWifiLock(int,java.lang.String)
  /// ```
@JavaMethod
  open func createWifiLock(_ arg0: Int32, _ arg1: String) -> WifiManager.WifiLock!

  /// Java method `createWifiLock`.
  ///
  /// ### Java method signature
  /// ```java
  /// public android.net.wifi.WifiManager$WifiLock android.net.wifi.WifiManager.createWifiLock(java.lang.String)
  /// ```
@available(*, deprecated)
  @JavaMethod
  open func createWifiLock(_ arg0: String) -> WifiManager.WifiLock!

  /// Java method `isWpa3SaeSupported`.
  ///
  /// ### Java method signature
  /// ```java
  /// public boolean android.net.wifi.WifiManager.isWpa3SaeSupported()
  /// ```
@JavaMethod
  open func isWpa3SaeSupported() -> Bool

  /// Java method `isWapiSupported`.
  ///
  /// ### Java method signature
  /// ```java
  /// public boolean android.net.wifi.WifiManager.isWapiSupported()
  /// ```
@JavaMethod
  open func isWapiSupported() -> Bool

  /// Java method `isTlsV13Supported`.
  ///
  /// ### Java method signature
  /// ```java
  /// public boolean android.net.wifi.WifiManager.isTlsV13Supported()
  /// ```
@JavaMethod
  open func isTlsV13Supported() -> Bool

  /// Java method `isWepSupported`.
  ///
  /// ### Java method signature
  /// ```java
  /// public boolean android.net.wifi.WifiManager.isWepSupported()
  /// ```
@JavaMethod
  open func isWepSupported() -> Bool

  /// Java method `getMaxNumberOfNetworkSuggestionsPerApp`.
  ///
  /// ### Java method signature
  /// ```java
  /// public int android.net.wifi.WifiManager.getMaxNumberOfNetworkSuggestionsPerApp()
  /// ```
@JavaMethod
  open func getMaxNumberOfNetworkSuggestionsPerApp() -> Int32

  /// Java method `isStaConcurrencyForLocalOnlyConnectionsSupported`.
  ///
  /// ### Java method signature
  /// ```java
  /// public boolean android.net.wifi.WifiManager.isStaConcurrencyForLocalOnlyConnectionsSupported()
  /// ```
@JavaMethod
  open func isStaConcurrencyForLocalOnlyConnectionsSupported() -> Bool

  /// Java method `isMakeBeforeBreakWifiSwitchingSupported`.
  ///
  /// ### Java method signature
  /// ```java
  /// public boolean android.net.wifi.WifiManager.isMakeBeforeBreakWifiSwitchingSupported()
  /// ```
@JavaMethod
  open func isMakeBeforeBreakWifiSwitchingSupported() -> Bool

  /// Java method `isStaConcurrencyForMultiInternetSupported`.
  ///
  /// ### Java method signature
  /// ```java
  /// public boolean android.net.wifi.WifiManager.isStaConcurrencyForMultiInternetSupported()
  /// ```
@JavaMethod
  open func isStaConcurrencyForMultiInternetSupported() -> Bool

  /// Java method `unregisterSubsystemRestartTrackingCallback`.
  ///
  /// ### Java method signature
  /// ```java
  /// public void android.net.wifi.WifiManager.unregisterSubsystemRestartTrackingCallback(android.net.wifi.WifiManager$SubsystemRestartTrackingCallback)
  /// ```
@JavaMethod
  open func unregisterSubsystemRestartTrackingCallback(_ arg0: WifiManager.SubsystemRestartTrackingCallback?)

  /// Java method `isEasyConnectEnrolleeResponderModeSupported`.
  ///
  /// ### Java method signature
  /// ```java
  /// public boolean android.net.wifi.WifiManager.isEasyConnectEnrolleeResponderModeSupported()
  /// ```
@JavaMethod
  open func isEasyConnectEnrolleeResponderModeSupported() -> Bool

  /// Java method `isPasspointTermsAndConditionsSupported`.
  ///
  /// ### Java method signature
  /// ```java
  /// public boolean android.net.wifi.WifiManager.isPasspointTermsAndConditionsSupported()
  /// ```
@JavaMethod
  open func isPasspointTermsAndConditionsSupported() -> Bool

  /// Java method `isTidToLinkMappingNegotiationSupported`.
  ///
  /// ### Java method signature
  /// ```java
  /// public boolean android.net.wifi.WifiManager.isTidToLinkMappingNegotiationSupported()
  /// ```
@JavaMethod
  open func isTidToLinkMappingNegotiationSupported() -> Bool

  /// Java method `removeSuggestionConnectionStatusListener`.
  ///
  /// ### Java method signature
  /// ```java
  /// public void android.net.wifi.WifiManager.removeSuggestionConnectionStatusListener(android.net.wifi.WifiManager$SuggestionConnectionStatusListener)
  /// ```
@JavaMethod
  open func removeSuggestionConnectionStatusListener(_ arg0: WifiManager.SuggestionConnectionStatusListener?)

  /// Java method `removeLocalOnlyConnectionFailureListener`.
  ///
  /// ### Java method signature
  /// ```java
  /// public void android.net.wifi.WifiManager.removeLocalOnlyConnectionFailureListener(android.net.wifi.WifiManager$LocalOnlyConnectionFailureListener)
  /// ```
@JavaMethod
  open func removeLocalOnlyConnectionFailureListener(_ arg0: WifiManager.LocalOnlyConnectionFailureListener?)

  /// Java method `removeSuggestionUserApprovalStatusListener`.
  ///
  /// ### Java method signature
  /// ```java
  /// public void android.net.wifi.WifiManager.removeSuggestionUserApprovalStatusListener(android.net.wifi.WifiManager$SuggestionUserApprovalStatusListener)
  /// ```
@JavaMethod
  open func removeSuggestionUserApprovalStatusListener(_ arg0: WifiManager.SuggestionUserApprovalStatusListener?)

  /// Java method `getStaConcurrencyForMultiInternetMode`.
  ///
  /// ### Java method signature
  /// ```java
  /// public int android.net.wifi.WifiManager.getStaConcurrencyForMultiInternetMode()
  /// ```
@JavaMethod
  open func getStaConcurrencyForMultiInternetMode() -> Int32

  /// Java method `getMaxNumberOfChannelsPerNetworkSpecifierRequest`.
  ///
  /// ### Java method signature
  /// ```java
  /// public int android.net.wifi.WifiManager.getMaxNumberOfChannelsPerNetworkSpecifierRequest()
  /// ```
@JavaMethod
  open func getMaxNumberOfChannelsPerNetworkSpecifierRequest() -> Int32
}
extension WifiManager {
  @JavaInterface("android.net.wifi.WifiManager$LocalOnlyConnectionFailureListener")
  public struct LocalOnlyConnectionFailureListener {
    /// Java method `onConnectionFailed`.
    ///
    /// ### Java method signature
    /// ```java
    /// public abstract void android.net.wifi.WifiManager$LocalOnlyConnectionFailureListener.onConnectionFailed(android.net.wifi.WifiNetworkSpecifier,int)
    /// ```
  @JavaMethod
  public func onConnectionFailed(_ arg0: WifiNetworkSpecifier?, _ arg1: Int32)
  }
}
extension JavaClass<WifiManager> {
  @JavaStaticField(isFinal: true)
  public var ACTION_PICK_WIFI_NETWORK: String

  @JavaStaticField(isFinal: true)
  public var ACTION_REMOVE_SUGGESTION_DISCONNECT: Int32

  @JavaStaticField(isFinal: true)
  public var ACTION_REMOVE_SUGGESTION_LINGER: Int32

  @JavaStaticField(isFinal: true)
  public var ACTION_REQUEST_SCAN_ALWAYS_AVAILABLE: String

  @JavaStaticField(isFinal: true)
  public var ACTION_WIFI_NETWORK_SUGGESTION_POST_CONNECTION: String

  @JavaStaticField(isFinal: true)
  public var ACTION_WIFI_SCAN_AVAILABILITY_CHANGED: String

  @JavaStaticField(isFinal: true)
  public var CHANNEL_DATA_KEY_FREQUENCY_MHZ: String

  @JavaStaticField(isFinal: true)
  public var CHANNEL_DATA_KEY_NUM_AP: String

  @available(*, deprecated)
  @JavaStaticField(isFinal: true)
  public var ERROR_AUTHENTICATING: Int32

  @available(*, deprecated)
  @JavaStaticField(isFinal: true)
  public var EXTRA_BSSID: String

  @JavaStaticField(isFinal: true)
  public var EXTRA_NETWORK_INFO: String

  @JavaStaticField(isFinal: true)
  public var EXTRA_NETWORK_SUGGESTION: String

  @JavaStaticField(isFinal: true)
  public var EXTRA_NEW_RSSI: String

  @available(*, deprecated)
  @JavaStaticField(isFinal: true)
  public var EXTRA_NEW_STATE: String

  @JavaStaticField(isFinal: true)
  public var EXTRA_PREVIOUS_WIFI_STATE: String

  @JavaStaticField(isFinal: true)
  public var EXTRA_RESULTS_UPDATED: String

  @JavaStaticField(isFinal: true)
  public var EXTRA_SCAN_AVAILABLE: String

  @available(*, deprecated)
  @JavaStaticField(isFinal: true)
  public var EXTRA_SUPPLICANT_CONNECTED: String

  @available(*, deprecated)
  @JavaStaticField(isFinal: true)
  public var EXTRA_SUPPLICANT_ERROR: String

  @available(*, deprecated)
  @JavaStaticField(isFinal: true)
  public var EXTRA_WIFI_INFO: String

  @JavaStaticField(isFinal: true)
  public var EXTRA_WIFI_STATE: String

  @JavaStaticField(isFinal: true)
  public var FLAG_SEND_DHCP_HOSTNAME_RESTRICTION_OPEN: Int32

  @JavaStaticField(isFinal: true)
  public var FLAG_SEND_DHCP_HOSTNAME_RESTRICTION_SECURE: Int32

  @JavaStaticField(isFinal: true)
  public var NETWORK_IDS_CHANGED_ACTION: String

  @JavaStaticField(isFinal: true)
  public var NETWORK_STATE_CHANGED_ACTION: String

  @JavaStaticField(isFinal: true)
  public var ROAMING_MODE_AGGRESSIVE: Int32

  @JavaStaticField(isFinal: true)
  public var ROAMING_MODE_NONE: Int32

  @JavaStaticField(isFinal: true)
  public var ROAMING_MODE_NORMAL: Int32

  @JavaStaticField(isFinal: true)
  public var RSSI_CHANGED_ACTION: String

  @JavaStaticField(isFinal: true)
  public var SCAN_RESULTS_AVAILABLE_ACTION: String

  @JavaStaticField(isFinal: true)
  public var STATUS_LOCAL_ONLY_CONNECTION_FAILURE_ASSOCIATION: Int32

  @JavaStaticField(isFinal: true)
  public var STATUS_LOCAL_ONLY_CONNECTION_FAILURE_AUTHENTICATION: Int32

  @JavaStaticField(isFinal: true)
  public var STATUS_LOCAL_ONLY_CONNECTION_FAILURE_IP_PROVISIONING: Int32

  @JavaStaticField(isFinal: true)
  public var STATUS_LOCAL_ONLY_CONNECTION_FAILURE_NOT_FOUND: Int32

  @JavaStaticField(isFinal: true)
  public var STATUS_LOCAL_ONLY_CONNECTION_FAILURE_NO_RESPONSE: Int32

  @JavaStaticField(isFinal: true)
  public var STATUS_LOCAL_ONLY_CONNECTION_FAILURE_UNKNOWN: Int32

  @JavaStaticField(isFinal: true)
  public var STATUS_NETWORK_SUGGESTIONS_ERROR_ADD_DUPLICATE: Int32

  @JavaStaticField(isFinal: true)
  public var STATUS_NETWORK_SUGGESTIONS_ERROR_ADD_EXCEEDS_MAX_PER_APP: Int32

  @JavaStaticField(isFinal: true)
  public var STATUS_NETWORK_SUGGESTIONS_ERROR_ADD_INVALID: Int32

  @JavaStaticField(isFinal: true)
  public var STATUS_NETWORK_SUGGESTIONS_ERROR_ADD_NOT_ALLOWED: Int32

  @JavaStaticField(isFinal: true)
  public var STATUS_NETWORK_SUGGESTIONS_ERROR_APP_DISALLOWED: Int32

  @JavaStaticField(isFinal: true)
  public var STATUS_NETWORK_SUGGESTIONS_ERROR_INTERNAL: Int32

  @JavaStaticField(isFinal: true)
  public var STATUS_NETWORK_SUGGESTIONS_ERROR_REMOVE_INVALID: Int32

  @JavaStaticField(isFinal: true)
  public var STATUS_NETWORK_SUGGESTIONS_ERROR_RESTRICTED_BY_ADMIN: Int32

  @JavaStaticField(isFinal: true)
  public var STATUS_NETWORK_SUGGESTIONS_SUCCESS: Int32

  @JavaStaticField(isFinal: true)
  public var STATUS_SUGGESTION_APPROVAL_APPROVED_BY_CARRIER_PRIVILEGE: Int32

  @JavaStaticField(isFinal: true)
  public var STATUS_SUGGESTION_APPROVAL_APPROVED_BY_USER: Int32

  @JavaStaticField(isFinal: true)
  public var STATUS_SUGGESTION_APPROVAL_PENDING: Int32

  @JavaStaticField(isFinal: true)
  public var STATUS_SUGGESTION_APPROVAL_REJECTED_BY_USER: Int32

  @JavaStaticField(isFinal: true)
  public var STATUS_SUGGESTION_APPROVAL_UNKNOWN: Int32

  @JavaStaticField(isFinal: true)
  public var STATUS_SUGGESTION_CONNECTION_FAILURE_ASSOCIATION: Int32

  @JavaStaticField(isFinal: true)
  public var STATUS_SUGGESTION_CONNECTION_FAILURE_AUTHENTICATION: Int32

  @JavaStaticField(isFinal: true)
  public var STATUS_SUGGESTION_CONNECTION_FAILURE_IP_PROVISIONING: Int32

  @JavaStaticField(isFinal: true)
  public var STATUS_SUGGESTION_CONNECTION_FAILURE_UNKNOWN: Int32

  @available(*, deprecated)
  @JavaStaticField(isFinal: true)
  public var SUPPLICANT_CONNECTION_CHANGE_ACTION: String

  @available(*, deprecated)
  @JavaStaticField(isFinal: true)
  public var SUPPLICANT_STATE_CHANGED_ACTION: String

  @JavaStaticField(isFinal: true)
  public var UNKNOWN_SSID: String

  @JavaStaticField(isFinal: true)
  public var WIFI_INTERFACE_TYPE_AP: Int32

  @JavaStaticField(isFinal: true)
  public var WIFI_INTERFACE_TYPE_AWARE: Int32

  @JavaStaticField(isFinal: true)
  public var WIFI_INTERFACE_TYPE_DIRECT: Int32

  @JavaStaticField(isFinal: true)
  public var WIFI_INTERFACE_TYPE_STA: Int32

  @available(*, deprecated)
  @JavaStaticField(isFinal: true)
  public var WIFI_MODE_FULL: Int32

  @available(*, deprecated)
  @JavaStaticField(isFinal: true)
  public var WIFI_MODE_FULL_HIGH_PERF: Int32

  @JavaStaticField(isFinal: true)
  public var WIFI_MODE_FULL_LOW_LATENCY: Int32

  @available(*, deprecated)
  @JavaStaticField(isFinal: true)
  public var WIFI_MODE_SCAN_ONLY: Int32

  @JavaStaticField(isFinal: true)
  public var WIFI_MULTI_INTERNET_MODE_DBS_AP: Int32

  @JavaStaticField(isFinal: true)
  public var WIFI_MULTI_INTERNET_MODE_DISABLED: Int32

  @JavaStaticField(isFinal: true)
  public var WIFI_MULTI_INTERNET_MODE_MULTI_AP: Int32

  @JavaStaticField(isFinal: true)
  public var WIFI_STATE_CHANGED_ACTION: String

  @JavaStaticField(isFinal: true)
  public var WIFI_STATE_DISABLED: Int32

  @JavaStaticField(isFinal: true)
  public var WIFI_STATE_DISABLING: Int32

  @JavaStaticField(isFinal: true)
  public var WIFI_STATE_ENABLED: Int32

  @JavaStaticField(isFinal: true)
  public var WIFI_STATE_ENABLING: Int32

  @JavaStaticField(isFinal: true)
  public var WIFI_STATE_UNKNOWN: Int32

  @available(*, deprecated)
  @JavaStaticField(isFinal: true)
  public var WPS_AUTH_FAILURE: Int32

  @available(*, deprecated)
  @JavaStaticField(isFinal: true)
  public var WPS_OVERLAP_ERROR: Int32

  @available(*, deprecated)
  @JavaStaticField(isFinal: true)
  public var WPS_TIMED_OUT: Int32

  @available(*, deprecated)
  @JavaStaticField(isFinal: true)
  public var WPS_TKIP_ONLY_PROHIBITED: Int32

  @available(*, deprecated)
  @JavaStaticField(isFinal: true)
  public var WPS_WEP_PROHIBITED: Int32

    /// Java method `calculateSignalLevel`.
    ///
    /// ### Java method signature
    /// ```java
    /// public static int android.net.wifi.WifiManager.calculateSignalLevel(int,int)
    /// ```
  @available(*, deprecated)
  @JavaStaticMethod
  public func calculateSignalLevel(_ arg0: Int32, _ arg1: Int32) -> Int32

    /// Java method `compareSignalLevel`.
    ///
    /// ### Java method signature
    /// ```java
    /// public static int android.net.wifi.WifiManager.compareSignalLevel(int,int)
    /// ```
  @JavaStaticMethod
  public func compareSignalLevel(_ arg0: Int32, _ arg1: Int32) -> Int32
}
