// Auto-generated by Java-to-Swift wrapper generator.
import AndroidOS
import SwiftJava
import SwiftJavaJNICore

extension WifiManager {
  @JavaClass("android.net.wifi.WifiManager$AddNetworkResult", implements: Parcelable.self)
  open class AddNetworkResult: JavaObject {
  @JavaField(isFinal: true)
  public var networkId: Int32

  @JavaField(isFinal: true)
  public var statusCode: Int32

  @JavaMethod
  @_nonoverride public convenience init(_ arg0: Int32, _ arg1: Int32, environment: JNIEnvironment? = nil)

    /// Java method `describeContents`.
    ///
    /// ### Java method signature
    /// ```java
    /// public int android.net.wifi.WifiManager$AddNetworkResult.describeContents()
    /// ```
  @JavaMethod
  open func describeContents() -> Int32

    /// Java method `writeToParcel`.
    ///
    /// ### Java method signature
    /// ```java
    /// public void android.net.wifi.WifiManager$AddNetworkResult.writeToParcel(android.os.Parcel,int)
    /// ```
  @JavaMethod
  open func writeToParcel(_ arg0: Parcel?, _ arg1: Int32)
  }
}
@available(Android 30, *)
extension JavaClass<WifiManager.AddNetworkResult> {
  @JavaStaticField(isFinal: true)
  public var CREATOR: Parcelable.Creator<WifiManager.AddNetworkResult>!

  @JavaStaticField(isFinal: true)
  public var STATUS_ADD_PASSPOINT_FAILURE: Int32

  @JavaStaticField(isFinal: true)
  public var STATUS_ADD_WIFI_CONFIG_FAILURE: Int32

  @JavaStaticField(isFinal: true)
  public var STATUS_FAILURE_UNKNOWN: Int32

  @JavaStaticField(isFinal: true)
  public var STATUS_FAILURE_UPDATE_NETWORK_KEYS: Int32

  @JavaStaticField(isFinal: true)
  public var STATUS_INVALID_CONFIGURATION: Int32

  @JavaStaticField(isFinal: true)
  public var STATUS_INVALID_CONFIGURATION_ENTERPRISE: Int32

  @JavaStaticField(isFinal: true)
  public var STATUS_NO_PERMISSION: Int32

  @JavaStaticField(isFinal: true)
  public var STATUS_NO_PERMISSION_MODIFY_CONFIG: Int32

  @JavaStaticField(isFinal: true)
  public var STATUS_NO_PERMISSION_MODIFY_MAC_RANDOMIZATION: Int32

  @JavaStaticField(isFinal: true)
  public var STATUS_NO_PERMISSION_MODIFY_PROXY_SETTING: Int32

  @JavaStaticField(isFinal: true)
  public var STATUS_SUCCESS: Int32
}
