// Auto-generated by Java-to-Swift wrapper generator.
import AndroidOS
import SwiftJava
import SwiftJavaJNICore

@JavaClass("android.net.wifi.aware.WifiAwareChannelInfo", implements: Parcelable.self)
open class WifiAwareChannelInfo: JavaObject {
  /// Java method `getChannelFrequencyMhz`.
  ///
  /// ### Java method signature
  /// ```java
  /// public int android.net.wifi.aware.WifiAwareChannelInfo.getChannelFrequencyMhz()
  /// ```
@JavaMethod
  open func getChannelFrequencyMhz() -> Int32

  /// Java method `getChannelBandwidth`.
  ///
  /// ### Java method signature
  /// ```java
  /// public int android.net.wifi.aware.WifiAwareChannelInfo.getChannelBandwidth()
  /// ```
@JavaMethod
  open func getChannelBandwidth() -> Int32

  /// Java method `getSpatialStreamCount`.
  ///
  /// ### Java method signature
  /// ```java
  /// public int android.net.wifi.aware.WifiAwareChannelInfo.getSpatialStreamCount()
  /// ```
@JavaMethod
  open func getSpatialStreamCount() -> Int32

  /// Java method `describeContents`.
  ///
  /// ### Java method signature
  /// ```java
  /// public int android.net.wifi.aware.WifiAwareChannelInfo.describeContents()
  /// ```
@JavaMethod
  open func describeContents() -> Int32

  /// Java method `writeToParcel`.
  ///
  /// ### Java method signature
  /// ```java
  /// public void android.net.wifi.aware.WifiAwareChannelInfo.writeToParcel(android.os.Parcel,int)
  /// ```
@JavaMethod
  open func writeToParcel(_ arg0: Parcel?, _ arg1: Int32)

  /// Java method `equals`.
  ///
  /// ### Java method signature
  /// ```java
  /// public boolean android.net.wifi.aware.WifiAwareChannelInfo.equals(java.lang.Object)
  /// ```
@JavaMethod
  open override func equals(_ arg0: JavaObject?) -> Bool

  /// Java method `toString`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.lang.String android.net.wifi.aware.WifiAwareChannelInfo.toString()
  /// ```
@JavaMethod
  open override func toString() -> String

  /// Java method `hashCode`.
  ///
  /// ### Java method signature
  /// ```java
  /// public int android.net.wifi.aware.WifiAwareChannelInfo.hashCode()
  /// ```
@JavaMethod
  open override func hashCode() -> Int32
}
extension JavaClass<WifiAwareChannelInfo> {
  @JavaStaticField(isFinal: true)
  public var CREATOR: Parcelable.Creator<WifiAwareChannelInfo>!
}
