// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava
import CSwiftJavaJNI

extension ChildHelper {
  @JavaClass("androidx.recyclerview.widget.ChildHelper$Bucket")
  open class Bucket: JavaObject {
  @JavaMethod
  open override func toString() -> String
  }
}
