// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

@JavaClass("androidx.lifecycle.CompositeGeneratedAdaptersObserver", implements: LifecycleEventObserver.self)
open class CompositeGeneratedAdaptersObserver: JavaObject {
  @JavaMethod
  open func onStateChanged(_ arg0: LifecycleOwner?, _ arg1: Lifecycle.Event?)
}
