// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

extension ConcatAdapter {
  @JavaClass("androidx.recyclerview.widget.ConcatAdapter$Config")
  open class Config: JavaObject {
  @JavaField(isFinal: true)
  public var isolateViewTypes: Bool

  @JavaField(isFinal: true)
  public var stableIdMode: ConcatAdapter.Config.StableIdMode!
  }
}
extension JavaClass<ConcatAdapter.Config> {
  @JavaStaticField(isFinal: true)
  public var DEFAULT: ConcatAdapter.Config!
}
