// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

@JavaClass("androidx.recyclerview.widget.DiffUtil")
open class DiffUtil: JavaObject {

}
extension JavaClass<DiffUtil> {
  @JavaStaticMethod
  public func calculateDiff(_ arg0: DiffUtil.Callback?, _ arg1: Bool) -> DiffUtil.DiffResult!

  @JavaStaticMethod
  public func calculateDiff(_ arg0: DiffUtil.Callback?) -> DiffUtil.DiffResult!
}
