// Auto-generated by Java-to-Swift wrapper generator.
import AndroidContent
import AndroidGraphics
import AndroidView
import JavaKit
import JavaRuntime

@JavaClass("androidx.recyclerview.widget.DividerItemDecoration")
open class DividerItemDecoration: RecyclerView.ItemDecoration {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: Context?, _ arg1: Int32, environment: JNIEnvironment? = nil)

  @JavaMethod
  open func getDrawable() -> Drawable!

  @JavaMethod
  open override func onDraw(_ arg0: Canvas?, _ arg1: RecyclerView?, _ arg2: RecyclerView.State?)

  @JavaMethod
  open override func getItemOffsets(_ arg0: Rect?, _ arg1: View?, _ arg2: RecyclerView?, _ arg3: RecyclerView.State?)

  @JavaMethod
  open func setOrientation(_ arg0: Int32)

  @JavaMethod
  open func setDrawable(_ arg0: Drawable?)
}
extension JavaClass<DividerItemDecoration> {
  @JavaStaticField(isFinal: true)
  public var HORIZONTAL: Int32

  @JavaStaticField(isFinal: true)
  public var VERTICAL: Int32
}
