// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava
import CSwiftJavaJNI

extension FastScroller {
  @JavaClass("androidx.recyclerview.widget.FastScroller$AnimatorListener")
  open class AnimatorListener: JavaObject {

  }
}
