// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

extension GridLayoutManager {
  @JavaClass("androidx.recyclerview.widget.GridLayoutManager$DefaultSpanSizeLookup")
  open class DefaultSpanSizeLookup: GridLayoutManager.SpanSizeLookup {
  @JavaMethod
  @_nonoverride public convenience init(environment: JNIEnvironment? = nil)

  @JavaMethod
  open override func getSpanIndex(_ arg0: Int32, _ arg1: Int32) -> Int32

  @JavaMethod
  open override func getSpanSize(_ arg0: Int32) -> Int32
  }
}
