// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

@JavaInterface("androidx.lifecycle.LifecycleOwner")
public struct LifecycleOwner {
  @JavaMethod
  public func getLifecycle() -> Lifecycle!
}
