// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

extension NavBackStackEntry {
  @JavaClass("androidx.navigation.NavBackStackEntry$SavedStateViewModel")
  open class SavedStateViewModel: JavaObject {

  }
}
