// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

extension NavDeepLink {
  @JavaClass("androidx.navigation.NavDeepLink$Companion")
  open class Companion: JavaObject {

  }
}
