// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

@JavaClass("androidx.navigation.NavigatorProviderKt")
open class NavigatorProviderKt: JavaObject {

}
extension JavaClass<NavigatorProviderKt> {
  @JavaStaticMethod
  public func plusAssign(_ arg0: NavigatorProvider?, _ arg1: Navigator<NavDestination>?)

  @JavaStaticMethod
  public func get(_ arg0: NavigatorProvider?, _ arg1: String) -> Navigator<NavDestination>!

  @JavaStaticMethod
  public func set(_ arg0: NavigatorProvider?, _ arg1: String, _ arg2: Navigator<NavDestination>?) -> Navigator<NavDestination>!
}
