// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

extension RecyclerView.LayoutManager {
  @JavaClass("androidx.recyclerview.widget.RecyclerView$LayoutManager$Properties")
  open class Properties: JavaObject {
  @JavaField(isFinal: false)
  public var orientation: Int32

  @JavaField(isFinal: false)
  public var spanCount: Int32

  @JavaField(isFinal: false)
  public var reverseLayout: Bool

  @JavaField(isFinal: false)
  public var stackFromEnd: Bool

  @JavaMethod
  @_nonoverride public convenience init(environment: JNIEnvironment? = nil)
  }
}
