// Auto-generated by Java-to-Swift wrapper generator.
import AndroidGraphics
import SwiftJava
import CSwiftJavaJNI

extension RecyclerView.SmoothScroller {
  @JavaInterface("androidx.recyclerview.widget.RecyclerView$SmoothScroller$ScrollVectorProvider")
  public struct ScrollVectorProvider {
  @JavaMethod
  public func computeScrollVectorForPosition(_ arg0: Int32) -> PointF!
  }
}
