// Auto-generated by Java-to-Swift wrapper generator.
import AndroidOS
import JavaKit
import JavaRuntime

extension RecyclerView {
  @JavaClass("androidx.recyclerview.widget.RecyclerView$SavedState")
  open class SavedState: AbsSavedState {
  @JavaMethod
  open override func writeToParcel(_ arg0: Parcel?, _ arg1: Int32)
  }
}
extension JavaClass<RecyclerView.SavedState> {
  @JavaStaticField(isFinal: true)
  public var CREATOR: Parcelable.Creator<RecyclerView.SavedState>!

  @JavaStaticField(isFinal: true)
  public var EMPTY_STATE: AbsSavedState!

  @JavaStaticField(isFinal: true)
  public var CREATOR: Parcelable.Creator<AbsSavedState>!

  @JavaStaticField(isFinal: true)
  public var CONTENTS_FILE_DESCRIPTOR: Int32

  @JavaStaticField(isFinal: true)
  public var PARCELABLE_WRITE_RETURN_VALUE: Int32
}
