// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

extension SortedList {
  @JavaClass("androidx.recyclerview.widget.SortedList$BatchedCallback")
  open class BatchedCallback<T2: AnyJavaObject>: SortedList.Callback {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: SortedList.Callback<JavaObject>?, environment: JNIEnvironment? = nil)

  @JavaMethod
  open func onInserted(_ arg0: Int32, _ arg1: Int32)

  @JavaMethod
  open func onRemoved(_ arg0: Int32, _ arg1: Int32)

  @JavaMethod
  open override func onChanged(_ arg0: Int32, _ arg1: Int32, _ arg2: JavaObject?)

  @JavaMethod
  open override func onChanged(_ arg0: Int32, _ arg1: Int32)

  @JavaMethod
  open override func areContentsTheSame(_ arg0: JavaObject?, _ arg1: JavaObject?) -> Bool

  @JavaMethod
  open override func areItemsTheSame(_ arg0: JavaObject?, _ arg1: JavaObject?) -> Bool

  @JavaMethod
  open override func getChangePayload(_ arg0: JavaObject?, _ arg1: JavaObject?) -> JavaObject!

  @JavaMethod
  open func dispatchLastEvent()

  @JavaMethod
  open func onMoved(_ arg0: Int32, _ arg1: Int32)

  @JavaMethod
  open override func compare(_ arg0: JavaObject?, _ arg1: JavaObject?) -> Int32
  }
}
