// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

extension StableIdStorage.IsolatedStableIdStorage {
  @JavaClass("androidx.recyclerview.widget.StableIdStorage$IsolatedStableIdStorage$WrapperStableIdLookup", implements: StableIdStorage.StableIdLookup.self)
  open class WrapperStableIdLookup: JavaObject {
  @JavaMethod
  open func localToGlobal(_ arg0: Int64) -> Int64
  }
}
