// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

extension ViewBoundsCheck {
  @JavaClass("androidx.recyclerview.widget.ViewBoundsCheck$BoundFlags")
  open class BoundFlags: JavaObject {

  }
}
