// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava
import CSwiftJavaJNI

extension ViewBoundsCheck {
  @JavaClass("androidx.recyclerview.widget.ViewBoundsCheck$BoundFlags")
  open class BoundFlags: JavaObject {

  }
}
