// Auto-generated by Java-to-Swift wrapper generator.
import JavaIO
import SwiftJava
import SwiftJavaJNICore

@available(Android 18, *)
@JavaClass("android.media.MediaMuxer")
open class MediaMuxer: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: String, _ arg1: Int32, environment: JNIEnvironment? = nil) throws

  @JavaMethod
  @_nonoverride public convenience init(_ arg0: FileDescriptor?, _ arg1: Int32, environment: JNIEnvironment? = nil) throws

    /// Java method `setOrientationHint`.
    ///
    /// ### Java method signature
    /// ```java
    /// public void android.media.MediaMuxer.setOrientationHint(int)
    /// ```
  @JavaMethod
  open func setOrientationHint(_ arg0: Int32)

    /// Java method `setLocation`.
    ///
    /// ### Java method signature
    /// ```java
    /// public void android.media.MediaMuxer.setLocation(float,float)
    /// ```
  @available(Android 19, *)
  @JavaMethod
  open func setLocation(_ arg0: Float, _ arg1: Float)

    /// Java method `addTrack`.
    ///
    /// ### Java method signature
    /// ```java
    /// public int android.media.MediaMuxer.addTrack(android.media.MediaFormat)
    /// ```
  @JavaMethod
  open func addTrack(_ arg0: MediaFormat?) -> Int32

    /// Java method `finalize`.
    ///
    /// ### Java method signature
    /// ```java
    /// protected void android.media.MediaMuxer.finalize() throws java.lang.Throwable
    /// ```
  @JavaMethod
  open override func finalize() throws

    /// Java method `start`.
    ///
    /// ### Java method signature
    /// ```java
    /// public void android.media.MediaMuxer.start()
    /// ```
  @JavaMethod
  open func start()

    /// Java method `stop`.
    ///
    /// ### Java method signature
    /// ```java
    /// public void android.media.MediaMuxer.stop()
    /// ```
  @JavaMethod
  open func stop()

    /// Java method `release`.
    ///
    /// ### Java method signature
    /// ```java
    /// public void android.media.MediaMuxer.release()
    /// ```
  @JavaMethod
  open func release()
}
extension MediaMuxer {
  @JavaClass("android.media.MediaMuxer$OutputFormat")
  open class OutputFormat: JavaObject {

  }
}
@available(Android 18, *)
extension JavaClass<MediaMuxer.OutputFormat> {
  @JavaStaticField(isFinal: true)
  public var MUXER_OUTPUT_3GPP: Int32

  @JavaStaticField(isFinal: true)
  public var MUXER_OUTPUT_HEIF: Int32

  @JavaStaticField(isFinal: true)
  public var MUXER_OUTPUT_MPEG_4: Int32

  @JavaStaticField(isFinal: true)
  public var MUXER_OUTPUT_OGG: Int32

  @JavaStaticField(isFinal: true)
  public var MUXER_OUTPUT_WEBM: Int32
}
