// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

extension ActionProvider {
  @JavaInterface("android.view.ActionProvider$VisibilityListener")
  public struct VisibilityListener {
  @JavaMethod
  public func onActionProviderVisibilityChanged(_ arg0: Bool)
  }
}
