// Auto-generated by Java-to-Swift wrapper generator.
import AndroidContent
import AndroidUtil
import JavaKit
import JavaKitCollection
import JavaRuntime

@JavaClass("android.view.animation.AnimationSet")
open class AnimationSet: Animation {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: Context?, _ arg1: AttributeSet?, environment: JNIEnvironment? = nil)

  @JavaMethod
  @_nonoverride public convenience init(_ arg0: Bool, environment: JNIEnvironment? = nil)

  @JavaMethod
  open override func reset()

  @JavaMethod
  open override func clone() throws -> AnimationSet!

  @JavaMethod
  open override func initialize(_ arg0: Int32, _ arg1: Int32, _ arg2: Int32, _ arg3: Int32)

  @JavaMethod
  open override func getDuration() -> Int64

  @JavaMethod
  open override func scaleCurrentDuration(_ arg0: Float)

  @JavaMethod
  open override func willChangeTransformationMatrix() -> Bool

  @JavaMethod
  open override func computeDurationHint() -> Int64

  @JavaMethod
  open override func setStartOffset(_ arg0: Int64)

  @JavaMethod
  open override func setDuration(_ arg0: Int64)

  @JavaMethod
  open override func restrictDuration(_ arg0: Int64)

  @JavaMethod
  open override func setStartTime(_ arg0: Int64)

  @JavaMethod
  open override func setRepeatMode(_ arg0: Int32)

  @JavaMethod
  open override func setFillBefore(_ arg0: Bool)

  @JavaMethod
  open override func setFillAfter(_ arg0: Bool)

  @JavaMethod
  open override func getStartTime() -> Int64

  @JavaMethod
  open override func willChangeBounds() -> Bool

  @JavaMethod
  open override func getTransformation(_ arg0: Int64, _ arg1: Transformation?) -> Bool

  @JavaMethod
  open func addAnimation(_ arg0: Animation?)

  @JavaMethod
  open func getAnimations() -> List<Animation>!
}
extension JavaClass<AnimationSet> {
  @JavaStaticField(isFinal: true)
  public var ABSOLUTE: Int32

  @JavaStaticField(isFinal: true)
  public var INFINITE: Int32

  @JavaStaticField(isFinal: true)
  public var RELATIVE_TO_PARENT: Int32

  @JavaStaticField(isFinal: true)
  public var RELATIVE_TO_SELF: Int32

  @JavaStaticField(isFinal: true)
  public var RESTART: Int32

  @JavaStaticField(isFinal: true)
  public var REVERSE: Int32

  @JavaStaticField(isFinal: true)
  public var START_ON_FIRST_FRAME: Int32

  @JavaStaticField(isFinal: true)
  public var ZORDER_BOTTOM: Int32

  @JavaStaticField(isFinal: true)
  public var ZORDER_NORMAL: Int32

  @JavaStaticField(isFinal: true)
  public var ZORDER_TOP: Int32
}
