// Auto-generated by Java-to-Swift wrapper generator.
import AndroidOS
import JavaKit
import JavaRuntime

extension Display {
  @JavaClass("android.view.Display$HdrCapabilities", implements: Parcelable.self)
  open class HdrCapabilities: JavaObject {
  @JavaMethod
  open func writeToParcel(_ arg0: Parcel?, _ arg1: Int32)

  @JavaMethod
  open func describeContents() -> Int32

  @JavaMethod
  open func getSupportedHdrTypes() -> [Int32]

  @JavaMethod
  open func getDesiredMaxLuminance() -> Float

  @JavaMethod
  open func getDesiredMaxAverageLuminance() -> Float

  @JavaMethod
  open func getDesiredMinLuminance() -> Float

  @JavaMethod
  open override func equals(_ arg0: JavaObject?) -> Bool

  @JavaMethod
  open override func toString() -> String

  @JavaMethod
  open override func hashCode() -> Int32
  }
}
extension JavaClass<Display.HdrCapabilities> {
  @JavaStaticField(isFinal: true)
  public var CREATOR: Parcelable.Creator<Display.HdrCapabilities>!

  @JavaStaticField(isFinal: true)
  public var HDR_TYPE_DOLBY_VISION: Int32

  @JavaStaticField(isFinal: true)
  public var HDR_TYPE_HDR10: Int32

  @JavaStaticField(isFinal: true)
  public var HDR_TYPE_HDR10_PLUS: Int32

  @JavaStaticField(isFinal: true)
  public var HDR_TYPE_HLG: Int32

  @JavaStaticField(isFinal: true)
  public var INVALID_LUMINANCE: Float

  @JavaStaticField(isFinal: true)
  public var CONTENTS_FILE_DESCRIPTOR: Int32

  @JavaStaticField(isFinal: true)
  public var PARCELABLE_WRITE_RETURN_VALUE: Int32
}
