// Auto-generated by Java-to-Swift wrapper generator.
import AndroidGraphics
import JavaKit
import JavaRuntime

@JavaClass("android.view.FocusFinder")
open class FocusFinder: JavaObject {
  @JavaMethod
  open func findNextFocus(_ arg0: ViewGroup?, _ arg1: View?, _ arg2: Int32) -> View!

  @JavaMethod
  open func findNextFocusFromRect(_ arg0: ViewGroup?, _ arg1: Rect?, _ arg2: Int32) -> View!

  @JavaMethod
  open func findNextKeyboardNavigationCluster(_ arg0: View?, _ arg1: View?, _ arg2: Int32) -> View!

  @JavaMethod
  open func findNearestTouchable(_ arg0: ViewGroup?, _ arg1: Int32, _ arg2: Int32, _ arg3: Int32, _ arg4: [Int32]) -> View!
}
extension JavaClass<FocusFinder> {
  @JavaStaticMethod
  public func getInstance() -> FocusFinder!
}
