// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

extension GestureDetector {
  @JavaInterface("android.view.GestureDetector$OnDoubleTapListener")
  public struct OnDoubleTapListener {
  @JavaMethod
  public func onDoubleTap(_ arg0: MotionEvent?) -> Bool

  @JavaMethod
  public func onDoubleTapEvent(_ arg0: MotionEvent?) -> Bool

  @JavaMethod
  public func onSingleTapConfirmed(_ arg0: MotionEvent?) -> Bool
  }
}
