// Auto-generated by Java-to-Swift wrapper generator.
import AndroidOS
import JavaKit
import JavaRuntime

@JavaClass("android.view.KeyboardShortcutInfo", implements: Parcelable.self)
open class KeyboardShortcutInfo: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: CharSequence?, _ arg1: Int32, _ arg2: Int32, environment: JNIEnvironment? = nil)

  @JavaMethod
  @_nonoverride public convenience init(_ arg0: CharSequence?, _ arg1: UInt16, _ arg2: Int32, environment: JNIEnvironment? = nil)

  @JavaMethod
  open func getModifiers() -> Int32

  @JavaMethod
  open func getLabel() -> CharSequence!

  @JavaMethod
  open func describeContents() -> Int32

  @JavaMethod
  open func writeToParcel(_ arg0: Parcel?, _ arg1: Int32)

  @JavaMethod
  open func getKeycode() -> Int32

  @JavaMethod
  open func getBaseCharacter() -> UInt16
}
extension JavaClass<KeyboardShortcutInfo> {
  @JavaStaticField(isFinal: true)
  public var CREATOR: Parcelable.Creator<KeyboardShortcutInfo>!

  @JavaStaticField(isFinal: true)
  public var CONTENTS_FILE_DESCRIPTOR: Int32

  @JavaStaticField(isFinal: true)
  public var PARCELABLE_WRITE_RETURN_VALUE: Int32
}
