// Auto-generated by Java-to-Swift wrapper generator.
import AndroidGraphics
import AndroidOS
import JavaKit
import JavaRuntime

@JavaClass("android.view.MotionEvent", implements: Parcelable.self)
open class MotionEvent: InputEvent {
  @JavaMethod
  open func getX() -> Float

  @JavaMethod
  open func getX(_ arg0: Int32) -> Float

  @JavaMethod
  open func getY(_ arg0: Int32) -> Float

  @JavaMethod
  open func getY() -> Float

  @JavaMethod
  open func getAction() -> Int32

  @JavaMethod
  open func getMetaState() -> Int32

  @JavaMethod
  open func writeToParcel(_ arg0: Parcel?, _ arg1: Int32)

  @JavaMethod
  open override func getDeviceId() -> Int32

  @JavaMethod
  open func recycle()

  @JavaMethod
  open func getOrientation() -> Float

  @JavaMethod
  open func getOrientation(_ arg0: Int32) -> Float

  @JavaMethod
  open override func getSource() -> Int32

  @JavaMethod
  open func setSource(_ arg0: Int32)

  @JavaMethod
  open func getActionMasked() -> Int32

  @JavaMethod
  open func getActionIndex() -> Int32

  @JavaMethod
  open func getDownTime() -> Int64

  @JavaMethod
  open override func getEventTime() -> Int64

  @JavaMethod
  open func getPressure(_ arg0: Int32) -> Float

  @JavaMethod
  open func getPressure() -> Float

  @JavaMethod
  open func getTouchMajor(_ arg0: Int32) -> Float

  @JavaMethod
  open func getTouchMajor() -> Float

  @JavaMethod
  open func getTouchMinor(_ arg0: Int32) -> Float

  @JavaMethod
  open func getTouchMinor() -> Float

  @JavaMethod
  open func getToolMajor() -> Float

  @JavaMethod
  open func getToolMajor(_ arg0: Int32) -> Float

  @JavaMethod
  open func getToolMinor() -> Float

  @JavaMethod
  open func getToolMinor(_ arg0: Int32) -> Float

  @JavaMethod
  open func getAxisValue(_ arg0: Int32) -> Float

  @JavaMethod
  open func getAxisValue(_ arg0: Int32, _ arg1: Int32) -> Float

  @JavaMethod
  open func getPointerCount() -> Int32

  @JavaMethod
  open func getPointerId(_ arg0: Int32) -> Int32

  @JavaMethod
  open func getToolType(_ arg0: Int32) -> Int32

  @JavaMethod
  open func findPointerIndex(_ arg0: Int32) -> Int32

  @JavaMethod
  open func getPointerCoords(_ arg0: Int32, _ arg1: MotionEvent.PointerCoords?)

  @JavaMethod
  open func getPointerProperties(_ arg0: Int32, _ arg1: MotionEvent.PointerProperties?)

  @JavaMethod
  open func getButtonState() -> Int32

  @JavaMethod
  open func getClassification() -> Int32

  @JavaMethod
  open func getActionButton() -> Int32

  @JavaMethod
  open func getRawX(_ arg0: Int32) -> Float

  @JavaMethod
  open func getRawX() -> Float

  @JavaMethod
  open func getRawY() -> Float

  @JavaMethod
  open func getRawY(_ arg0: Int32) -> Float

  @JavaMethod
  open func getXPrecision() -> Float

  @JavaMethod
  open func getYPrecision() -> Float

  @JavaMethod
  open func getHistorySize() -> Int32

  @JavaMethod
  open func getHistoricalEventTime(_ arg0: Int32) -> Int64

  @JavaMethod
  open func getHistoricalX(_ arg0: Int32) -> Float

  @JavaMethod
  open func getHistoricalX(_ arg0: Int32, _ arg1: Int32) -> Float

  @JavaMethod
  open func getHistoricalY(_ arg0: Int32) -> Float

  @JavaMethod
  open func getHistoricalY(_ arg0: Int32, _ arg1: Int32) -> Float

  @JavaMethod
  open func getHistoricalPressure(_ arg0: Int32) -> Float

  @JavaMethod
  open func getHistoricalPressure(_ arg0: Int32, _ arg1: Int32) -> Float

  @JavaMethod
  open func getHistoricalSize(_ arg0: Int32) -> Float

  @JavaMethod
  open func getHistoricalSize(_ arg0: Int32, _ arg1: Int32) -> Float

  @JavaMethod
  open func getHistoricalTouchMajor(_ arg0: Int32) -> Float

  @JavaMethod
  open func getHistoricalTouchMajor(_ arg0: Int32, _ arg1: Int32) -> Float

  @JavaMethod
  open func getHistoricalTouchMinor(_ arg0: Int32, _ arg1: Int32) -> Float

  @JavaMethod
  open func getHistoricalTouchMinor(_ arg0: Int32) -> Float

  @JavaMethod
  open func getHistoricalToolMajor(_ arg0: Int32, _ arg1: Int32) -> Float

  @JavaMethod
  open func getHistoricalToolMajor(_ arg0: Int32) -> Float

  @JavaMethod
  open func getHistoricalToolMinor(_ arg0: Int32, _ arg1: Int32) -> Float

  @JavaMethod
  open func getHistoricalToolMinor(_ arg0: Int32) -> Float

  @JavaMethod
  open func getHistoricalOrientation(_ arg0: Int32, _ arg1: Int32) -> Float

  @JavaMethod
  open func getHistoricalOrientation(_ arg0: Int32) -> Float

  @JavaMethod
  open func getHistoricalAxisValue(_ arg0: Int32, _ arg1: Int32) -> Float

  @JavaMethod
  open func getHistoricalAxisValue(_ arg0: Int32, _ arg1: Int32, _ arg2: Int32) -> Float

  @JavaMethod
  open func getHistoricalPointerCoords(_ arg0: Int32, _ arg1: Int32, _ arg2: MotionEvent.PointerCoords?)

  @JavaMethod
  open func getEdgeFlags() -> Int32

  @JavaMethod
  open func setEdgeFlags(_ arg0: Int32)

  @JavaMethod
  open func setAction(_ arg0: Int32)

  @JavaMethod
  open func offsetLocation(_ arg0: Float, _ arg1: Float)

  @JavaMethod
  open func setLocation(_ arg0: Float, _ arg1: Float)

  @JavaMethod
  open func addBatch(_ arg0: Int64, _ arg1: [MotionEvent.PointerCoords?], _ arg2: Int32)

  @JavaMethod
  open func addBatch(_ arg0: Int64, _ arg1: Float, _ arg2: Float, _ arg3: Float, _ arg4: Float, _ arg5: Int32)

  @JavaMethod
  open func isButtonPressed(_ arg0: Int32) -> Bool

  @JavaMethod
  open override func finalize() throws

  @JavaMethod
  open override func toString() -> String

  @JavaMethod
  open func transform(_ arg0: Matrix?)

  @JavaMethod
  open func getSize(_ arg0: Int32) -> Float

  @JavaMethod
  open func getSize() -> Float

  @JavaMethod
  open func getFlags() -> Int32
}
extension JavaClass<MotionEvent> {
  @JavaStaticField(isFinal: true)
  public var ACTION_BUTTON_PRESS: Int32

  @JavaStaticField(isFinal: true)
  public var ACTION_BUTTON_RELEASE: Int32

  @JavaStaticField(isFinal: true)
  public var ACTION_CANCEL: Int32

  @JavaStaticField(isFinal: true)
  public var ACTION_DOWN: Int32

  @JavaStaticField(isFinal: true)
  public var ACTION_HOVER_ENTER: Int32

  @JavaStaticField(isFinal: true)
  public var ACTION_HOVER_EXIT: Int32

  @JavaStaticField(isFinal: true)
  public var ACTION_HOVER_MOVE: Int32

  @JavaStaticField(isFinal: true)
  public var ACTION_MASK: Int32

  @JavaStaticField(isFinal: true)
  public var ACTION_MOVE: Int32

  @JavaStaticField(isFinal: true)
  public var ACTION_OUTSIDE: Int32

  @JavaStaticField(isFinal: true)
  public var ACTION_POINTER_1_DOWN: Int32

  @JavaStaticField(isFinal: true)
  public var ACTION_POINTER_1_UP: Int32

  @JavaStaticField(isFinal: true)
  public var ACTION_POINTER_2_DOWN: Int32

  @JavaStaticField(isFinal: true)
  public var ACTION_POINTER_2_UP: Int32

  @JavaStaticField(isFinal: true)
  public var ACTION_POINTER_3_DOWN: Int32

  @JavaStaticField(isFinal: true)
  public var ACTION_POINTER_3_UP: Int32

  @JavaStaticField(isFinal: true)
  public var ACTION_POINTER_DOWN: Int32

  @JavaStaticField(isFinal: true)
  public var ACTION_POINTER_ID_MASK: Int32

  @JavaStaticField(isFinal: true)
  public var ACTION_POINTER_ID_SHIFT: Int32

  @JavaStaticField(isFinal: true)
  public var ACTION_POINTER_INDEX_MASK: Int32

  @JavaStaticField(isFinal: true)
  public var ACTION_POINTER_INDEX_SHIFT: Int32

  @JavaStaticField(isFinal: true)
  public var ACTION_POINTER_UP: Int32

  @JavaStaticField(isFinal: true)
  public var ACTION_SCROLL: Int32

  @JavaStaticField(isFinal: true)
  public var ACTION_UP: Int32

  @JavaStaticField(isFinal: true)
  public var AXIS_BRAKE: Int32

  @JavaStaticField(isFinal: true)
  public var AXIS_DISTANCE: Int32

  @JavaStaticField(isFinal: true)
  public var AXIS_GAS: Int32

  @JavaStaticField(isFinal: true)
  public var AXIS_GENERIC_1: Int32

  @JavaStaticField(isFinal: true)
  public var AXIS_GENERIC_10: Int32

  @JavaStaticField(isFinal: true)
  public var AXIS_GENERIC_11: Int32

  @JavaStaticField(isFinal: true)
  public var AXIS_GENERIC_12: Int32

  @JavaStaticField(isFinal: true)
  public var AXIS_GENERIC_13: Int32

  @JavaStaticField(isFinal: true)
  public var AXIS_GENERIC_14: Int32

  @JavaStaticField(isFinal: true)
  public var AXIS_GENERIC_15: Int32

  @JavaStaticField(isFinal: true)
  public var AXIS_GENERIC_16: Int32

  @JavaStaticField(isFinal: true)
  public var AXIS_GENERIC_2: Int32

  @JavaStaticField(isFinal: true)
  public var AXIS_GENERIC_3: Int32

  @JavaStaticField(isFinal: true)
  public var AXIS_GENERIC_4: Int32

  @JavaStaticField(isFinal: true)
  public var AXIS_GENERIC_5: Int32

  @JavaStaticField(isFinal: true)
  public var AXIS_GENERIC_6: Int32

  @JavaStaticField(isFinal: true)
  public var AXIS_GENERIC_7: Int32

  @JavaStaticField(isFinal: true)
  public var AXIS_GENERIC_8: Int32

  @JavaStaticField(isFinal: true)
  public var AXIS_GENERIC_9: Int32

  @JavaStaticField(isFinal: true)
  public var AXIS_HAT_X: Int32

  @JavaStaticField(isFinal: true)
  public var AXIS_HAT_Y: Int32

  @JavaStaticField(isFinal: true)
  public var AXIS_HSCROLL: Int32

  @JavaStaticField(isFinal: true)
  public var AXIS_LTRIGGER: Int32

  @JavaStaticField(isFinal: true)
  public var AXIS_ORIENTATION: Int32

  @JavaStaticField(isFinal: true)
  public var AXIS_PRESSURE: Int32

  @JavaStaticField(isFinal: true)
  public var AXIS_RELATIVE_X: Int32

  @JavaStaticField(isFinal: true)
  public var AXIS_RELATIVE_Y: Int32

  @JavaStaticField(isFinal: true)
  public var AXIS_RTRIGGER: Int32

  @JavaStaticField(isFinal: true)
  public var AXIS_RUDDER: Int32

  @JavaStaticField(isFinal: true)
  public var AXIS_RX: Int32

  @JavaStaticField(isFinal: true)
  public var AXIS_RY: Int32

  @JavaStaticField(isFinal: true)
  public var AXIS_RZ: Int32

  @JavaStaticField(isFinal: true)
  public var AXIS_SCROLL: Int32

  @JavaStaticField(isFinal: true)
  public var AXIS_SIZE: Int32

  @JavaStaticField(isFinal: true)
  public var AXIS_THROTTLE: Int32

  @JavaStaticField(isFinal: true)
  public var AXIS_TILT: Int32

  @JavaStaticField(isFinal: true)
  public var AXIS_TOOL_MAJOR: Int32

  @JavaStaticField(isFinal: true)
  public var AXIS_TOOL_MINOR: Int32

  @JavaStaticField(isFinal: true)
  public var AXIS_TOUCH_MAJOR: Int32

  @JavaStaticField(isFinal: true)
  public var AXIS_TOUCH_MINOR: Int32

  @JavaStaticField(isFinal: true)
  public var AXIS_VSCROLL: Int32

  @JavaStaticField(isFinal: true)
  public var AXIS_WHEEL: Int32

  @JavaStaticField(isFinal: true)
  public var AXIS_X: Int32

  @JavaStaticField(isFinal: true)
  public var AXIS_Y: Int32

  @JavaStaticField(isFinal: true)
  public var AXIS_Z: Int32

  @JavaStaticField(isFinal: true)
  public var BUTTON_BACK: Int32

  @JavaStaticField(isFinal: true)
  public var BUTTON_FORWARD: Int32

  @JavaStaticField(isFinal: true)
  public var BUTTON_PRIMARY: Int32

  @JavaStaticField(isFinal: true)
  public var BUTTON_SECONDARY: Int32

  @JavaStaticField(isFinal: true)
  public var BUTTON_STYLUS_PRIMARY: Int32

  @JavaStaticField(isFinal: true)
  public var BUTTON_STYLUS_SECONDARY: Int32

  @JavaStaticField(isFinal: true)
  public var BUTTON_TERTIARY: Int32

  @JavaStaticField(isFinal: true)
  public var CLASSIFICATION_AMBIGUOUS_GESTURE: Int32

  @JavaStaticField(isFinal: true)
  public var CLASSIFICATION_DEEP_PRESS: Int32

  @JavaStaticField(isFinal: true)
  public var CLASSIFICATION_NONE: Int32

  @JavaStaticField(isFinal: true)
  public var CREATOR: Parcelable.Creator<MotionEvent>!

  @JavaStaticField(isFinal: true)
  public var EDGE_BOTTOM: Int32

  @JavaStaticField(isFinal: true)
  public var EDGE_LEFT: Int32

  @JavaStaticField(isFinal: true)
  public var EDGE_RIGHT: Int32

  @JavaStaticField(isFinal: true)
  public var EDGE_TOP: Int32

  @JavaStaticField(isFinal: true)
  public var FLAG_CANCELED: Int32

  @JavaStaticField(isFinal: true)
  public var FLAG_WINDOW_IS_OBSCURED: Int32

  @JavaStaticField(isFinal: true)
  public var FLAG_WINDOW_IS_PARTIALLY_OBSCURED: Int32

  @JavaStaticField(isFinal: true)
  public var INVALID_POINTER_ID: Int32

  @JavaStaticField(isFinal: true)
  public var TOOL_TYPE_ERASER: Int32

  @JavaStaticField(isFinal: true)
  public var TOOL_TYPE_FINGER: Int32

  @JavaStaticField(isFinal: true)
  public var TOOL_TYPE_MOUSE: Int32

  @JavaStaticField(isFinal: true)
  public var TOOL_TYPE_STYLUS: Int32

  @JavaStaticField(isFinal: true)
  public var TOOL_TYPE_UNKNOWN: Int32

  @JavaStaticField(isFinal: true)
  public var CONTENTS_FILE_DESCRIPTOR: Int32

  @JavaStaticField(isFinal: true)
  public var PARCELABLE_WRITE_RETURN_VALUE: Int32

  @JavaStaticMethod
  public func obtain(_ arg0: Int64, _ arg1: Int64, _ arg2: Int32, _ arg3: Int32, _ arg4: [MotionEvent.PointerProperties?], _ arg5: [MotionEvent.PointerCoords?], _ arg6: Int32, _ arg7: Int32, _ arg8: Float, _ arg9: Float, _ arg10: Int32, _ arg11: Int32, _ arg12: Int32, _ arg13: Int32) -> MotionEvent!

  @JavaStaticMethod
  public func obtain(_ arg0: Int64, _ arg1: Int64, _ arg2: Int32, _ arg3: Float, _ arg4: Float, _ arg5: Float, _ arg6: Float, _ arg7: Int32, _ arg8: Float, _ arg9: Float, _ arg10: Int32, _ arg11: Int32) -> MotionEvent!

  @JavaStaticMethod
  public func obtain(_ arg0: Int64, _ arg1: Int64, _ arg2: Int32, _ arg3: Float, _ arg4: Float, _ arg5: Int32) -> MotionEvent!

  @JavaStaticMethod
  public func obtain(_ arg0: Int64, _ arg1: Int64, _ arg2: Int32, _ arg3: Int32, _ arg4: Float, _ arg5: Float, _ arg6: Float, _ arg7: Float, _ arg8: Int32, _ arg9: Float, _ arg10: Float, _ arg11: Int32, _ arg12: Int32) -> MotionEvent!

  @JavaStaticMethod
  public func obtain(_ arg0: Int64, _ arg1: Int64, _ arg2: Int32, _ arg3: Int32, _ arg4: [Int32], _ arg5: [MotionEvent.PointerCoords?], _ arg6: Int32, _ arg7: Float, _ arg8: Float, _ arg9: Int32, _ arg10: Int32, _ arg11: Int32, _ arg12: Int32) -> MotionEvent!

  @JavaStaticMethod
  public func obtain(_ arg0: MotionEvent?) -> MotionEvent!

  @JavaStaticMethod
  public func obtainNoHistory(_ arg0: MotionEvent?) -> MotionEvent!

  @JavaStaticMethod
  public func actionToString(_ arg0: Int32) -> String

  @JavaStaticMethod
  public func axisToString(_ arg0: Int32) -> String

  @JavaStaticMethod
  public func axisFromString(_ arg0: String) -> Int32
}
