// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

extension MotionEvent {
  @JavaClass("android.view.MotionEvent$PointerCoords")
  open class PointerCoords: JavaObject {
  @JavaField(isFinal: false)
  public var orientation: Float

  @JavaField(isFinal: false)
  public var pressure: Float

  @JavaField(isFinal: false)
  public var size: Float

  @JavaField(isFinal: false)
  public var toolMajor: Float

  @JavaField(isFinal: false)
  public var toolMinor: Float

  @JavaField(isFinal: false)
  public var touchMajor: Float

  @JavaField(isFinal: false)
  public var touchMinor: Float

  @JavaField(isFinal: false)
  public var x: Float

  @JavaField(isFinal: false)
  public var y: Float

  @JavaMethod
  @_nonoverride public convenience init(environment: JNIEnvironment? = nil)

  @JavaMethod
  @_nonoverride public convenience init(_ arg0: MotionEvent.PointerCoords?, environment: JNIEnvironment? = nil)

  @JavaMethod
  open func setAxisValue(_ arg0: Int32, _ arg1: Float)

  @JavaMethod
  open func getAxisValue(_ arg0: Int32) -> Float

  @JavaMethod
  open func clear()

  @JavaMethod
  open func copyFrom(_ arg0: MotionEvent.PointerCoords?)
  }
}
