// Auto-generated by Java-to-Swift wrapper generator.
import AndroidContent
import AndroidGraphics
import AndroidUtil
import JavaKit
import JavaRuntime

@JavaClass("android.view.animation.PathInterpolator")
open class PathInterpolator: BaseInterpolator {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: Context?, _ arg1: AttributeSet?, environment: JNIEnvironment? = nil)

  @JavaMethod
  @_nonoverride public convenience init(_ arg0: Float, _ arg1: Float, _ arg2: Float, _ arg3: Float, environment: JNIEnvironment? = nil)

  @JavaMethod
  @_nonoverride public convenience init(_ arg0: Float, _ arg1: Float, environment: JNIEnvironment? = nil)

  @JavaMethod
  @_nonoverride public convenience init(_ arg0: Path?, environment: JNIEnvironment? = nil)

  @JavaMethod
  open func getInterpolation(_ arg0: Float) -> Float
}
