// Auto-generated by Java-to-Swift wrapper generator.
import AndroidGraphics
import JavaLang
import AndroidOS
import JavaKit
import JavaKitFunction
import JavaRuntime

@JavaInterface("android.view.ScrollCaptureCallback")
public struct ScrollCaptureCallback {
  @JavaMethod
  public func onScrollCaptureSearch(_ arg0: CancellationSignal?, _ arg1: JavaConsumer<Rect>?)

  @JavaMethod
  public func onScrollCaptureStart(_ arg0: ScrollCaptureSession?, _ arg1: CancellationSignal?, _ arg2: Runnable?)

  @JavaMethod
  public func onScrollCaptureEnd(_ arg0: Runnable?)

  @JavaMethod
  public func onScrollCaptureImageRequest(_ arg0: ScrollCaptureSession?, _ arg1: CancellationSignal?, _ arg2: Rect?, _ arg3: JavaConsumer<Rect>?)
}
