// Auto-generated by Java-to-Swift wrapper generator.
import AndroidContent
import AndroidOS
import JavaKit
import JavaRuntime

extension SurfaceControlViewHost {
  @JavaClass("android.view.SurfaceControlViewHost$SurfacePackage", implements: Parcelable.self)
  open class SurfacePackage: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: SurfaceControlViewHost.SurfacePackage?, environment: JNIEnvironment? = nil)

  @JavaMethod
  open func writeToParcel(_ arg0: Parcel?, _ arg1: Int32)

  @JavaMethod
  open func describeContents() -> Int32

  @JavaMethod
  open func notifyConfigurationChanged(_ arg0: Configuration?)

  @JavaMethod
  open func notifyDetachedFromWindow()

  @JavaMethod
  open func release()
  }
}
extension JavaClass<SurfaceControlViewHost.SurfacePackage> {
  @JavaStaticField(isFinal: true)
  public var CREATOR: Parcelable.Creator<SurfaceControlViewHost.SurfacePackage>!

  @JavaStaticField(isFinal: true)
  public var CONTENTS_FILE_DESCRIPTOR: Int32

  @JavaStaticField(isFinal: true)
  public var PARCELABLE_WRITE_RETURN_VALUE: Int32
}
