// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava
import CSwiftJavaJNI

extension ViewTreeObserver {
  @JavaInterface("android.view.ViewTreeObserver$OnGlobalFocusChangeListener")
  public struct OnGlobalFocusChangeListener {
  @JavaMethod
  public func onGlobalFocusChanged(_ arg0: View?, _ arg1: View?)
  }
}
