// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava
import CSwiftJavaJNI

extension ViewTreeObserver {
  @JavaInterface("android.view.ViewTreeObserver$OnPreDrawListener")
  public struct OnPreDrawListener {
  @JavaMethod
  public func onPreDraw() -> Bool
  }
}
