// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava
import CSwiftJavaJNI

extension View {
  @JavaInterface("android.view.View$OnDragListener")
  public struct OnDragListener {
  @JavaMethod
  public func onDrag(_ arg0: View?, _ arg1: DragEvent?) -> Bool
  }
}
