// Auto-generated by Java-to-Swift wrapper generator.
import AndroidContent
import AndroidGraphics
import AndroidJavaLang
import AndroidJavaUtil
import AndroidOS
import AndroidUtil
import JavaKit
import JavaKitCollection
import JavaKitFunction
import JavaRuntime

@JavaClass("android.view.View", implements: Drawable.Callback.self, KeyEvent.Callback.self)
open class View: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: Context?, environment: JNIEnvironment? = nil)

  @JavaMethod
  @_nonoverride public convenience init(_ arg0: Context?, _ arg1: AttributeSet?, _ arg2: Int32, environment: JNIEnvironment? = nil)

  @JavaMethod
  @_nonoverride public convenience init(_ arg0: Context?, _ arg1: AttributeSet?, environment: JNIEnvironment? = nil)

  @JavaMethod
  @_nonoverride public convenience init(_ arg0: Context?, _ arg1: AttributeSet?, _ arg2: Int32, _ arg3: Int32, environment: JNIEnvironment? = nil)

  @JavaMethod
  open func onMeasure(_ arg0: Int32, _ arg1: Int32)

  @JavaMethod
  open func draw(_ arg0: Canvas?)

  @JavaMethod
  open func dispatchDraw(_ arg0: Canvas?)

  @JavaMethod
  open func setVisibility(_ arg0: Int32)

  @JavaMethod
  open func getAttributeResolutionStack(_ arg0: Int32) -> [Int32]

  @JavaMethod
  open func getAttributeSourceResourceMap() -> Map<JavaInteger, JavaInteger>!

  @JavaMethod
  open func getExplicitStyle() -> Int32

  @JavaMethod
  open func isShowingLayoutBounds() -> Bool

  @JavaMethod
  open func saveAttributeDataForStyleable(_ arg0: Context?, _ arg1: [Int32], _ arg2: AttributeSet?, _ arg3: TypedArray?, _ arg4: Int32, _ arg5: Int32)

  @JavaMethod
  open func getVerticalFadingEdgeLength() -> Int32

  @JavaMethod
  open func setFadingEdgeLength(_ arg0: Int32)

  @JavaMethod
  open func getHorizontalFadingEdgeLength() -> Int32

  @JavaMethod
  open func getVerticalScrollbarWidth() -> Int32

  @JavaMethod
  open func getHorizontalScrollbarHeight() -> Int32

  @JavaMethod
  open func setVerticalScrollbarThumbDrawable(_ arg0: Drawable?)

  @JavaMethod
  open func setVerticalScrollbarTrackDrawable(_ arg0: Drawable?)

  @JavaMethod
  open func setHorizontalScrollbarThumbDrawable(_ arg0: Drawable?)

  @JavaMethod
  open func setHorizontalScrollbarTrackDrawable(_ arg0: Drawable?)

  @JavaMethod
  open func getVerticalScrollbarThumbDrawable() -> Drawable!

  @JavaMethod
  open func getVerticalScrollbarTrackDrawable() -> Drawable!

  @JavaMethod
  open func getHorizontalScrollbarThumbDrawable() -> Drawable!

  @JavaMethod
  open func getHorizontalScrollbarTrackDrawable() -> Drawable!

  @JavaMethod
  open func setVerticalScrollbarPosition(_ arg0: Int32)

  @JavaMethod
  open func getVerticalScrollbarPosition() -> Int32

  @JavaMethod
  open func setScrollIndicators(_ arg0: Int32, _ arg1: Int32)

  @JavaMethod
  open func setScrollIndicators(_ arg0: Int32)

  @JavaMethod
  open func getScrollIndicators() -> Int32

  @JavaMethod
  open func setOnScrollChangeListener(_ arg0: View.OnScrollChangeListener?)

  @JavaMethod
  open func setOnFocusChangeListener(_ arg0: View.OnFocusChangeListener?)

  @JavaMethod
  open func addOnLayoutChangeListener(_ arg0: View.OnLayoutChangeListener?)

  @JavaMethod
  open func removeOnLayoutChangeListener(_ arg0: View.OnLayoutChangeListener?)

  @JavaMethod
  open func addOnAttachStateChangeListener(_ arg0: View.OnAttachStateChangeListener?)

  @JavaMethod
  open func removeOnAttachStateChangeListener(_ arg0: View.OnAttachStateChangeListener?)

  @JavaMethod
  open func getOnFocusChangeListener() -> View.OnFocusChangeListener!

  @JavaMethod
  open func setOnClickListener(_ arg0: View.OnClickListener?)

  @JavaMethod
  open func hasOnClickListeners() -> Bool

  @JavaMethod
  open func setOnLongClickListener(_ arg0: View.OnLongClickListener?)

  @JavaMethod
  open func hasOnLongClickListeners() -> Bool

  @JavaMethod
  open func setOnContextClickListener(_ arg0: View.OnContextClickListener?)

  @JavaMethod
  open func setOnCreateContextMenuListener(_ arg0: View.OnCreateContextMenuListener?)

  @JavaMethod
  open func performClick() -> Bool

  @JavaMethod
  open func callOnClick() -> Bool

  @JavaMethod
  open func performLongClick(_ arg0: Float, _ arg1: Float) -> Bool

  @JavaMethod
  open func performLongClick() -> Bool

  @JavaMethod
  open func performContextClick(_ arg0: Float, _ arg1: Float) -> Bool

  @JavaMethod
  open func performContextClick() -> Bool

  @JavaMethod
  open func showContextMenu() -> Bool

  @JavaMethod
  open func showContextMenu(_ arg0: Float, _ arg1: Float) -> Bool

  @JavaMethod
  open func startActionMode(_ arg0: ActionMode.Callback?, _ arg1: Int32) -> ActionMode!

  @JavaMethod
  open func startActionMode(_ arg0: ActionMode.Callback?) -> ActionMode!

  @JavaMethod
  open func setOnKeyListener(_ arg0: View.OnKeyListener?)

  @JavaMethod
  open func setOnTouchListener(_ arg0: View.OnTouchListener?)

  @JavaMethod
  open func setOnGenericMotionListener(_ arg0: View.OnGenericMotionListener?)

  @JavaMethod
  open func setOnHoverListener(_ arg0: View.OnHoverListener?)

  @JavaMethod
  open func setOnDragListener(_ arg0: View.OnDragListener?)

  @JavaMethod
  open func setRevealOnFocusHint(_ arg0: Bool)

  @JavaMethod
  open func getRevealOnFocusHint() -> Bool

  @JavaMethod
  open func requestRectangleOnScreen(_ arg0: Rect?, _ arg1: Bool) -> Bool

  @JavaMethod
  open func requestRectangleOnScreen(_ arg0: Rect?) -> Bool

  @JavaMethod
  open func clearFocus()

  @JavaMethod
  open func hasFocus() -> Bool

  @JavaMethod
  open func hasFocusable() -> Bool

  @JavaMethod
  open func hasExplicitFocusable() -> Bool

  @JavaMethod
  open func onFocusChanged(_ arg0: Bool, _ arg1: Int32, _ arg2: Rect?)

  @JavaMethod
  open func setAccessibilityPaneTitle(_ arg0: CharSequence?)

  @JavaMethod
  open func getAccessibilityPaneTitle() -> CharSequence!

  @JavaMethod
  open func sendAccessibilityEvent(_ arg0: Int32)

  @JavaMethod
  open func announceForAccessibility(_ arg0: CharSequence?)

  @JavaMethod
  open func getAccessibilityClassName() -> CharSequence!

  @JavaMethod
  open func onProvideStructure(_ arg0: ViewStructure?)

  @JavaMethod
  open func onProvideAutofillStructure(_ arg0: ViewStructure?, _ arg1: Int32)

  @JavaMethod
  open func onProvideContentCaptureStructure(_ arg0: ViewStructure?, _ arg1: Int32)

  @JavaMethod
  open func onProvideVirtualStructure(_ arg0: ViewStructure?)

  @JavaMethod
  open func onProvideAutofillVirtualStructure(_ arg0: ViewStructure?, _ arg1: Int32)

  @JavaMethod
  open func setOnReceiveContentListener(_ arg0: [String], _ arg1: OnReceiveContentListener?)

  @JavaMethod
  open func performReceiveContent(_ arg0: ContentInfo?) -> ContentInfo!

  @JavaMethod
  open func onReceiveContent(_ arg0: ContentInfo?) -> ContentInfo!

  @JavaMethod
  open func getReceiveContentMimeTypes() -> [String]

  @JavaMethod
  open func autofill(_ arg0: AutofillValue?)

  @JavaMethod
  open func autofill(_ arg0: SparseArray<AutofillValue>?)

  @JavaMethod
  open func getAutofillId() -> AutofillId!

  @JavaMethod
  open func setAutofillId(_ arg0: AutofillId?)

  @JavaMethod
  open func getAutofillType() -> Int32

  @JavaMethod
  open func getAutofillHints() -> [String]

  @JavaMethod
  open func getAutofillValue() -> AutofillValue!

  @JavaMethod
  open func getImportantForAutofill() -> Int32

  @JavaMethod
  open func setImportantForAutofill(_ arg0: Int32)

  @JavaMethod
  open func isImportantForAutofill() -> Bool

  @JavaMethod
  open func getImportantForContentCapture() -> Int32

  @JavaMethod
  open func setImportantForContentCapture(_ arg0: Int32)

  @JavaMethod
  open func isImportantForContentCapture() -> Bool

  @JavaMethod
  open func dispatchProvideStructure(_ arg0: ViewStructure?)

  @JavaMethod
  open func dispatchProvideAutofillStructure(_ arg0: ViewStructure?, _ arg1: Int32)

  @JavaMethod
  open func isVisibleToUserForAutofill(_ arg0: Int32) -> Bool

  @JavaMethod
  open func getAccessibilityDelegate() -> View.AccessibilityDelegate!

  @JavaMethod
  open func setAccessibilityDelegate(_ arg0: View.AccessibilityDelegate?)

  @JavaMethod
  open func getStateDescription() -> CharSequence!

  @JavaMethod
  open func getContentDescription() -> CharSequence!

  @JavaMethod
  open func setStateDescription(_ arg0: CharSequence?)

  @JavaMethod
  open func setContentDescription(_ arg0: CharSequence?)

  @JavaMethod
  open func setAccessibilityTraversalBefore(_ arg0: Int32)

  @JavaMethod
  open func getAccessibilityTraversalBefore() -> Int32

  @JavaMethod
  open func setAccessibilityTraversalAfter(_ arg0: Int32)

  @JavaMethod
  open func getAccessibilityTraversalAfter() -> Int32

  @JavaMethod
  open func getLabelFor() -> Int32

  @JavaMethod
  open func setLabelFor(_ arg0: Int32)

  @JavaMethod
  open func isFocused() -> Bool

  @JavaMethod
  open func findFocus() -> View!

  @JavaMethod
  open func isScrollContainer() -> Bool

  @JavaMethod
  open func setScrollContainer(_ arg0: Bool)

  @JavaMethod
  open func getDrawingCacheQuality() -> Int32

  @JavaMethod
  open func setDrawingCacheQuality(_ arg0: Int32)

  @JavaMethod
  open func getKeepScreenOn() -> Bool

  @JavaMethod
  open func setKeepScreenOn(_ arg0: Bool)

  @JavaMethod
  open func getNextFocusLeftId() -> Int32

  @JavaMethod
  open func setNextFocusLeftId(_ arg0: Int32)

  @JavaMethod
  open func getNextFocusRightId() -> Int32

  @JavaMethod
  open func setNextFocusRightId(_ arg0: Int32)

  @JavaMethod
  open func getNextFocusUpId() -> Int32

  @JavaMethod
  open func setNextFocusUpId(_ arg0: Int32)

  @JavaMethod
  open func getNextFocusDownId() -> Int32

  @JavaMethod
  open func setNextFocusDownId(_ arg0: Int32)

  @JavaMethod
  open func getNextFocusForwardId() -> Int32

  @JavaMethod
  open func setNextFocusForwardId(_ arg0: Int32)

  @JavaMethod
  open func getNextClusterForwardId() -> Int32

  @JavaMethod
  open func setNextClusterForwardId(_ arg0: Int32)

  @JavaMethod
  open func isShown() -> Bool

  @JavaMethod
  open func fitSystemWindows(_ arg0: Rect?) -> Bool

  @JavaMethod
  open func onApplyWindowInsets(_ arg0: WindowInsets?) -> WindowInsets!

  @JavaMethod
  open func setOnApplyWindowInsetsListener(_ arg0: View.OnApplyWindowInsetsListener?)

  @JavaMethod
  open func dispatchApplyWindowInsets(_ arg0: WindowInsets?) -> WindowInsets!

  @JavaMethod
  open func setWindowInsetsAnimationCallback(_ arg0: WindowInsetsAnimation.Callback?)

  @JavaMethod
  open func dispatchWindowInsetsAnimationPrepare(_ arg0: WindowInsetsAnimation?)

  @JavaMethod
  open func dispatchWindowInsetsAnimationStart(_ arg0: WindowInsetsAnimation?, _ arg1: WindowInsetsAnimation.Bounds?) -> WindowInsetsAnimation.Bounds!

  @JavaMethod
  open func dispatchWindowInsetsAnimationProgress(_ arg0: WindowInsets?, _ arg1: List<WindowInsetsAnimation>?) -> WindowInsets!

  @JavaMethod
  open func dispatchWindowInsetsAnimationEnd(_ arg0: WindowInsetsAnimation?)

  @JavaMethod
  open func setSystemGestureExclusionRects(_ arg0: List<Rect>?)

  @JavaMethod
  open func getSystemGestureExclusionRects() -> List<Rect>!

  @JavaMethod
  open func setPreferKeepClear(_ arg0: Bool)

  @JavaMethod
  open func isPreferKeepClear() -> Bool

  @JavaMethod
  open func setPreferKeepClearRects(_ arg0: List<Rect>?)

  @JavaMethod
  open func getPreferKeepClearRects() -> List<Rect>!

  @JavaMethod
  open func getLocationInSurface(_ arg0: [Int32])

  @JavaMethod
  open func getRootWindowInsets() -> WindowInsets!

  @JavaMethod
  open func getWindowInsetsController() -> WindowInsetsController!

  @JavaMethod
  open func computeSystemWindowInsets(_ arg0: WindowInsets?, _ arg1: Rect?) -> WindowInsets!

  @JavaMethod
  open func setFitsSystemWindows(_ arg0: Bool)

  @JavaMethod
  open func getFitsSystemWindows() -> Bool

  @JavaMethod
  open func requestFitSystemWindows()

  @JavaMethod
  open func requestApplyInsets()

  @JavaMethod
  open func getVisibility() -> Int32

  @JavaMethod
  open func setEnabled(_ arg0: Bool)

  @JavaMethod
  open func setFocusable(_ arg0: Bool)

  @JavaMethod
  open func setFocusable(_ arg0: Int32)

  @JavaMethod
  open func setFocusableInTouchMode(_ arg0: Bool)

  @JavaMethod
  open func setAutofillHints(_ arg0: [String])

  @JavaMethod
  open func setSoundEffectsEnabled(_ arg0: Bool)

  @JavaMethod
  open func isSoundEffectsEnabled() -> Bool

  @JavaMethod
  open func setHapticFeedbackEnabled(_ arg0: Bool)

  @JavaMethod
  open func isHapticFeedbackEnabled() -> Bool

  @JavaMethod
  open func setLayoutDirection(_ arg0: Int32)

  @JavaMethod
  open func getLayoutDirection() -> Int32

  @JavaMethod
  open func layout(_ arg0: Int32, _ arg1: Int32, _ arg2: Int32, _ arg3: Int32)

  @JavaMethod
  open func hasTransientState() -> Bool

  @JavaMethod
  open func setHasTransientState(_ arg0: Bool)

  @JavaMethod
  open func isAttachedToWindow() -> Bool

  @JavaMethod
  open func isLaidOut() -> Bool

  @JavaMethod
  open func setWillNotDraw(_ arg0: Bool)

  @JavaMethod
  open func willNotDraw() -> Bool

  @JavaMethod
  open func setWillNotCacheDrawing(_ arg0: Bool)

  @JavaMethod
  open func willNotCacheDrawing() -> Bool

  @JavaMethod
  open func isClickable() -> Bool

  @JavaMethod
  open func setClickable(_ arg0: Bool)

  @JavaMethod
  open func setAllowClickWhenDisabled(_ arg0: Bool)

  @JavaMethod
  open func isLongClickable() -> Bool

  @JavaMethod
  open func setLongClickable(_ arg0: Bool)

  @JavaMethod
  open func isContextClickable() -> Bool

  @JavaMethod
  open func setContextClickable(_ arg0: Bool)

  @JavaMethod
  open func setPressed(_ arg0: Bool)

  @JavaMethod
  open func dispatchSetPressed(_ arg0: Bool)

  @JavaMethod
  open func isPressed() -> Bool

  @JavaMethod
  open func isSaveEnabled() -> Bool

  @JavaMethod
  open func setSaveEnabled(_ arg0: Bool)

  @JavaMethod
  open func getFilterTouchesWhenObscured() -> Bool

  @JavaMethod
  open func setFilterTouchesWhenObscured(_ arg0: Bool)

  @JavaMethod
  open func isSaveFromParentEnabled() -> Bool

  @JavaMethod
  open func setSaveFromParentEnabled(_ arg0: Bool)

  @JavaMethod
  open func isFocusable() -> Bool

  @JavaMethod
  open func getFocusable() -> Int32

  @JavaMethod
  open func isFocusableInTouchMode() -> Bool

  @JavaMethod
  open func isScreenReaderFocusable() -> Bool

  @JavaMethod
  open func setScreenReaderFocusable(_ arg0: Bool)

  @JavaMethod
  open func isAccessibilityHeading() -> Bool

  @JavaMethod
  open func setAccessibilityHeading(_ arg0: Bool)

  @JavaMethod
  open func focusSearch(_ arg0: Int32) -> View!

  @JavaMethod
  open func isKeyboardNavigationCluster() -> Bool

  @JavaMethod
  open func setKeyboardNavigationCluster(_ arg0: Bool)

  @JavaMethod
  open func isFocusedByDefault() -> Bool

  @JavaMethod
  open func setFocusedByDefault(_ arg0: Bool)

  @JavaMethod
  open func keyboardNavigationClusterSearch(_ arg0: View?, _ arg1: Int32) -> View!

  @JavaMethod
  open func dispatchUnhandledMove(_ arg0: View?, _ arg1: Int32) -> Bool

  @JavaMethod
  open func setDefaultFocusHighlightEnabled(_ arg0: Bool)

  @JavaMethod
  open func getDefaultFocusHighlightEnabled() -> Bool

  @JavaMethod
  open func getFocusables(_ arg0: Int32) -> ArrayList<View>!

  @JavaMethod
  open func addFocusables(_ arg0: ArrayList<View>?, _ arg1: Int32)

  @JavaMethod
  open func addFocusables(_ arg0: ArrayList<View>?, _ arg1: Int32, _ arg2: Int32)

  @JavaMethod
  open func addKeyboardNavigationClusters(_ arg0: JavaCollection<View>?, _ arg1: Int32)

  @JavaMethod
  open func findViewsWithText(_ arg0: ArrayList<View>?, _ arg1: CharSequence?, _ arg2: Int32)

  @JavaMethod
  open func getTouchables() -> ArrayList<View>!

  @JavaMethod
  open func addTouchables(_ arg0: ArrayList<View>?)

  @JavaMethod
  open func isAccessibilityFocused() -> Bool

  @JavaMethod
  open func requestFocus(_ arg0: Int32, _ arg1: Rect?) -> Bool

  @JavaMethod
  open func requestFocus(_ arg0: Int32) -> Bool

  @JavaMethod
  open func requestFocus() -> Bool

  @JavaMethod
  open func restoreDefaultFocus() -> Bool

  @JavaMethod
  open func requestFocusFromTouch() -> Bool

  @JavaMethod
  open func getImportantForAccessibility() -> Int32

  @JavaMethod
  open func setAccessibilityLiveRegion(_ arg0: Int32)

  @JavaMethod
  open func getAccessibilityLiveRegion() -> Int32

  @JavaMethod
  open func setImportantForAccessibility(_ arg0: Int32)

  @JavaMethod
  open func isImportantForAccessibility() -> Bool

  @JavaMethod
  open func getParentForAccessibility() -> ViewParent!

  @JavaMethod
  open func addChildrenForAccessibility(_ arg0: ArrayList<View>?)

  @JavaMethod
  open func setTransitionVisibility(_ arg0: Int32)

  @JavaMethod
  open func dispatchNestedPrePerformAccessibilityAction(_ arg0: Int32, _ arg1: Bundle?) -> Bool

  @JavaMethod
  open func performAccessibilityAction(_ arg0: Int32, _ arg1: Bundle?) -> Bool

  @JavaMethod
  open func isTemporarilyDetached() -> Bool

  @JavaMethod
  open func dispatchStartTemporaryDetach()

  @JavaMethod
  open func onStartTemporaryDetach()

  @JavaMethod
  open func dispatchFinishTemporaryDetach()

  @JavaMethod
  open func onFinishTemporaryDetach()

  @JavaMethod
  open func getKeyDispatcherState() -> KeyEvent.DispatcherState!

  @JavaMethod
  open func dispatchKeyEventPreIme(_ arg0: KeyEvent?) -> Bool

  @JavaMethod
  open func dispatchKeyEvent(_ arg0: KeyEvent?) -> Bool

  @JavaMethod
  open func dispatchKeyShortcutEvent(_ arg0: KeyEvent?) -> Bool

  @JavaMethod
  open func dispatchTouchEvent(_ arg0: MotionEvent?) -> Bool

  @JavaMethod
  open func onFilterTouchEventForSecurity(_ arg0: MotionEvent?) -> Bool

  @JavaMethod
  open func dispatchTrackballEvent(_ arg0: MotionEvent?) -> Bool

  @JavaMethod
  open func dispatchCapturedPointerEvent(_ arg0: MotionEvent?) -> Bool

  @JavaMethod
  open func dispatchGenericMotionEvent(_ arg0: MotionEvent?) -> Bool

  @JavaMethod
  open func dispatchHoverEvent(_ arg0: MotionEvent?) -> Bool

  @JavaMethod
  open func dispatchGenericPointerEvent(_ arg0: MotionEvent?) -> Bool

  @JavaMethod
  open func dispatchGenericFocusedEvent(_ arg0: MotionEvent?) -> Bool

  @JavaMethod
  open func dispatchWindowFocusChanged(_ arg0: Bool)

  @JavaMethod
  open func onWindowFocusChanged(_ arg0: Bool)

  @JavaMethod
  open func hasWindowFocus() -> Bool

  @JavaMethod
  open func dispatchVisibilityChanged(_ arg0: View?, _ arg1: Int32)

  @JavaMethod
  open func onVisibilityChanged(_ arg0: View?, _ arg1: Int32)

  @JavaMethod
  open func dispatchDisplayHint(_ arg0: Int32)

  @JavaMethod
  open func onDisplayHint(_ arg0: Int32)

  @JavaMethod
  open func dispatchWindowVisibilityChanged(_ arg0: Int32)

  @JavaMethod
  open func onWindowVisibilityChanged(_ arg0: Int32)

  @JavaMethod
  open func onVisibilityAggregated(_ arg0: Bool)

  @JavaMethod
  open func getWindowVisibility() -> Int32

  @JavaMethod
  open func getWindowVisibleDisplayFrame(_ arg0: Rect?)

  @JavaMethod
  open func dispatchConfigurationChanged(_ arg0: Configuration?)

  @JavaMethod
  open func onConfigurationChanged(_ arg0: Configuration?)

  @JavaMethod
  open func isInTouchMode() -> Bool

  @JavaMethod
  open func onKeyPreIme(_ arg0: Int32, _ arg1: KeyEvent?) -> Bool

  @JavaMethod
  open func onKeyDown(_ arg0: Int32, _ arg1: KeyEvent?) -> Bool

  @JavaMethod
  open func onKeyLongPress(_ arg0: Int32, _ arg1: KeyEvent?) -> Bool

  @JavaMethod
  open func onKeyUp(_ arg0: Int32, _ arg1: KeyEvent?) -> Bool

  @JavaMethod
  open func onKeyMultiple(_ arg0: Int32, _ arg1: Int32, _ arg2: KeyEvent?) -> Bool

  @JavaMethod
  open func onKeyShortcut(_ arg0: Int32, _ arg1: KeyEvent?) -> Bool

  @JavaMethod
  open func onCheckIsTextEditor() -> Bool

  @JavaMethod
  open func checkInputConnectionProxy(_ arg0: View?) -> Bool

  @JavaMethod
  open func createContextMenu(_ arg0: ContextMenu?)

  @JavaMethod
  open func getContextMenuInfo() -> ContextMenu.ContextMenuInfo!

  @JavaMethod
  open func onCreateContextMenu(_ arg0: ContextMenu?)

  @JavaMethod
  open func onTrackballEvent(_ arg0: MotionEvent?) -> Bool

  @JavaMethod
  open func onGenericMotionEvent(_ arg0: MotionEvent?) -> Bool

  @JavaMethod
  open func onHoverEvent(_ arg0: MotionEvent?) -> Bool

  @JavaMethod
  open func isHovered() -> Bool

  @JavaMethod
  open func setHovered(_ arg0: Bool)

  @JavaMethod
  open func onHoverChanged(_ arg0: Bool)

  @JavaMethod
  open func onTouchEvent(_ arg0: MotionEvent?) -> Bool

  @JavaMethod
  open func cancelLongPress()

  @JavaMethod
  open func setTouchDelegate(_ arg0: TouchDelegate?)

  @JavaMethod
  open func getTouchDelegate() -> TouchDelegate!

  @JavaMethod
  open func requestUnbufferedDispatch(_ arg0: MotionEvent?)

  @JavaMethod
  open func requestUnbufferedDispatch(_ arg0: Int32)

  @JavaMethod
  open func bringToFront()

  @JavaMethod
  open func onScrollChanged(_ arg0: Int32, _ arg1: Int32, _ arg2: Int32, _ arg3: Int32)

  @JavaMethod
  open func onSizeChanged(_ arg0: Int32, _ arg1: Int32, _ arg2: Int32, _ arg3: Int32)

  @JavaMethod
  open func setScrollX(_ arg0: Int32)

  @JavaMethod
  open func setScrollY(_ arg0: Int32)

  @JavaMethod
  open func getScrollX() -> Int32

  @JavaMethod
  open func getScrollY() -> Int32

  @JavaMethod
  open func getDrawingRect(_ arg0: Rect?)

  @JavaMethod
  open func getMeasuredWidth() -> Int32

  @JavaMethod
  open func getMeasuredWidthAndState() -> Int32

  @JavaMethod
  open func getMeasuredHeight() -> Int32

  @JavaMethod
  open func getMeasuredHeightAndState() -> Int32

  @JavaMethod
  open func getMeasuredState() -> Int32

  @JavaMethod
  open func getMatrix() -> Matrix!

  @JavaMethod
  open func getCameraDistance() -> Float

  @JavaMethod
  open func setCameraDistance(_ arg0: Float)

  @JavaMethod
  open func setRotation(_ arg0: Float)

  @JavaMethod
  open func getRotationY() -> Float

  @JavaMethod
  open func setRotationY(_ arg0: Float)

  @JavaMethod
  open func getRotationX() -> Float

  @JavaMethod
  open func setRotationX(_ arg0: Float)

  @JavaMethod
  open func getScaleX() -> Float

  @JavaMethod
  open func setScaleX(_ arg0: Float)

  @JavaMethod
  open func getScaleY() -> Float

  @JavaMethod
  open func setScaleY(_ arg0: Float)

  @JavaMethod
  open func getPivotX() -> Float

  @JavaMethod
  open func setPivotX(_ arg0: Float)

  @JavaMethod
  open func getPivotY() -> Float

  @JavaMethod
  open func setPivotY(_ arg0: Float)

  @JavaMethod
  open func isPivotSet() -> Bool

  @JavaMethod
  open func resetPivot()

  @JavaMethod
  open func getAlpha() -> Float

  @JavaMethod
  open func forceHasOverlappingRendering(_ arg0: Bool)

  @JavaMethod
  open func hasOverlappingRendering() -> Bool

  @JavaMethod
  open func getHasOverlappingRendering() -> Bool

  @JavaMethod
  open func setAlpha(_ arg0: Float)

  @JavaMethod
  open func setTransitionAlpha(_ arg0: Float)

  @JavaMethod
  open func getTransitionAlpha() -> Float

  @JavaMethod
  open func setForceDarkAllowed(_ arg0: Bool)

  @JavaMethod
  open func isForceDarkAllowed() -> Bool

  @JavaMethod
  open func getTop() -> Int32

  @JavaMethod
  open func setTop(_ arg0: Int32)

  @JavaMethod
  open func getBottom() -> Int32

  @JavaMethod
  open func setBottom(_ arg0: Int32)

  @JavaMethod
  open func getLeft() -> Int32

  @JavaMethod
  open func setLeft(_ arg0: Int32)

  @JavaMethod
  open func getRight() -> Int32

  @JavaMethod
  open func setRight(_ arg0: Int32)

  @JavaMethod
  open func getX() -> Float

  @JavaMethod
  open func setX(_ arg0: Float)

  @JavaMethod
  open func getY() -> Float

  @JavaMethod
  open func setY(_ arg0: Float)

  @JavaMethod
  open func getZ() -> Float

  @JavaMethod
  open func setZ(_ arg0: Float)

  @JavaMethod
  open func getElevation() -> Float

  @JavaMethod
  open func setElevation(_ arg0: Float)

  @JavaMethod
  open func getTranslationX() -> Float

  @JavaMethod
  open func setTranslationX(_ arg0: Float)

  @JavaMethod
  open func getTranslationY() -> Float

  @JavaMethod
  open func setTranslationY(_ arg0: Float)

  @JavaMethod
  open func getTranslationZ() -> Float

  @JavaMethod
  open func setTranslationZ(_ arg0: Float)

  @JavaMethod
  open func setAnimationMatrix(_ arg0: Matrix?)

  @JavaMethod
  open func getAnimationMatrix() -> Matrix!

  @JavaMethod
  open func getClipToOutline() -> Bool

  @JavaMethod
  open func setClipToOutline(_ arg0: Bool)

  @JavaMethod
  open func setOutlineProvider(_ arg0: ViewOutlineProvider?)

  @JavaMethod
  open func getOutlineProvider() -> ViewOutlineProvider!

  @JavaMethod
  open func invalidateOutline()

  @JavaMethod
  open func setOutlineSpotShadowColor(_ arg0: Int32)

  @JavaMethod
  open func getOutlineSpotShadowColor() -> Int32

  @JavaMethod
  open func setOutlineAmbientShadowColor(_ arg0: Int32)

  @JavaMethod
  open func getOutlineAmbientShadowColor() -> Int32

  @JavaMethod
  open func getHitRect(_ arg0: Rect?)

  @JavaMethod
  open func getFocusedRect(_ arg0: Rect?)

  @JavaMethod
  open func getGlobalVisibleRect(_ arg0: Rect?, _ arg1: Point?) -> Bool

  @JavaMethod
  open func getGlobalVisibleRect(_ arg0: Rect?) -> Bool

  @JavaMethod
  open func getLocalVisibleRect(_ arg0: Rect?) -> Bool

  @JavaMethod
  open func offsetTopAndBottom(_ arg0: Int32)

  @JavaMethod
  open func offsetLeftAndRight(_ arg0: Int32)

  @JavaMethod
  open func getLayoutParams() -> ViewGroup.LayoutParams!

  @JavaMethod
  open func setLayoutParams(_ arg0: ViewGroup.LayoutParams?)

  @JavaMethod
  open func scrollTo(_ arg0: Int32, _ arg1: Int32)

  @JavaMethod
  open func scrollBy(_ arg0: Int32, _ arg1: Int32)

  @JavaMethod
  open func awakenScrollBars(_ arg0: Int32) -> Bool

  @JavaMethod
  open func awakenScrollBars(_ arg0: Int32, _ arg1: Bool) -> Bool

  @JavaMethod
  open func awakenScrollBars() -> Bool

  @JavaMethod
  open func invalidate()

  @JavaMethod
  open func invalidate(_ arg0: Int32, _ arg1: Int32, _ arg2: Int32, _ arg3: Int32)

  @JavaMethod
  open func invalidate(_ arg0: Rect?)

  @JavaMethod
  open func postDelayed(_ arg0: Runnable?, _ arg1: Int64) -> Bool

  @JavaMethod
  open func postOnAnimation(_ arg0: Runnable?)

  @JavaMethod
  open func postOnAnimationDelayed(_ arg0: Runnable?, _ arg1: Int64)

  @JavaMethod
  open func removeCallbacks(_ arg0: Runnable?) -> Bool

  @JavaMethod
  open func postInvalidate(_ arg0: Int32, _ arg1: Int32, _ arg2: Int32, _ arg3: Int32)

  @JavaMethod
  open func postInvalidate()

  @JavaMethod
  open func postInvalidateDelayed(_ arg0: Int64)

  @JavaMethod
  open func postInvalidateDelayed(_ arg0: Int64, _ arg1: Int32, _ arg2: Int32, _ arg3: Int32, _ arg4: Int32)

  @JavaMethod
  open func postInvalidateOnAnimation(_ arg0: Int32, _ arg1: Int32, _ arg2: Int32, _ arg3: Int32)

  @JavaMethod
  open func postInvalidateOnAnimation()

  @JavaMethod
  open func computeScroll()

  @JavaMethod
  open func isHorizontalFadingEdgeEnabled() -> Bool

  @JavaMethod
  open func setHorizontalFadingEdgeEnabled(_ arg0: Bool)

  @JavaMethod
  open func isVerticalFadingEdgeEnabled() -> Bool

  @JavaMethod
  open func setVerticalFadingEdgeEnabled(_ arg0: Bool)

  @JavaMethod
  open func getTopFadingEdgeStrength() -> Float

  @JavaMethod
  open func getBottomFadingEdgeStrength() -> Float

  @JavaMethod
  open func getLeftFadingEdgeStrength() -> Float

  @JavaMethod
  open func getRightFadingEdgeStrength() -> Float

  @JavaMethod
  open func isHorizontalScrollBarEnabled() -> Bool

  @JavaMethod
  open func setHorizontalScrollBarEnabled(_ arg0: Bool)

  @JavaMethod
  open func isVerticalScrollBarEnabled() -> Bool

  @JavaMethod
  open func setVerticalScrollBarEnabled(_ arg0: Bool)

  @JavaMethod
  open func setScrollbarFadingEnabled(_ arg0: Bool)

  @JavaMethod
  open func isScrollbarFadingEnabled() -> Bool

  @JavaMethod
  open func getScrollBarDefaultDelayBeforeFade() -> Int32

  @JavaMethod
  open func setScrollBarDefaultDelayBeforeFade(_ arg0: Int32)

  @JavaMethod
  open func setScrollBarFadeDuration(_ arg0: Int32)

  @JavaMethod
  open func setScrollBarSize(_ arg0: Int32)

  @JavaMethod
  open func setScrollBarStyle(_ arg0: Int32)

  @JavaMethod
  open func getScrollBarStyle() -> Int32

  @JavaMethod
  open func computeHorizontalScrollRange() -> Int32

  @JavaMethod
  open func computeHorizontalScrollOffset() -> Int32

  @JavaMethod
  open func computeHorizontalScrollExtent() -> Int32

  @JavaMethod
  open func computeVerticalScrollRange() -> Int32

  @JavaMethod
  open func computeVerticalScrollOffset() -> Int32

  @JavaMethod
  open func computeVerticalScrollExtent() -> Int32

  @JavaMethod
  open func canScrollHorizontally(_ arg0: Int32) -> Bool

  @JavaMethod
  open func canScrollVertically(_ arg0: Int32) -> Bool

  @JavaMethod
  open func onDrawScrollBars(_ arg0: Canvas?)

  @JavaMethod
  open func onAttachedToWindow()

  @JavaMethod
  open func onScreenStateChanged(_ arg0: Int32)

  @JavaMethod
  open func onRtlPropertiesChanged(_ arg0: Int32)

  @JavaMethod
  open func canResolveLayoutDirection() -> Bool

  @JavaMethod
  open func isLayoutDirectionResolved() -> Bool

  @JavaMethod
  open func onDetachedFromWindow()

  @JavaMethod
  open func getWindowAttachCount() -> Int32

  @JavaMethod
  open func getWindowToken() -> IBinder!

  @JavaMethod
  open func getWindowId() -> WindowId!

  @JavaMethod
  open func getApplicationWindowToken() -> IBinder!

  @JavaMethod
  open func getDisplay() -> Display!

  @JavaMethod
  open func cancelPendingInputEvents()

  @JavaMethod
  open func onCancelPendingInputEvents()

  @JavaMethod
  open func saveHierarchyState(_ arg0: SparseArray<Parcelable>?)

  @JavaMethod
  open func dispatchSaveInstanceState(_ arg0: SparseArray<Parcelable>?)

  @JavaMethod
  open func onSaveInstanceState() -> Parcelable!

  @JavaMethod
  open func restoreHierarchyState(_ arg0: SparseArray<Parcelable>?)

  @JavaMethod
  open func dispatchRestoreInstanceState(_ arg0: SparseArray<Parcelable>?)

  @JavaMethod
  open func onRestoreInstanceState(_ arg0: Parcelable?)

  @JavaMethod
  open func getDrawingTime() -> Int64

  @JavaMethod
  open func setDuplicateParentStateEnabled(_ arg0: Bool)

  @JavaMethod
  open func isDuplicateParentStateEnabled() -> Bool

  @JavaMethod
  open func setLayerType(_ arg0: Int32, _ arg1: Paint?)

  @JavaMethod
  open func setRenderEffect(_ arg0: RenderEffect?)

  @JavaMethod
  open func setLayerPaint(_ arg0: Paint?)

  @JavaMethod
  open func getLayerType() -> Int32

  @JavaMethod
  open func buildLayer()

  @JavaMethod
  open func setDrawingCacheEnabled(_ arg0: Bool)

  @JavaMethod
  open func isDrawingCacheEnabled() -> Bool

  @JavaMethod
  open func getDrawingCache() -> Bitmap!

  @JavaMethod
  open func getDrawingCache(_ arg0: Bool) -> Bitmap!

  @JavaMethod
  open func destroyDrawingCache()

  @JavaMethod
  open func setDrawingCacheBackgroundColor(_ arg0: Int32)

  @JavaMethod
  open func getDrawingCacheBackgroundColor() -> Int32

  @JavaMethod
  open func buildDrawingCache(_ arg0: Bool)

  @JavaMethod
  open func buildDrawingCache()

  @JavaMethod
  open func isInEditMode() -> Bool

  @JavaMethod
  open func isPaddingOffsetRequired() -> Bool

  @JavaMethod
  open func getLeftPaddingOffset() -> Int32

  @JavaMethod
  open func getRightPaddingOffset() -> Int32

  @JavaMethod
  open func getTopPaddingOffset() -> Int32

  @JavaMethod
  open func getBottomPaddingOffset() -> Int32

  @JavaMethod
  open func isHardwareAccelerated() -> Bool

  @JavaMethod
  open func setClipBounds(_ arg0: Rect?)

  @JavaMethod
  open func getClipBounds(_ arg0: Rect?) -> Bool

  @JavaMethod
  open func getClipBounds() -> Rect!

  @JavaMethod
  open func getOverlay() -> ViewOverlay!

  @JavaMethod
  open func getSolidColor() -> Int32

  @JavaMethod
  open func isLayoutRequested() -> Bool

  @JavaMethod
  open func onLayout(_ arg0: Bool, _ arg1: Int32, _ arg2: Int32, _ arg3: Int32, _ arg4: Int32)

  @JavaMethod
  open func setLeftTopRightBottom(_ arg0: Int32, _ arg1: Int32, _ arg2: Int32, _ arg3: Int32)

  @JavaMethod
  open func onFinishInflate()

  @JavaMethod
  open func invalidateDrawable(_ arg0: Drawable?)

  @JavaMethod
  open func scheduleDrawable(_ arg0: Drawable?, _ arg1: Runnable?, _ arg2: Int64)

  @JavaMethod
  open func unscheduleDrawable(_ arg0: Drawable?)

  @JavaMethod
  open func unscheduleDrawable(_ arg0: Drawable?, _ arg1: Runnable?)

  @JavaMethod
  open func verifyDrawable(_ arg0: Drawable?) -> Bool

  @JavaMethod
  open func drawableStateChanged()

  @JavaMethod
  open func drawableHotspotChanged(_ arg0: Float, _ arg1: Float)

  @JavaMethod
  open func dispatchDrawableHotspotChanged(_ arg0: Float, _ arg1: Float)

  @JavaMethod
  open func refreshDrawableState()

  @JavaMethod
  open func getDrawableState() -> [Int32]

  @JavaMethod
  open func onCreateDrawableState(_ arg0: Int32) -> [Int32]

  @JavaMethod
  open func jumpDrawablesToCurrentState()

  @JavaMethod
  open func setBackgroundResource(_ arg0: Int32)

  @JavaMethod
  open func setBackground(_ arg0: Drawable?)

  @JavaMethod
  open func setBackgroundDrawable(_ arg0: Drawable?)

  @JavaMethod
  open func getBackground() -> Drawable!

  @JavaMethod
  open func setBackgroundTintList(_ arg0: ColorStateList?)

  @JavaMethod
  open func getBackgroundTintList() -> ColorStateList!

  @JavaMethod
  open func setBackgroundTintMode(_ arg0: PorterDuff.Mode?)

  @JavaMethod
  open func setBackgroundTintBlendMode(_ arg0: BlendMode?)

  @JavaMethod
  open func getBackgroundTintMode() -> PorterDuff.Mode!

  @JavaMethod
  open func getBackgroundTintBlendMode() -> BlendMode!

  @JavaMethod
  open func getForeground() -> Drawable!

  @JavaMethod
  open func setForeground(_ arg0: Drawable?)

  @JavaMethod
  open func getForegroundGravity() -> Int32

  @JavaMethod
  open func setForegroundGravity(_ arg0: Int32)

  @JavaMethod
  open func setForegroundTintList(_ arg0: ColorStateList?)

  @JavaMethod
  open func getForegroundTintList() -> ColorStateList!

  @JavaMethod
  open func setForegroundTintMode(_ arg0: PorterDuff.Mode?)

  @JavaMethod
  open func setForegroundTintBlendMode(_ arg0: BlendMode?)

  @JavaMethod
  open func getForegroundTintMode() -> PorterDuff.Mode!

  @JavaMethod
  open func getForegroundTintBlendMode() -> BlendMode!

  @JavaMethod
  open func onDrawForeground(_ arg0: Canvas?)

  @JavaMethod
  open func setPadding(_ arg0: Int32, _ arg1: Int32, _ arg2: Int32, _ arg3: Int32)

  @JavaMethod
  open func setPaddingRelative(_ arg0: Int32, _ arg1: Int32, _ arg2: Int32, _ arg3: Int32)

  @JavaMethod
  open func getSourceLayoutResId() -> Int32

  @JavaMethod
  open func getPaddingTop() -> Int32

  @JavaMethod
  open func getPaddingBottom() -> Int32

  @JavaMethod
  open func getPaddingLeft() -> Int32

  @JavaMethod
  open func getPaddingStart() -> Int32

  @JavaMethod
  open func getPaddingRight() -> Int32

  @JavaMethod
  open func getPaddingEnd() -> Int32

  @JavaMethod
  open func isPaddingRelative() -> Bool

  @JavaMethod
  open func setSelected(_ arg0: Bool)

  @JavaMethod
  open func dispatchSetSelected(_ arg0: Bool)

  @JavaMethod
  open func isSelected() -> Bool

  @JavaMethod
  open func setActivated(_ arg0: Bool)

  @JavaMethod
  open func dispatchSetActivated(_ arg0: Bool)

  @JavaMethod
  open func isActivated() -> Bool

  @JavaMethod
  open func getViewTreeObserver() -> ViewTreeObserver!

  @JavaMethod
  open func getRootView() -> View!

  @JavaMethod
  open func transformMatrixToGlobal(_ arg0: Matrix?)

  @JavaMethod
  open func transformMatrixToLocal(_ arg0: Matrix?)

  @JavaMethod
  open func getLocationOnScreen(_ arg0: [Int32])

  @JavaMethod
  open func getLocationInWindow(_ arg0: [Int32])

  @JavaMethod
  open func findViewById(_ arg0: Int32) -> View!

  @JavaMethod
  open func requireViewById(_ arg0: Int32) -> View!

  @JavaMethod
  open func findViewWithTag(_ arg0: JavaObject?) -> View!

  @JavaMethod
  open func setId(_ arg0: Int32)

  @JavaMethod
  open func getUniqueDrawingId() -> Int64

  @JavaMethod
  open func getTag(_ arg0: Int32) -> JavaObject!

  @JavaMethod
  open func getTag() -> JavaObject!

  @JavaMethod
  open func setTag(_ arg0: Int32, _ arg1: JavaObject?)

  @JavaMethod
  open func setTag(_ arg0: JavaObject?)

  @JavaMethod
  open func getBaseline() -> Int32

  @JavaMethod
  open func isInLayout() -> Bool

  @JavaMethod
  open func requestLayout()

  @JavaMethod
  open func forceLayout()

  @JavaMethod
  open func measure(_ arg0: Int32, _ arg1: Int32)

  @JavaMethod
  open func setMeasuredDimension(_ arg0: Int32, _ arg1: Int32)

  @JavaMethod
  open func getSuggestedMinimumHeight() -> Int32

  @JavaMethod
  open func getSuggestedMinimumWidth() -> Int32

  @JavaMethod
  open func getMinimumHeight() -> Int32

  @JavaMethod
  open func setMinimumHeight(_ arg0: Int32)

  @JavaMethod
  open func getMinimumWidth() -> Int32

  @JavaMethod
  open func setMinimumWidth(_ arg0: Int32)

  @JavaMethod
  open func getAnimation() -> Animation!

  @JavaMethod
  open func startAnimation(_ arg0: Animation?)

  @JavaMethod
  open func clearAnimation()

  @JavaMethod
  open func setAnimation(_ arg0: Animation?)

  @JavaMethod
  open func onAnimationStart()

  @JavaMethod
  open func onAnimationEnd()

  @JavaMethod
  open func onSetAlpha(_ arg0: Int32) -> Bool

  @JavaMethod
  open func gatherTransparentRegion(_ arg0: Region?) -> Bool

  @JavaMethod
  open func playSoundEffect(_ arg0: Int32)

  @JavaMethod
  open func performHapticFeedback(_ arg0: Int32, _ arg1: Int32) -> Bool

  @JavaMethod
  open func performHapticFeedback(_ arg0: Int32) -> Bool

  @JavaMethod
  open func setSystemUiVisibility(_ arg0: Int32)

  @JavaMethod
  open func getSystemUiVisibility() -> Int32

  @JavaMethod
  open func getWindowSystemUiVisibility() -> Int32

  @JavaMethod
  open func onWindowSystemUiVisibilityChanged(_ arg0: Int32)

  @JavaMethod
  open func dispatchWindowSystemUiVisiblityChanged(_ arg0: Int32)

  @JavaMethod
  open func setOnSystemUiVisibilityChangeListener(_ arg0: View.OnSystemUiVisibilityChangeListener?)

  @JavaMethod
  open func dispatchSystemUiVisibilityChanged(_ arg0: Int32)

  @JavaMethod
  open func startDrag(_ arg0: ClipData?, _ arg1: View.DragShadowBuilder?, _ arg2: JavaObject?, _ arg3: Int32) -> Bool

  @JavaMethod
  open func startDragAndDrop(_ arg0: ClipData?, _ arg1: View.DragShadowBuilder?, _ arg2: JavaObject?, _ arg3: Int32) -> Bool

  @JavaMethod
  open func cancelDragAndDrop()

  @JavaMethod
  open func updateDragShadow(_ arg0: View.DragShadowBuilder?)

  @JavaMethod
  open func onDragEvent(_ arg0: DragEvent?) -> Bool

  @JavaMethod
  open func dispatchDragEvent(_ arg0: DragEvent?) -> Bool

  @JavaMethod
  open func overScrollBy(_ arg0: Int32, _ arg1: Int32, _ arg2: Int32, _ arg3: Int32, _ arg4: Int32, _ arg5: Int32, _ arg6: Int32, _ arg7: Int32, _ arg8: Bool) -> Bool

  @JavaMethod
  open func onOverScrolled(_ arg0: Int32, _ arg1: Int32, _ arg2: Bool, _ arg3: Bool)

  @JavaMethod
  open func getOverScrollMode() -> Int32

  @JavaMethod
  open func setOverScrollMode(_ arg0: Int32)

  @JavaMethod
  open func setNestedScrollingEnabled(_ arg0: Bool)

  @JavaMethod
  open func isNestedScrollingEnabled() -> Bool

  @JavaMethod
  open func startNestedScroll(_ arg0: Int32) -> Bool

  @JavaMethod
  open func stopNestedScroll()

  @JavaMethod
  open func hasNestedScrollingParent() -> Bool

  @JavaMethod
  open func dispatchNestedScroll(_ arg0: Int32, _ arg1: Int32, _ arg2: Int32, _ arg3: Int32, _ arg4: [Int32]) -> Bool

  @JavaMethod
  open func dispatchNestedPreScroll(_ arg0: Int32, _ arg1: Int32, _ arg2: [Int32], _ arg3: [Int32]) -> Bool

  @JavaMethod
  open func dispatchNestedFling(_ arg0: Float, _ arg1: Float, _ arg2: Bool) -> Bool

  @JavaMethod
  open func dispatchNestedPreFling(_ arg0: Float, _ arg1: Float) -> Bool

  @JavaMethod
  open func setTextDirection(_ arg0: Int32)

  @JavaMethod
  open func getTextDirection() -> Int32

  @JavaMethod
  open func canResolveTextDirection() -> Bool

  @JavaMethod
  open func isTextDirectionResolved() -> Bool

  @JavaMethod
  open func setTextAlignment(_ arg0: Int32)

  @JavaMethod
  open func getTextAlignment() -> Int32

  @JavaMethod
  open func canResolveTextAlignment() -> Bool

  @JavaMethod
  open func isTextAlignmentResolved() -> Bool

  @JavaMethod
  open func onResolvePointerIcon(_ arg0: MotionEvent?, _ arg1: Int32) -> PointerIcon!

  @JavaMethod
  open func setPointerIcon(_ arg0: PointerIcon?)

  @JavaMethod
  open func getPointerIcon() -> PointerIcon!

  @JavaMethod
  open func hasPointerCapture() -> Bool

  @JavaMethod
  open func requestPointerCapture()

  @JavaMethod
  open func releasePointerCapture()

  @JavaMethod
  open func onPointerCaptureChange(_ arg0: Bool)

  @JavaMethod
  open func dispatchPointerCaptureChanged(_ arg0: Bool)

  @JavaMethod
  open func onCapturedPointerEvent(_ arg0: MotionEvent?) -> Bool

  @JavaMethod
  open func setOnCapturedPointerListener(_ arg0: View.OnCapturedPointerListener?)

  @JavaMethod
  open func animate() -> ViewPropertyAnimator!

  @JavaMethod
  open func setTransitionName(_ arg0: String)

  @JavaMethod
  open func getTransitionName() -> String

  @JavaMethod
  open func getScrollCaptureHint() -> Int32

  @JavaMethod
  open func setScrollCaptureHint(_ arg0: Int32)

  @JavaMethod
  open func setScrollCaptureCallback(_ arg0: ScrollCaptureCallback?)

  @JavaMethod
  open func dispatchScrollCaptureSearch(_ arg0: Rect?, _ arg1: Point?, _ arg2: JavaConsumer<ScrollCaptureTarget>?)

  @JavaMethod
  open func onScrollCaptureSearch(_ arg0: Rect?, _ arg1: Point?, _ arg2: JavaConsumer<ScrollCaptureTarget>?)

  @JavaMethod
  open func setTooltipText(_ arg0: CharSequence?)

  @JavaMethod
  open func getTooltipText() -> CharSequence!

  @JavaMethod
  open func addOnUnhandledKeyEventListener(_ arg0: View.OnUnhandledKeyEventListener?)

  @JavaMethod
  open func removeOnUnhandledKeyEventListener(_ arg0: View.OnUnhandledKeyEventListener?)

  @JavaMethod
  open func setAutoHandwritingEnabled(_ arg0: Bool)

  @JavaMethod
  open func isAutoHandwritingEnabled() -> Bool

  @JavaMethod
  open func clearViewTranslationCallback()

  @JavaMethod
  open func getRootSurfaceControl() -> AttachedSurfaceControl!

  @JavaMethod
  open func getWidth() -> Int32

  @JavaMethod
  open func getHeight() -> Int32

  @JavaMethod
  open func getRotation() -> Float

  @JavaMethod
  open func getScrollBarSize() -> Int32

  @JavaMethod
  open func getScrollBarFadeDuration() -> Int32

  @JavaMethod
  open func onDraw(_ arg0: Canvas?)

  @JavaMethod
  open func setBackgroundColor(_ arg0: Int32)

  @JavaMethod
  open override func toString() -> String

  @JavaMethod
  open func getResources() -> Resources!

  @JavaMethod
  open func getParent() -> ViewParent!

  @JavaMethod
  open func isEnabled() -> Bool

  @JavaMethod
  open func getId() -> Int32

  @JavaMethod
  open func isOpaque() -> Bool

  @JavaMethod
  open func getHandler() -> Handler!

  @JavaMethod
  open func getContext() -> Context!

  @JavaMethod
  open func isDirty() -> Bool

  @JavaMethod
  open func post(_ arg0: Runnable?) -> Bool
}
extension JavaClass<View> {
  @JavaStaticField(isFinal: true)
  public var ACCESSIBILITY_LIVE_REGION_ASSERTIVE: Int32

  @JavaStaticField(isFinal: true)
  public var ACCESSIBILITY_LIVE_REGION_NONE: Int32

  @JavaStaticField(isFinal: true)
  public var ACCESSIBILITY_LIVE_REGION_POLITE: Int32

  @JavaStaticField(isFinal: true)
  public var AUTOFILL_FLAG_INCLUDE_NOT_IMPORTANT_VIEWS: Int32

  @JavaStaticField(isFinal: true)
  public var AUTOFILL_HINT_CREDIT_CARD_EXPIRATION_DATE: String

  @JavaStaticField(isFinal: true)
  public var AUTOFILL_HINT_CREDIT_CARD_EXPIRATION_DAY: String

  @JavaStaticField(isFinal: true)
  public var AUTOFILL_HINT_CREDIT_CARD_EXPIRATION_MONTH: String

  @JavaStaticField(isFinal: true)
  public var AUTOFILL_HINT_CREDIT_CARD_EXPIRATION_YEAR: String

  @JavaStaticField(isFinal: true)
  public var AUTOFILL_HINT_CREDIT_CARD_NUMBER: String

  @JavaStaticField(isFinal: true)
  public var AUTOFILL_HINT_CREDIT_CARD_SECURITY_CODE: String

  @JavaStaticField(isFinal: true)
  public var AUTOFILL_HINT_EMAIL_ADDRESS: String

  @JavaStaticField(isFinal: true)
  public var AUTOFILL_HINT_NAME: String

  @JavaStaticField(isFinal: true)
  public var AUTOFILL_HINT_PASSWORD: String

  @JavaStaticField(isFinal: true)
  public var AUTOFILL_HINT_PHONE: String

  @JavaStaticField(isFinal: true)
  public var AUTOFILL_HINT_POSTAL_ADDRESS: String

  @JavaStaticField(isFinal: true)
  public var AUTOFILL_HINT_POSTAL_CODE: String

  @JavaStaticField(isFinal: true)
  public var AUTOFILL_HINT_USERNAME: String

  @JavaStaticField(isFinal: true)
  public var AUTOFILL_TYPE_DATE: Int32

  @JavaStaticField(isFinal: true)
  public var AUTOFILL_TYPE_LIST: Int32

  @JavaStaticField(isFinal: true)
  public var AUTOFILL_TYPE_NONE: Int32

  @JavaStaticField(isFinal: true)
  public var AUTOFILL_TYPE_TEXT: Int32

  @JavaStaticField(isFinal: true)
  public var AUTOFILL_TYPE_TOGGLE: Int32

  @JavaStaticField(isFinal: true)
  public var DRAG_FLAG_ACCESSIBILITY_ACTION: Int32

  @JavaStaticField(isFinal: true)
  public var DRAG_FLAG_GLOBAL: Int32

  @JavaStaticField(isFinal: true)
  public var DRAG_FLAG_GLOBAL_PERSISTABLE_URI_PERMISSION: Int32

  @JavaStaticField(isFinal: true)
  public var DRAG_FLAG_GLOBAL_PREFIX_URI_PERMISSION: Int32

  @JavaStaticField(isFinal: true)
  public var DRAG_FLAG_GLOBAL_URI_READ: Int32

  @JavaStaticField(isFinal: true)
  public var DRAG_FLAG_GLOBAL_URI_WRITE: Int32

  @JavaStaticField(isFinal: true)
  public var DRAG_FLAG_OPAQUE: Int32

  @JavaStaticField(isFinal: true)
  public var DRAWING_CACHE_QUALITY_AUTO: Int32

  @JavaStaticField(isFinal: true)
  public var DRAWING_CACHE_QUALITY_HIGH: Int32

  @JavaStaticField(isFinal: true)
  public var DRAWING_CACHE_QUALITY_LOW: Int32

  @JavaStaticField(isFinal: true)
  public var FIND_VIEWS_WITH_CONTENT_DESCRIPTION: Int32

  @JavaStaticField(isFinal: true)
  public var FIND_VIEWS_WITH_TEXT: Int32

  @JavaStaticField(isFinal: true)
  public var FOCUSABLE: Int32

  @JavaStaticField(isFinal: true)
  public var FOCUSABLES_ALL: Int32

  @JavaStaticField(isFinal: true)
  public var FOCUSABLES_TOUCH_MODE: Int32

  @JavaStaticField(isFinal: true)
  public var FOCUSABLE_AUTO: Int32

  @JavaStaticField(isFinal: true)
  public var FOCUS_BACKWARD: Int32

  @JavaStaticField(isFinal: true)
  public var FOCUS_DOWN: Int32

  @JavaStaticField(isFinal: true)
  public var FOCUS_FORWARD: Int32

  @JavaStaticField(isFinal: true)
  public var FOCUS_LEFT: Int32

  @JavaStaticField(isFinal: true)
  public var FOCUS_RIGHT: Int32

  @JavaStaticField(isFinal: true)
  public var FOCUS_UP: Int32

  @JavaStaticField(isFinal: true)
  public var GONE: Int32

  @JavaStaticField(isFinal: true)
  public var HAPTIC_FEEDBACK_ENABLED: Int32

  @JavaStaticField(isFinal: true)
  public var IMPORTANT_FOR_ACCESSIBILITY_AUTO: Int32

  @JavaStaticField(isFinal: true)
  public var IMPORTANT_FOR_ACCESSIBILITY_NO: Int32

  @JavaStaticField(isFinal: true)
  public var IMPORTANT_FOR_ACCESSIBILITY_NO_HIDE_DESCENDANTS: Int32

  @JavaStaticField(isFinal: true)
  public var IMPORTANT_FOR_ACCESSIBILITY_YES: Int32

  @JavaStaticField(isFinal: true)
  public var IMPORTANT_FOR_AUTOFILL_AUTO: Int32

  @JavaStaticField(isFinal: true)
  public var IMPORTANT_FOR_AUTOFILL_NO: Int32

  @JavaStaticField(isFinal: true)
  public var IMPORTANT_FOR_AUTOFILL_NO_EXCLUDE_DESCENDANTS: Int32

  @JavaStaticField(isFinal: true)
  public var IMPORTANT_FOR_AUTOFILL_YES: Int32

  @JavaStaticField(isFinal: true)
  public var IMPORTANT_FOR_AUTOFILL_YES_EXCLUDE_DESCENDANTS: Int32

  @JavaStaticField(isFinal: true)
  public var IMPORTANT_FOR_CONTENT_CAPTURE_AUTO: Int32

  @JavaStaticField(isFinal: true)
  public var IMPORTANT_FOR_CONTENT_CAPTURE_NO: Int32

  @JavaStaticField(isFinal: true)
  public var IMPORTANT_FOR_CONTENT_CAPTURE_NO_EXCLUDE_DESCENDANTS: Int32

  @JavaStaticField(isFinal: true)
  public var IMPORTANT_FOR_CONTENT_CAPTURE_YES: Int32

  @JavaStaticField(isFinal: true)
  public var IMPORTANT_FOR_CONTENT_CAPTURE_YES_EXCLUDE_DESCENDANTS: Int32

  @JavaStaticField(isFinal: true)
  public var INVISIBLE: Int32

  @JavaStaticField(isFinal: true)
  public var KEEP_SCREEN_ON: Int32

  @JavaStaticField(isFinal: true)
  public var LAYER_TYPE_HARDWARE: Int32

  @JavaStaticField(isFinal: true)
  public var LAYER_TYPE_NONE: Int32

  @JavaStaticField(isFinal: true)
  public var LAYER_TYPE_SOFTWARE: Int32

  @JavaStaticField(isFinal: true)
  public var LAYOUT_DIRECTION_INHERIT: Int32

  @JavaStaticField(isFinal: true)
  public var LAYOUT_DIRECTION_LOCALE: Int32

  @JavaStaticField(isFinal: true)
  public var LAYOUT_DIRECTION_LTR: Int32

  @JavaStaticField(isFinal: true)
  public var LAYOUT_DIRECTION_RTL: Int32

  @JavaStaticField(isFinal: true)
  public var MEASURED_HEIGHT_STATE_SHIFT: Int32

  @JavaStaticField(isFinal: true)
  public var MEASURED_SIZE_MASK: Int32

  @JavaStaticField(isFinal: true)
  public var MEASURED_STATE_MASK: Int32

  @JavaStaticField(isFinal: true)
  public var MEASURED_STATE_TOO_SMALL: Int32

  @JavaStaticField(isFinal: true)
  public var NOT_FOCUSABLE: Int32

  @JavaStaticField(isFinal: true)
  public var NO_ID: Int32

  @JavaStaticField(isFinal: true)
  public var OVER_SCROLL_ALWAYS: Int32

  @JavaStaticField(isFinal: true)
  public var OVER_SCROLL_IF_CONTENT_SCROLLS: Int32

  @JavaStaticField(isFinal: true)
  public var OVER_SCROLL_NEVER: Int32

  @JavaStaticField(isFinal: true)
  public var SCREEN_STATE_OFF: Int32

  @JavaStaticField(isFinal: true)
  public var SCREEN_STATE_ON: Int32

  @JavaStaticField(isFinal: true)
  public var SCROLLBARS_INSIDE_INSET: Int32

  @JavaStaticField(isFinal: true)
  public var SCROLLBARS_INSIDE_OVERLAY: Int32

  @JavaStaticField(isFinal: true)
  public var SCROLLBARS_OUTSIDE_INSET: Int32

  @JavaStaticField(isFinal: true)
  public var SCROLLBARS_OUTSIDE_OVERLAY: Int32

  @JavaStaticField(isFinal: true)
  public var SCROLLBAR_POSITION_DEFAULT: Int32

  @JavaStaticField(isFinal: true)
  public var SCROLLBAR_POSITION_LEFT: Int32

  @JavaStaticField(isFinal: true)
  public var SCROLLBAR_POSITION_RIGHT: Int32

  @JavaStaticField(isFinal: true)
  public var SCROLL_AXIS_HORIZONTAL: Int32

  @JavaStaticField(isFinal: true)
  public var SCROLL_AXIS_NONE: Int32

  @JavaStaticField(isFinal: true)
  public var SCROLL_AXIS_VERTICAL: Int32

  @JavaStaticField(isFinal: true)
  public var SCROLL_CAPTURE_HINT_AUTO: Int32

  @JavaStaticField(isFinal: true)
  public var SCROLL_CAPTURE_HINT_EXCLUDE: Int32

  @JavaStaticField(isFinal: true)
  public var SCROLL_CAPTURE_HINT_EXCLUDE_DESCENDANTS: Int32

  @JavaStaticField(isFinal: true)
  public var SCROLL_CAPTURE_HINT_INCLUDE: Int32

  @JavaStaticField(isFinal: true)
  public var SCROLL_INDICATOR_BOTTOM: Int32

  @JavaStaticField(isFinal: true)
  public var SCROLL_INDICATOR_END: Int32

  @JavaStaticField(isFinal: true)
  public var SCROLL_INDICATOR_LEFT: Int32

  @JavaStaticField(isFinal: true)
  public var SCROLL_INDICATOR_RIGHT: Int32

  @JavaStaticField(isFinal: true)
  public var SCROLL_INDICATOR_START: Int32

  @JavaStaticField(isFinal: true)
  public var SCROLL_INDICATOR_TOP: Int32

  @JavaStaticField(isFinal: true)
  public var SOUND_EFFECTS_ENABLED: Int32

  @JavaStaticField(isFinal: true)
  public var STATUS_BAR_HIDDEN: Int32

  @JavaStaticField(isFinal: true)
  public var STATUS_BAR_VISIBLE: Int32

  @JavaStaticField(isFinal: true)
  public var SYSTEM_UI_FLAG_FULLSCREEN: Int32

  @JavaStaticField(isFinal: true)
  public var SYSTEM_UI_FLAG_HIDE_NAVIGATION: Int32

  @JavaStaticField(isFinal: true)
  public var SYSTEM_UI_FLAG_IMMERSIVE: Int32

  @JavaStaticField(isFinal: true)
  public var SYSTEM_UI_FLAG_IMMERSIVE_STICKY: Int32

  @JavaStaticField(isFinal: true)
  public var SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN: Int32

  @JavaStaticField(isFinal: true)
  public var SYSTEM_UI_FLAG_LAYOUT_HIDE_NAVIGATION: Int32

  @JavaStaticField(isFinal: true)
  public var SYSTEM_UI_FLAG_LAYOUT_STABLE: Int32

  @JavaStaticField(isFinal: true)
  public var SYSTEM_UI_FLAG_LIGHT_NAVIGATION_BAR: Int32

  @JavaStaticField(isFinal: true)
  public var SYSTEM_UI_FLAG_LIGHT_STATUS_BAR: Int32

  @JavaStaticField(isFinal: true)
  public var SYSTEM_UI_FLAG_LOW_PROFILE: Int32

  @JavaStaticField(isFinal: true)
  public var SYSTEM_UI_FLAG_VISIBLE: Int32

  @JavaStaticField(isFinal: true)
  public var SYSTEM_UI_LAYOUT_FLAGS: Int32

  @JavaStaticField(isFinal: true)
  public var TEXT_ALIGNMENT_CENTER: Int32

  @JavaStaticField(isFinal: true)
  public var TEXT_ALIGNMENT_GRAVITY: Int32

  @JavaStaticField(isFinal: true)
  public var TEXT_ALIGNMENT_INHERIT: Int32

  @JavaStaticField(isFinal: true)
  public var TEXT_ALIGNMENT_TEXT_END: Int32

  @JavaStaticField(isFinal: true)
  public var TEXT_ALIGNMENT_TEXT_START: Int32

  @JavaStaticField(isFinal: true)
  public var TEXT_ALIGNMENT_VIEW_END: Int32

  @JavaStaticField(isFinal: true)
  public var TEXT_ALIGNMENT_VIEW_START: Int32

  @JavaStaticField(isFinal: true)
  public var TEXT_DIRECTION_ANY_RTL: Int32

  @JavaStaticField(isFinal: true)
  public var TEXT_DIRECTION_FIRST_STRONG: Int32

  @JavaStaticField(isFinal: true)
  public var TEXT_DIRECTION_FIRST_STRONG_LTR: Int32

  @JavaStaticField(isFinal: true)
  public var TEXT_DIRECTION_FIRST_STRONG_RTL: Int32

  @JavaStaticField(isFinal: true)
  public var TEXT_DIRECTION_INHERIT: Int32

  @JavaStaticField(isFinal: true)
  public var TEXT_DIRECTION_LOCALE: Int32

  @JavaStaticField(isFinal: true)
  public var TEXT_DIRECTION_LTR: Int32

  @JavaStaticField(isFinal: true)
  public var TEXT_DIRECTION_RTL: Int32

  @JavaStaticField(isFinal: true)
  public var VISIBLE: Int32

  @JavaStaticMethod
  public func mergeDrawableStates(_ arg0: [Int32], _ arg1: [Int32]) -> [Int32]

  @JavaStaticMethod
  public func combineMeasuredStates(_ arg0: Int32, _ arg1: Int32) -> Int32

  @JavaStaticMethod
  public func resolveSizeAndState(_ arg0: Int32, _ arg1: Int32, _ arg2: Int32) -> Int32

  @JavaStaticMethod
  public func getDefaultSize(_ arg0: Int32, _ arg1: Int32) -> Int32

  @JavaStaticMethod
  public func generateViewId() -> Int32

  @JavaStaticMethod
  public func resolveSize(_ arg0: Int32, _ arg1: Int32) -> Int32

  @JavaStaticMethod
  public func inflate(_ arg0: Context?, _ arg1: Int32, _ arg2: ViewGroup?) -> View!
}
