// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

extension ViewTreeObserver {
  @JavaInterface("android.view.ViewTreeObserver$OnWindowFocusChangeListener")
  public struct OnWindowFocusChangeListener {
  @JavaMethod
  public func onWindowFocusChanged(_ arg0: Bool)
  }
}
