// Auto-generated by Java-to-Swift wrapper generator.
import AndroidOS
import JavaKit
import JavaRuntime

@JavaInterface("android.view.WindowInsetsController")
public struct WindowInsetsController {
  @JavaMethod
  public func controlWindowInsetsAnimation(_ arg0: Int32, _ arg1: Int64, _ arg2: Interpolator?, _ arg3: CancellationSignal?, _ arg4: WindowInsetsAnimationControlListener?)

  @JavaMethod
  public func setSystemBarsAppearance(_ arg0: Int32, _ arg1: Int32)

  @JavaMethod
  public func getSystemBarsAppearance() -> Int32

  @JavaMethod
  public func setSystemBarsBehavior(_ arg0: Int32)

  @JavaMethod
  public func getSystemBarsBehavior() -> Int32

  @JavaMethod
  public func hide(_ arg0: Int32)

  @JavaMethod
  public func show(_ arg0: Int32)

  @JavaMethod
  public func addOnControllableInsetsChangedListener(_ arg0: WindowInsetsController.OnControllableInsetsChangedListener?)

  @JavaMethod
  public func removeOnControllableInsetsChangedListener(_ arg0: WindowInsetsController.OnControllableInsetsChangedListener?)
}
extension JavaClass<WindowInsetsController> {
  @JavaStaticField(isFinal: true)
  public var APPEARANCE_LIGHT_NAVIGATION_BARS: Int32

  @JavaStaticField(isFinal: true)
  public var APPEARANCE_LIGHT_STATUS_BARS: Int32

  @JavaStaticField(isFinal: true)
  public var BEHAVIOR_DEFAULT: Int32

  @JavaStaticField(isFinal: true)
  public var BEHAVIOR_SHOW_BARS_BY_SWIPE: Int32

  @JavaStaticField(isFinal: true)
  public var BEHAVIOR_SHOW_BARS_BY_TOUCH: Int32

  @JavaStaticField(isFinal: true)
  public var BEHAVIOR_SHOW_TRANSIENT_BARS_BY_SWIPE: Int32
}
