// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaKitCollection
import JavaRuntime

extension WindowInsetsAnimation {
  @JavaClass("android.view.WindowInsetsAnimation$Callback")
  open class Callback: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: Int32, environment: JNIEnvironment? = nil)

  @JavaMethod
  open func onStart(_ arg0: WindowInsetsAnimation?, _ arg1: WindowInsetsAnimation.Bounds?) -> WindowInsetsAnimation.Bounds!

  @JavaMethod
  open func getDispatchMode() -> Int32

  @JavaMethod
  open func onPrepare(_ arg0: WindowInsetsAnimation?)

  @JavaMethod
  open func onProgress(_ arg0: WindowInsets?, _ arg1: List<WindowInsetsAnimation>?) -> WindowInsets!

  @JavaMethod
  open func onEnd(_ arg0: WindowInsetsAnimation?)
  }
}
extension JavaClass<WindowInsetsAnimation.Callback> {
  @JavaStaticField(isFinal: true)
  public var DISPATCH_MODE_CONTINUE_ON_SUBTREE: Int32

  @JavaStaticField(isFinal: true)
  public var DISPATCH_MODE_STOP: Int32
}
