// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

extension WindowInsets {
  @JavaClass("android.view.WindowInsets$Type")
  open class `Type`: JavaObject {

  }
}
extension JavaClass<WindowInsets.`Type`> {
    
  @JavaStaticMethod
  public func mandatorySystemGestures() -> Int32

  @JavaStaticMethod
  public func captionBar() -> Int32

  @JavaStaticMethod
  public func navigationBars() -> Int32

  @JavaStaticMethod
  public func statusBars() -> Int32

  @JavaStaticMethod
  public func ime() -> Int32

  @JavaStaticMethod
  public func systemGestures() -> Int32

  @JavaStaticMethod
  public func tappableElement() -> Int32

  @JavaStaticMethod
  public func displayCutout() -> Int32

  @JavaStaticMethod
  public func systemBars() -> Int32
}
