// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava
import CSwiftJavaJNI

extension LayoutTransition {
  @JavaInterface("android.animation.LayoutTransition$TransitionListener")
  public struct TransitionListener {

  }
}
