// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaKitCollection
import JavaRuntime

@JavaClass("android.animation.LayoutTransition")
open class LayoutTransition: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(environment: JNIEnvironment? = nil)

  @JavaMethod
  open func setDuration(_ arg0: Int32, _ arg1: Int64)

  @JavaMethod
  open func setDuration(_ arg0: Int64)

  @JavaMethod
  open func enableTransitionType(_ arg0: Int32)

  @JavaMethod
  open func disableTransitionType(_ arg0: Int32)

  @JavaMethod
  open func isTransitionTypeEnabled(_ arg0: Int32) -> Bool

  @JavaMethod
  open func setStartDelay(_ arg0: Int32, _ arg1: Int64)

  @JavaMethod
  open func getStartDelay(_ arg0: Int32) -> Int64

  @JavaMethod
  open func setStagger(_ arg0: Int32, _ arg1: Int64)

  @JavaMethod
  open func getStagger(_ arg0: Int32) -> Int64

  @JavaMethod
  open func setInterpolator(_ arg0: Int32, _ arg1: TimeInterpolator?)

  @JavaMethod
  open func getInterpolator(_ arg0: Int32) -> TimeInterpolator!

  @JavaMethod
  open func setAnimator(_ arg0: Int32, _ arg1: Animator?)

  @JavaMethod
  open func getAnimator(_ arg0: Int32) -> Animator!

  @JavaMethod
  open func setAnimateParentHierarchy(_ arg0: Bool)

  @JavaMethod
  open func isChangingLayout() -> Bool

  @JavaMethod
  open func isRunning() -> Bool

  @JavaMethod
  open func addTransitionListener(_ arg0: LayoutTransition.TransitionListener?)

  @JavaMethod
  open func removeTransitionListener(_ arg0: LayoutTransition.TransitionListener?)

  @JavaMethod
  open func getTransitionListeners() -> List<LayoutTransition.TransitionListener>!

  @JavaMethod
  open func getDuration(_ arg0: Int32) -> Int64
}
extension JavaClass<LayoutTransition> {
  @JavaStaticField(isFinal: true)
  public var APPEARING: Int32

  @JavaStaticField(isFinal: true)
  public var CHANGE_APPEARING: Int32

  @JavaStaticField(isFinal: true)
  public var CHANGE_DISAPPEARING: Int32

  @JavaStaticField(isFinal: true)
  public var CHANGING: Int32

  @JavaStaticField(isFinal: true)
  public var DISAPPEARING: Int32
}
