#pragma once

// NDK headers
#include <android/api-level.h>
#include <android/asset_manager_jni.h>
#include <android/asset_manager.h>
#include <android/binder_ibinder_jni.h>
#include <android/binder_ibinder.h>
#include <android/binder_internal_logging.h>
#include <android/binder_parcel_jni.h>
#include <android/binder_parcel.h>
#include <android/binder_status.h>
#include <android/bitmap.h>
#include <android/choreographer.h>
#include <android/configuration.h>
#include <android/crash_detail.h>
#include <android/data_space.h>
#include <android/dlext.h>
#include <android/fdsan.h>
#include <android/file_descriptor_jni.h>
#include <android/font_matcher.h>
#include <android/font.h>
#include <android/hardware_buffer_aidl.h>
#include <android/hardware_buffer_jni.h>
#include <android/hardware_buffer.h>
#include <android/hdr_metadata.h>
#include <android/imagedecoder.h>
#include <android/input.h>
#include <android/keycodes.h>
#include <android/log_macros.h>
#include <android/log.h>
#include <android/looper.h>
#include <android/multinetwork.h>
#include <android/native_activity.h>
#include <android/native_window_aidl.h>
#include <android/native_window_jni.h>
#include <android/native_window.h>
#include <android/ndk-version.h>
#include <android/NeuralNetworks.h>
#include <android/NeuralNetworksTypes.h>
#include <android/obb.h>
#include <android/performance_hint.h>
#include <android/permission_manager.h>
#include <android/persistable_bundle.h>
#include <android/rect.h>
#include <android/sensor.h>
#include <android/set_abort_message.h>
#include <android/sharedmem_jni.h>
#include <android/sharedmem.h>
#include <android/storage_manager.h>
#include <android/surface_texture_jni.h>
#include <android/surface_texture.h>
#include <android/sync.h>
#include <android/system_fonts.h>
#include <android/trace.h>
#include <android/versioning.h>
#include <android/window.h>

// Bionic
#include <sys/epoll.h>
#include <sys/eventfd.h>
#include <sys/stat.h>
#include <sys/socket.h>
#include <sys/sysinfo.h>
#include <sys/timerfd.h>
#include <sys/types.h>
#include <errno.h>
#include <fcntl.h>
#include <pthread.h>
#include <sched.h>
#include <unistd.h>