// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

@JavaClass("com.google.android.material.floatingactionbutton.AnimatorTracker")
open class AnimatorTracker: JavaObject {
  @JavaMethod
  open func cancelCurrent()

  @JavaMethod
  open func clear()
}
