// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaKitReflection
import JavaRuntime

extension AppBarLayout.LayoutParams {

    public typealias ScrollEffect = AppBarLayoutLayoutParamsScrollEffect
}

@JavaInterface("com.google.android.material.appbar.AppBarLayout$LayoutParams$ScrollEffect", extends: Annotation.self)
public struct AppBarLayoutLayoutParamsScrollEffect {
@JavaMethod
public func equals(_ arg0: JavaObject?) -> Bool

@JavaMethod
public func toString() -> String

@JavaMethod
public func hashCode() -> Int32

@JavaMethod
public func annotationType() -> JavaClass<Annotation>!
}
