// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

extension AppBarLayout.BaseBehavior {
  @JavaClass("com.google.android.material.appbar.AppBarLayout$BaseBehavior$BaseDragCallback")
  open class BaseDragCallback: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(environment: JNIEnvironment? = nil)

  @JavaMethod
  open func canDrag(_ arg0: AppBarLayout?) -> Bool
  }
}
