// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

extension BottomAppBar {
  @JavaInterface("com.google.android.material.bottomappbar.BottomAppBar$AnimationListener")
  public struct AnimationListener {
  @JavaMethod
  public func onAnimationStart(_ arg0: BottomAppBar?)

  @JavaMethod
  public func onAnimationEnd(_ arg0: BottomAppBar?)
  }
}
