// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava
import JavaLangReflect
import CSwiftJavaJNI

extension BottomAppBar {
  @JavaInterface("com.google.android.material.bottomappbar.BottomAppBar$FabAnchorMode", extends: Annotation.self)
  public struct FabAnchorMode {
  @JavaMethod
  public func equals(_ arg0: JavaObject?) -> Bool

  @JavaMethod
  public func toString() -> String

  @JavaMethod
  public func hashCode() -> Int32

  @JavaMethod
  public func annotationType() -> JavaClass<Annotation>!
  }
}
