// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

extension BottomSheetBehavior {
  @JavaClass("com.google.android.material.bottomsheet.BottomSheetBehavior$StateSettlingTracker")
  open class StateSettlingTracker: JavaObject {

  }
}
