// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaKitReflection
import JavaRuntime

extension BottomAppBar {
  @JavaInterface("com.google.android.material.bottomappbar.BottomAppBar$MenuAlignmentMode", extends: Annotation.self)
  public struct MenuAlignmentMode {
  @JavaMethod
  public func equals(_ arg0: JavaObject?) -> Bool

  @JavaMethod
  public func toString() -> String

  @JavaMethod
  public func hashCode() -> Int32

  @JavaMethod
  public func annotationType() -> JavaClass<Annotation>!
  }
}
