// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava
import CSwiftJavaJNI

@JavaClass("com.google.android.material.carousel.CarouselStrategyHelper")
open class CarouselStrategyHelper: JavaObject {

}
