// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava
import CSwiftJavaJNI

extension ColorResourcesTableCreator {
  @JavaClass("com.google.android.material.color.ColorResourcesTableCreator$ColorResource")
  open class ColorResource: JavaObject {

  }
}
