// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaKitCollection
import JavaRuntime

extension CompositeDateValidator {
  @JavaInterface("com.google.android.material.datepicker.CompositeDateValidator$Operator")
  public struct Operator {
  @JavaMethod
  public func getId() -> Int32

  @JavaMethod
  public func isValid(_ arg0: List<CalendarConstraints.DateValidator>?, _ arg1: Int64) -> Bool
  }
}
