// Auto-generated by Java-to-Swift wrapper generator.
import AndroidView
import JavaKit
import JavaRuntime

extension ExtendedFloatingActionButton {
  @JavaInterface("com.google.android.material.floatingactionbutton.ExtendedFloatingActionButton$Size")
  public struct Size {
  @JavaMethod
  public func getWidth() -> Int32

  @JavaMethod
  public func getHeight() -> Int32

  @JavaMethod
  public func getLayoutParams() -> ViewGroup.LayoutParams!

  @JavaMethod
  public func getPaddingStart() -> Int32

  @JavaMethod
  public func getPaddingEnd() -> Int32
  }
}
