// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

extension FloatingActionButtonImpl {
  @JavaClass("com.google.android.material.floatingactionbutton.FloatingActionButtonImpl$ResetElevationAnimation")
  open class ResetElevationAnimation: FloatingActionButtonImpl.ShadowAnimatorImpl {
  @JavaMethod
  open override func getTargetShadowSize() -> Float
  }
}
