// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava
import CSwiftJavaJNI

@JavaClass("com.google.android.material.floatingactionbutton.FloatingActionButtonImplLollipop")
open class FloatingActionButtonImplLollipop: FloatingActionButtonImpl {
  @JavaMethod
  open func getElevation() -> Float
}
