// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

@JavaClass("com.google.android.material.color.HarmonizedColorAttributes")
open class HarmonizedColorAttributes: JavaObject {
  @JavaMethod
  open func getThemeOverlay() -> Int32

  @JavaMethod
  open func getAttributes() -> [Int32]
}
extension JavaClass<HarmonizedColorAttributes> {
  @JavaStaticMethod
  public func createMaterialDefaults() -> HarmonizedColorAttributes!

  @JavaStaticMethod
  public func create(_ arg0: [Int32], _ arg1: Int32) -> HarmonizedColorAttributes!

  @JavaStaticMethod
  public func create(_ arg0: [Int32]) -> HarmonizedColorAttributes!
}
