// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

@JavaClass("com.google.android.material.carousel.KeylineStateList")
open class KeylineStateList: JavaObject {
  @JavaMethod
  open func getShiftedState(_ arg0: Float, _ arg1: Float, _ arg2: Float) -> KeylineState!
}
