// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava
import CSwiftJavaJNI

extension MaterialCardView {
  @JavaInterface("com.google.android.material.card.MaterialCardView$OnCheckedChangeListener")
  public struct OnCheckedChangeListener {
  @JavaMethod
  public func onCheckedChanged(_ arg0: MaterialCardView?, _ arg1: Bool)
  }
}
