// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

extension MaterialButton {
  @JavaInterface("com.google.android.material.button.MaterialButton$OnPressedChangeListener")
  public struct OnPressedChangeListener {
  @JavaMethod
  public func onPressedChanged(_ arg0: MaterialButton?, _ arg1: Bool)
  }
}
