// Auto-generated by Java-to-Swift wrapper generator.
import AndroidContent
import AndroidGraphics
import AndroidUtil
import AndroidView
import JavaKit
import JavaRuntime

@JavaClass("com.google.android.material.divider.MaterialDividerItemDecoration")
open class MaterialDividerItemDecoration: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: Context?, _ arg1: AttributeSet?, _ arg2: Int32, environment: JNIEnvironment? = nil)

  @JavaMethod
  @_nonoverride public convenience init(_ arg0: Context?, _ arg1: AttributeSet?, _ arg2: Int32, _ arg3: Int32, environment: JNIEnvironment? = nil)

  @JavaMethod
  @_nonoverride public convenience init(_ arg0: Context?, _ arg1: Int32, environment: JNIEnvironment? = nil)

  @JavaMethod
  open func setOrientation(_ arg0: Int32)

  @JavaMethod
  open func getOrientation() -> Int32

  @JavaMethod
  open func setDividerThickness(_ arg0: Int32)

  @JavaMethod
  open func setDividerThicknessResource(_ arg0: Context?, _ arg1: Int32)

  @JavaMethod
  open func getDividerThickness() -> Int32

  @JavaMethod
  open func setDividerColor(_ arg0: Int32)

  @JavaMethod
  open func setDividerColorResource(_ arg0: Context?, _ arg1: Int32)

  @JavaMethod
  open func getDividerColor() -> Int32

  @JavaMethod
  open func setDividerInsetStart(_ arg0: Int32)

  @JavaMethod
  open func setDividerInsetStartResource(_ arg0: Context?, _ arg1: Int32)

  @JavaMethod
  open func getDividerInsetStart() -> Int32

  @JavaMethod
  open func setDividerInsetEnd(_ arg0: Int32)

  @JavaMethod
  open func setDividerInsetEndResource(_ arg0: Context?, _ arg1: Int32)

  @JavaMethod
  open func getDividerInsetEnd() -> Int32

  @JavaMethod
  open func setLastItemDecorated(_ arg0: Bool)

  @JavaMethod
  open func isLastItemDecorated() -> Bool
}
extension JavaClass<MaterialDividerItemDecoration> {
  @JavaStaticField(isFinal: true)
  public var HORIZONTAL: Int32

  @JavaStaticField(isFinal: true)
  public var VERTICAL: Int32
}
