// Auto-generated by Java-to-Swift wrapper generator.
import AndroidView
import JavaKit
import JavaRuntime

extension NavigationView {
  @JavaInterface("com.google.android.material.navigation.NavigationView$OnNavigationItemSelectedListener")
  public struct OnNavigationItemSelectedListener {
  @JavaMethod
  public func onNavigationItemSelected(_ arg0: MenuItem?) -> Bool
  }
}
