// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

extension TabLayout {
  @JavaClass("com.google.android.material.tabs.TabLayout$PagerAdapterObserver")
  open class PagerAdapterObserver: JavaObject {
  @JavaMethod
  open func onInvalidated()

  @JavaMethod
  open func onChanged()
  }
}
