// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

@JavaInterface("java.util.concurrent.Callable")
public struct Callable<V: AnyJavaObject> {
  @JavaMethod
  public func call() throws -> JavaObject!
}
