// Auto-generated by Java-to-Swift wrapper generator.
import AndroidJavaIO
import JavaKit
import JavaRuntime

@JavaClass("java.util.Date", implements: Serializable.self)
open class Date: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: String, environment: JNIEnvironment? = nil)

  @JavaMethod
  @_nonoverride public convenience init(_ arg0: Int32, _ arg1: Int32, _ arg2: Int32, _ arg3: Int32, _ arg4: Int32, _ arg5: Int32, environment: JNIEnvironment? = nil)

  @JavaMethod
  @_nonoverride public convenience init(_ arg0: Int32, _ arg1: Int32, _ arg2: Int32, _ arg3: Int32, _ arg4: Int32, environment: JNIEnvironment? = nil)

  @JavaMethod
  @_nonoverride public convenience init(environment: JNIEnvironment? = nil)

  @JavaMethod
  @_nonoverride public convenience init(_ arg0: Int64, environment: JNIEnvironment? = nil)

  @JavaMethod
  @_nonoverride public convenience init(_ arg0: Int32, _ arg1: Int32, _ arg2: Int32, environment: JNIEnvironment? = nil)

  @JavaMethod
  open override func equals(_ arg0: JavaObject?) -> Bool

  @JavaMethod
  open override func toString() -> String

  @JavaMethod
  open override func hashCode() -> Int32

  @JavaMethod
  open override func clone() -> JavaObject!

  @JavaMethod
  open func compareTo(_ arg0: JavaObject?) -> Int32

  @JavaMethod
  open func compareTo(_ arg0: Date?) -> Int32

  @JavaMethod
  open func before(_ arg0: Date?) -> Bool

  @JavaMethod
  open func after(_ arg0: Date?) -> Bool

  @JavaMethod
  open func getYear() -> Int32

  @JavaMethod
  open func getTime() -> Int64

  @JavaMethod
  open func setTime(_ arg0: Int64)

  @JavaMethod
  open func getSeconds() -> Int32

  @JavaMethod
  open func getMonth() -> Int32

  @JavaMethod
  open func setDate(_ arg0: Int32)

  @JavaMethod
  open func setMonth(_ arg0: Int32)

  @JavaMethod
  open func getHours() -> Int32

  @JavaMethod
  open func setHours(_ arg0: Int32)

  @JavaMethod
  open func getMinutes() -> Int32

  @JavaMethod
  open func setMinutes(_ arg0: Int32)

  @JavaMethod
  open func setSeconds(_ arg0: Int32)

  @JavaMethod
  open func setYear(_ arg0: Int32)

  @JavaMethod
  open func getDate() -> Int32

  @JavaMethod
  open func getDay() -> Int32

  @JavaMethod
  open func toLocaleString() -> String

  @JavaMethod
  open func toGMTString() -> String

  @JavaMethod
  open func getTimezoneOffset() -> Int32
}
extension JavaClass<Date> {
  @JavaStaticMethod
  public func parse(_ arg0: String) -> Int64

  @JavaStaticMethod
  public func UTC(_ arg0: Int32, _ arg1: Int32, _ arg2: Int32, _ arg3: Int32, _ arg4: Int32, _ arg5: Int32) -> Int64
}
