// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaKitFunction
import JavaRuntime

extension DoubleStream {
  @JavaInterface("java.util.stream.DoubleStream$Builder", extends: JavaDoubleConsumer.self)
  public struct Builder {
  @JavaMethod
  public func add(_ arg0: Double) -> DoubleStream.Builder!

  @JavaMethod
  public func accept(_ arg0: Double)

  @JavaMethod
  public func build() -> DoubleStream!

  @JavaMethod
  public func andThen(_ arg0: JavaDoubleConsumer?) -> JavaDoubleConsumer!
  }
}
