// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

@JavaClass("java.util.prefs.NodeChangeEvent")
open class NodeChangeEvent: EventObject {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: Preferences?, _ arg1: Preferences?, environment: JNIEnvironment? = nil)

  @JavaMethod
  open func getParent() -> Preferences!

  @JavaMethod
  open func getChild() -> Preferences!
}
