// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

@JavaInterface("java.util.concurrent.ScheduledFuture", extends: Delayed.self, Future<JavaObject>.self)
public struct ScheduledFuture<V: AnyJavaObject> {
  @JavaMethod
  public func getDelay(_ arg0: TimeUnit?) -> Int64

  @JavaMethod
  public func compareTo(_ arg0: JavaObject?) -> Int32

  @JavaMethod
  public func get(_ arg0: Int64, _ arg1: TimeUnit?) throws -> JavaObject!

  @JavaMethod
  public func get() throws -> JavaObject!

  @JavaMethod
  public func state() -> Future.State!

  @JavaMethod
  public func isDone() -> Bool

  @JavaMethod
  public func cancel(_ arg0: Bool) -> Bool

  @JavaMethod
  public func isCancelled() -> Bool

  @JavaMethod
  public func resultNow() -> JavaObject!

  @JavaMethod
  public func exceptionNow() -> Throwable!
}
