// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

@JavaClass("java.util.StringJoiner")
open class StringJoiner: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: CharSequence?, environment: JNIEnvironment? = nil)

  @JavaMethod
  @_nonoverride public convenience init(_ arg0: CharSequence?, _ arg1: CharSequence?, _ arg2: CharSequence?, environment: JNIEnvironment? = nil)

  @JavaMethod
  open func length() -> Int32

  @JavaMethod
  open override func toString() -> String

  @JavaMethod
  open func add(_ arg0: CharSequence?) -> StringJoiner!

  @JavaMethod
  open func merge(_ arg0: StringJoiner?) -> StringJoiner!

  @JavaMethod
  open func setEmptyValue(_ arg0: CharSequence?) -> StringJoiner!
}
