// Auto-generated by Java-to-Swift wrapper generator.
import AndroidContent
import JavaKit
import JavaRuntime

@JavaClass("android.graphics.drawable.AnimatedStateListDrawable")
open class AnimatedStateListDrawable: StateListDrawable {
  @JavaMethod
  @_nonoverride public convenience init(environment: JNIEnvironment? = nil)

  @JavaMethod
  open override func setVisible(_ arg0: Bool, _ arg1: Bool) -> Bool

  @JavaMethod
  open func addState(_ arg0: [Int32], _ arg1: Drawable?, _ arg2: Int32)

  @JavaMethod
  open override func isStateful() -> Bool

  @JavaMethod
  open override func onStateChange(_ arg0: [Int32]) -> Bool

  @JavaMethod
  open override func jumpToCurrentState()

  @JavaMethod
  open override func applyTheme(_ arg0: Resources.Theme?)

  @JavaMethod
  open override func mutate() -> Drawable!

  @JavaMethod
  open override func setConstantState(_ arg0: DrawableContainer.DrawableContainerState?)
}
