// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

@JavaClass("android.graphics.Camera")
open class Camera: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(environment: JNIEnvironment? = nil)

  @JavaMethod
  open func restore()

  @JavaMethod
  open func translate(_ arg0: Float, _ arg1: Float, _ arg2: Float)

  @JavaMethod
  open func rotateX(_ arg0: Float)

  @JavaMethod
  open func rotateY(_ arg0: Float)

  @JavaMethod
  open func rotateZ(_ arg0: Float)

  @JavaMethod
  open func getLocationX() -> Float

  @JavaMethod
  open func getLocationY() -> Float

  @JavaMethod
  open func getLocationZ() -> Float

  @JavaMethod
  open func setLocation(_ arg0: Float, _ arg1: Float, _ arg2: Float)

  @JavaMethod
  open func getMatrix(_ arg0: Matrix?)

  @JavaMethod
  open func applyToCanvas(_ arg0: Canvas?)

  @JavaMethod
  open func dotWithNormal(_ arg0: Float, _ arg1: Float, _ arg2: Float) -> Float

  @JavaMethod
  open override func finalize() throws

  @JavaMethod
  open func save()

  @JavaMethod
  open func rotate(_ arg0: Float, _ arg1: Float, _ arg2: Float)
}
