// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

@JavaClass("android.graphics.fonts.FontStyle")
open class FontStyle: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(environment: JNIEnvironment? = nil)

  @JavaMethod
  @_nonoverride public convenience init(_ arg0: Int32, _ arg1: Int32, environment: JNIEnvironment? = nil)

  @JavaMethod
  open func getWeight() -> Int32

  @JavaMethod
  open func getSlant() -> Int32

  @JavaMethod
  open override func equals(_ arg0: JavaObject?) -> Bool

  @JavaMethod
  open override func toString() -> String

  @JavaMethod
  open override func hashCode() -> Int32
}
extension JavaClass<FontStyle> {
  @JavaStaticField(isFinal: true)
  public var FONT_SLANT_ITALIC: Int32

  @JavaStaticField(isFinal: true)
  public var FONT_SLANT_UPRIGHT: Int32

  @JavaStaticField(isFinal: true)
  public var FONT_WEIGHT_BLACK: Int32

  @JavaStaticField(isFinal: true)
  public var FONT_WEIGHT_BOLD: Int32

  @JavaStaticField(isFinal: true)
  public var FONT_WEIGHT_EXTRA_BOLD: Int32

  @JavaStaticField(isFinal: true)
  public var FONT_WEIGHT_EXTRA_LIGHT: Int32

  @JavaStaticField(isFinal: true)
  public var FONT_WEIGHT_LIGHT: Int32

  @JavaStaticField(isFinal: true)
  public var FONT_WEIGHT_MAX: Int32

  @JavaStaticField(isFinal: true)
  public var FONT_WEIGHT_MEDIUM: Int32

  @JavaStaticField(isFinal: true)
  public var FONT_WEIGHT_MIN: Int32

  @JavaStaticField(isFinal: true)
  public var FONT_WEIGHT_NORMAL: Int32

  @JavaStaticField(isFinal: true)
  public var FONT_WEIGHT_SEMI_BOLD: Int32

  @JavaStaticField(isFinal: true)
  public var FONT_WEIGHT_THIN: Int32
}
