// Auto-generated by Java-to-Swift wrapper generator.
import AndroidUtil
import JavaKit
import JavaRuntime

extension ImageDecoder {
  @JavaClass("android.graphics.ImageDecoder$ImageInfo")
  open class ImageInfo: JavaObject {
  @JavaMethod
  open func getMimeType() -> String

  @JavaMethod
  open func isAnimated() -> Bool

  @JavaMethod
  open func getColorSpace() -> ColorSpace!

  @JavaMethod
  open func getSize() -> Size!
  }
}
