// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

extension LineBreaker {
  @JavaClass("android.graphics.text.LineBreaker$ParagraphConstraints")
  open class ParagraphConstraints: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(environment: JNIEnvironment? = nil)

  @JavaMethod
  open func setWidth(_ arg0: Float)

  @JavaMethod
  open func getWidth() -> Float

  @JavaMethod
  open func setIndent(_ arg0: Float, _ arg1: Int32)

  @JavaMethod
  open func setTabStops(_ arg0: [Float], _ arg1: Float)

  @JavaMethod
  open func getFirstWidth() -> Float

  @JavaMethod
  open func getFirstWidthLineCount() -> Int32

  @JavaMethod
  open func getTabStops() -> [Float]

  @JavaMethod
  open func getDefaultTabStop() -> Float
  }
}
