// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

extension Paint {
  @JavaClass("android.graphics.Paint$FontMetrics")
  open class FontMetrics: JavaObject {
  @JavaField(isFinal: false)
  public var ascent: Float

  @JavaField(isFinal: false)
  public var bottom: Float

  @JavaField(isFinal: false)
  public var descent: Float

  @JavaField(isFinal: false)
  public var leading: Float

  @JavaField(isFinal: false)
  public var top: Float

  @JavaMethod
  @_nonoverride public convenience init(environment: JNIEnvironment? = nil)
  }
}
