// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava
import CSwiftJavaJNI

extension PdfDocument {
  @JavaClass("android.graphics.pdf.PdfDocument$PageInfo")
  open class PageInfo: JavaObject {
  @JavaMethod
  open func getPageWidth() -> Int32

  @JavaMethod
  open func getPageHeight() -> Int32

  @JavaMethod
  open func getContentRect() -> Rect!

  @JavaMethod
  open func getPageNumber() -> Int32
  }
}
