// Auto-generated by Java-to-Swift wrapper generator.
import AndroidContent
import AndroidJavaIO
import JavaKit
import JavaRuntime

@JavaClass("android.graphics.Typeface")
open class Typeface: JavaObject {
  @JavaMethod
  open func getStyle() -> Int32

  @JavaMethod
  open func getWeight() -> Int32

  @JavaMethod
  open func isBold() -> Bool

  @JavaMethod
  open func isItalic() -> Bool

  @JavaMethod
  open override func equals(_ arg0: JavaObject?) -> Bool

  @JavaMethod
  open override func hashCode() -> Int32
}
extension JavaClass<Typeface> {
  @JavaStaticField(isFinal: true)
  public var BOLD: Int32

  @JavaStaticField(isFinal: true)
  public var BOLD_ITALIC: Int32

  @JavaStaticField(isFinal: true)
  public var DEFAULT: Typeface!

  @JavaStaticField(isFinal: true)
  public var DEFAULT_BOLD: Typeface!

  @JavaStaticField(isFinal: true)
  public var ITALIC: Int32

  @JavaStaticField(isFinal: true)
  public var MONOSPACE: Typeface!

  @JavaStaticField(isFinal: true)
  public var NORMAL: Int32

  @JavaStaticField(isFinal: true)
  public var SANS_SERIF: Typeface!

  @JavaStaticField(isFinal: true)
  public var SERIF: Typeface!

  @JavaStaticMethod
  public func defaultFromStyle(_ arg0: Int32) -> Typeface!

  @JavaStaticMethod
  public func createFromAsset(_ arg0: AssetManager?, _ arg1: String) -> Typeface!

  @JavaStaticMethod
  public func createFromFile(_ arg0: String) -> Typeface!

  @JavaStaticMethod
  public func createFromFile(_ arg0: File?) -> Typeface!

  @JavaStaticMethod
  public func create(_ arg0: Typeface?, _ arg1: Int32, _ arg2: Bool) -> Typeface!

  @JavaStaticMethod
  public func create(_ arg0: String, _ arg1: Int32) -> Typeface!

  @JavaStaticMethod
  public func create(_ arg0: Typeface?, _ arg1: Int32) -> Typeface!
}
