// Auto-generated by Java-to-Swift wrapper generator.
import AndroidOS
import CSwiftJavaJNI
import SwiftJava

@available(Android 24, *)
@JavaClass("android.location.GnssMeasurement", implements: Parcelable.self)
open class GnssMeasurement: JavaObject {
  /// Java method `getConstellationType`.
  ///
  /// ### Java method signature
  /// ```java
  /// public int android.location.GnssMeasurement.getConstellationType()
  /// ```
@JavaMethod
  open func getConstellationType() -> Int32

  /// Java method `hasCarrierFrequencyHz`.
  ///
  /// ### Java method signature
  /// ```java
  /// public boolean android.location.GnssMeasurement.hasCarrierFrequencyHz()
  /// ```
@available(Android 26, *)
@JavaMethod
  open func hasCarrierFrequencyHz() -> Bool

  /// Java method `getCarrierFrequencyHz`.
  ///
  /// ### Java method signature
  /// ```java
  /// public float android.location.GnssMeasurement.getCarrierFrequencyHz()
  /// ```
@available(Android 26, *)
@JavaMethod
  open func getCarrierFrequencyHz() -> Float

  /// Java method `getReceivedSvTimeNanos`.
  ///
  /// ### Java method signature
  /// ```java
  /// public long android.location.GnssMeasurement.getReceivedSvTimeNanos()
  /// ```
@JavaMethod
  open func getReceivedSvTimeNanos() -> Int64

  /// Java method `getReceivedSvTimeUncertaintyNanos`.
  ///
  /// ### Java method signature
  /// ```java
  /// public long android.location.GnssMeasurement.getReceivedSvTimeUncertaintyNanos()
  /// ```
@JavaMethod
  open func getReceivedSvTimeUncertaintyNanos() -> Int64

  /// Java method `getPseudorangeRateMetersPerSecond`.
  ///
  /// ### Java method signature
  /// ```java
  /// public double android.location.GnssMeasurement.getPseudorangeRateMetersPerSecond()
  /// ```
@JavaMethod
  open func getPseudorangeRateMetersPerSecond() -> Double

  /// Java method `getAccumulatedDeltaRangeState`.
  ///
  /// ### Java method signature
  /// ```java
  /// public int android.location.GnssMeasurement.getAccumulatedDeltaRangeState()
  /// ```
@JavaMethod
  open func getAccumulatedDeltaRangeState() -> Int32

  /// Java method `getAccumulatedDeltaRangeMeters`.
  ///
  /// ### Java method signature
  /// ```java
  /// public double android.location.GnssMeasurement.getAccumulatedDeltaRangeMeters()
  /// ```
@JavaMethod
  open func getAccumulatedDeltaRangeMeters() -> Double

  /// Java method `hasCarrierPhaseUncertainty`.
  ///
  /// ### Java method signature
  /// ```java
  /// public boolean android.location.GnssMeasurement.hasCarrierPhaseUncertainty()
  /// ```
@JavaMethod
  open func hasCarrierPhaseUncertainty() -> Bool

  /// Java method `getCarrierPhaseUncertainty`.
  ///
  /// ### Java method signature
  /// ```java
  /// public double android.location.GnssMeasurement.getCarrierPhaseUncertainty()
  /// ```
@JavaMethod
  open func getCarrierPhaseUncertainty() -> Double

  /// Java method `getMultipathIndicator`.
  ///
  /// ### Java method signature
  /// ```java
  /// public int android.location.GnssMeasurement.getMultipathIndicator()
  /// ```
@JavaMethod
  open func getMultipathIndicator() -> Int32

  /// Java method `hasAutomaticGainControlLevelDb`.
  ///
  /// ### Java method signature
  /// ```java
  /// public boolean android.location.GnssMeasurement.hasAutomaticGainControlLevelDb()
  /// ```
@available(Android 26, *)
@JavaMethod
  open func hasAutomaticGainControlLevelDb() -> Bool

  /// Java method `getAutomaticGainControlLevelDb`.
  ///
  /// ### Java method signature
  /// ```java
  /// public double android.location.GnssMeasurement.getAutomaticGainControlLevelDb()
  /// ```
@available(Android 26, *)
@JavaMethod
  open func getAutomaticGainControlLevelDb() -> Double

  /// Java method `hasFullInterSignalBiasNanos`.
  ///
  /// ### Java method signature
  /// ```java
  /// public boolean android.location.GnssMeasurement.hasFullInterSignalBiasNanos()
  /// ```
@available(Android 31, *)
@JavaMethod
  open func hasFullInterSignalBiasNanos() -> Bool

  /// Java method `getFullInterSignalBiasNanos`.
  ///
  /// ### Java method signature
  /// ```java
  /// public double android.location.GnssMeasurement.getFullInterSignalBiasNanos()
  /// ```
@available(Android 31, *)
@JavaMethod
  open func getFullInterSignalBiasNanos() -> Double

  /// Java method `hasSatelliteInterSignalBiasNanos`.
  ///
  /// ### Java method signature
  /// ```java
  /// public boolean android.location.GnssMeasurement.hasSatelliteInterSignalBiasNanos()
  /// ```
@available(Android 31, *)
@JavaMethod
  open func hasSatelliteInterSignalBiasNanos() -> Bool

  /// Java method `getSatelliteInterSignalBiasNanos`.
  ///
  /// ### Java method signature
  /// ```java
  /// public double android.location.GnssMeasurement.getSatelliteInterSignalBiasNanos()
  /// ```
@available(Android 31, *)
@JavaMethod
  open func getSatelliteInterSignalBiasNanos() -> Double

  /// Java method `getPseudorangeRateUncertaintyMetersPerSecond`.
  ///
  /// ### Java method signature
  /// ```java
  /// public double android.location.GnssMeasurement.getPseudorangeRateUncertaintyMetersPerSecond()
  /// ```
@JavaMethod
  open func getPseudorangeRateUncertaintyMetersPerSecond() -> Double

  /// Java method `getAccumulatedDeltaRangeUncertaintyMeters`.
  ///
  /// ### Java method signature
  /// ```java
  /// public double android.location.GnssMeasurement.getAccumulatedDeltaRangeUncertaintyMeters()
  /// ```
@JavaMethod
  open func getAccumulatedDeltaRangeUncertaintyMeters() -> Double

  /// Java method `hasFullInterSignalBiasUncertaintyNanos`.
  ///
  /// ### Java method signature
  /// ```java
  /// public boolean android.location.GnssMeasurement.hasFullInterSignalBiasUncertaintyNanos()
  /// ```
@available(Android 31, *)
@JavaMethod
  open func hasFullInterSignalBiasUncertaintyNanos() -> Bool

  /// Java method `getFullInterSignalBiasUncertaintyNanos`.
  ///
  /// ### Java method signature
  /// ```java
  /// public double android.location.GnssMeasurement.getFullInterSignalBiasUncertaintyNanos()
  /// ```
@available(Android 31, *)
@JavaMethod
  open func getFullInterSignalBiasUncertaintyNanos() -> Double

  /// Java method `hasSatelliteInterSignalBiasUncertaintyNanos`.
  ///
  /// ### Java method signature
  /// ```java
  /// public boolean android.location.GnssMeasurement.hasSatelliteInterSignalBiasUncertaintyNanos()
  /// ```
@available(Android 31, *)
@JavaMethod
  open func hasSatelliteInterSignalBiasUncertaintyNanos() -> Bool

  /// Java method `getSatelliteInterSignalBiasUncertaintyNanos`.
  ///
  /// ### Java method signature
  /// ```java
  /// public double android.location.GnssMeasurement.getSatelliteInterSignalBiasUncertaintyNanos()
  /// ```
@available(Android 31, *)
@JavaMethod
  open func getSatelliteInterSignalBiasUncertaintyNanos() -> Double

  /// Java method `describeContents`.
  ///
  /// ### Java method signature
  /// ```java
  /// public int android.location.GnssMeasurement.describeContents()
  /// ```
@JavaMethod
  open func describeContents() -> Int32

  /// Java method `writeToParcel`.
  ///
  /// ### Java method signature
  /// ```java
  /// public void android.location.GnssMeasurement.writeToParcel(android.os.Parcel,int)
  /// ```
@JavaMethod
  open func writeToParcel(_ arg0: Parcel?, _ arg1: Int32)

  /// Java method `getSvid`.
  ///
  /// ### Java method signature
  /// ```java
  /// public int android.location.GnssMeasurement.getSvid()
  /// ```
@JavaMethod
  open func getSvid() -> Int32

  /// Java method `getCn0DbHz`.
  ///
  /// ### Java method signature
  /// ```java
  /// public double android.location.GnssMeasurement.getCn0DbHz()
  /// ```
@JavaMethod
  open func getCn0DbHz() -> Double

  /// Java method `hasBasebandCn0DbHz`.
  ///
  /// ### Java method signature
  /// ```java
  /// public boolean android.location.GnssMeasurement.hasBasebandCn0DbHz()
  /// ```
@available(Android 30, *)
@JavaMethod
  open func hasBasebandCn0DbHz() -> Bool

  /// Java method `getBasebandCn0DbHz`.
  ///
  /// ### Java method signature
  /// ```java
  /// public double android.location.GnssMeasurement.getBasebandCn0DbHz()
  /// ```
@available(Android 30, *)
@JavaMethod
  open func getBasebandCn0DbHz() -> Double

  /// Java method `getCodeType`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.lang.String android.location.GnssMeasurement.getCodeType()
  /// ```
@available(Android 29, *)
@JavaMethod
  open func getCodeType() -> String

  /// Java method `getTimeOffsetNanos`.
  ///
  /// ### Java method signature
  /// ```java
  /// public double android.location.GnssMeasurement.getTimeOffsetNanos()
  /// ```
@JavaMethod
  open func getTimeOffsetNanos() -> Double

  /// Java method `hasCarrierCycles`.
  ///
  /// ### Java method signature
  /// ```java
  /// public boolean android.location.GnssMeasurement.hasCarrierCycles()
  /// ```
@JavaMethod
  open func hasCarrierCycles() -> Bool

  /// Java method `getCarrierCycles`.
  ///
  /// ### Java method signature
  /// ```java
  /// public long android.location.GnssMeasurement.getCarrierCycles()
  /// ```
@JavaMethod
  open func getCarrierCycles() -> Int64

  /// Java method `hasCarrierPhase`.
  ///
  /// ### Java method signature
  /// ```java
  /// public boolean android.location.GnssMeasurement.hasCarrierPhase()
  /// ```
@JavaMethod
  open func hasCarrierPhase() -> Bool

  /// Java method `getCarrierPhase`.
  ///
  /// ### Java method signature
  /// ```java
  /// public double android.location.GnssMeasurement.getCarrierPhase()
  /// ```
@JavaMethod
  open func getCarrierPhase() -> Double

  /// Java method `hasSnrInDb`.
  ///
  /// ### Java method signature
  /// ```java
  /// public boolean android.location.GnssMeasurement.hasSnrInDb()
  /// ```
@JavaMethod
  open func hasSnrInDb() -> Bool

  /// Java method `getSnrInDb`.
  ///
  /// ### Java method signature
  /// ```java
  /// public double android.location.GnssMeasurement.getSnrInDb()
  /// ```
@JavaMethod
  open func getSnrInDb() -> Double

  /// Java method `hasCodeType`.
  ///
  /// ### Java method signature
  /// ```java
  /// public boolean android.location.GnssMeasurement.hasCodeType()
  /// ```
@available(Android 29, *)
@JavaMethod
  open func hasCodeType() -> Bool

  /// Java method `toString`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.lang.String android.location.GnssMeasurement.toString()
  /// ```
@JavaMethod
  open override func toString() -> String

  /// Java method `getState`.
  ///
  /// ### Java method signature
  /// ```java
  /// public int android.location.GnssMeasurement.getState()
  /// ```
@JavaMethod
  open func getState() -> Int32
}
@available(Android 24, *)
extension JavaClass<GnssMeasurement> {
  @JavaStaticField(isFinal: true)
  public var ADR_STATE_CYCLE_SLIP: Int32

  @JavaStaticField(isFinal: true)
  public var ADR_STATE_HALF_CYCLE_REPORTED: Int32

  @JavaStaticField(isFinal: true)
  public var ADR_STATE_HALF_CYCLE_RESOLVED: Int32

  @JavaStaticField(isFinal: true)
  public var ADR_STATE_RESET: Int32

  @JavaStaticField(isFinal: true)
  public var ADR_STATE_UNKNOWN: Int32

  @JavaStaticField(isFinal: true)
  public var ADR_STATE_VALID: Int32

  @JavaStaticField(isFinal: true)
  public var CREATOR: Parcelable.Creator<GnssMeasurement>!

  @JavaStaticField(isFinal: true)
  public var MULTIPATH_INDICATOR_DETECTED: Int32

  @JavaStaticField(isFinal: true)
  public var MULTIPATH_INDICATOR_NOT_DETECTED: Int32

  @JavaStaticField(isFinal: true)
  public var MULTIPATH_INDICATOR_UNKNOWN: Int32

  @JavaStaticField(isFinal: true)
  public var STATE_2ND_CODE_LOCK: Int32

  @JavaStaticField(isFinal: true)
  public var STATE_BDS_D2_BIT_SYNC: Int32

  @JavaStaticField(isFinal: true)
  public var STATE_BDS_D2_SUBFRAME_SYNC: Int32

  @JavaStaticField(isFinal: true)
  public var STATE_BIT_SYNC: Int32

  @JavaStaticField(isFinal: true)
  public var STATE_CODE_LOCK: Int32

  @JavaStaticField(isFinal: true)
  public var STATE_GAL_E1BC_CODE_LOCK: Int32

  @JavaStaticField(isFinal: true)
  public var STATE_GAL_E1B_PAGE_SYNC: Int32

  @JavaStaticField(isFinal: true)
  public var STATE_GAL_E1C_2ND_CODE_LOCK: Int32

  @JavaStaticField(isFinal: true)
  public var STATE_GLO_STRING_SYNC: Int32

  @JavaStaticField(isFinal: true)
  public var STATE_GLO_TOD_DECODED: Int32

  @JavaStaticField(isFinal: true)
  public var STATE_GLO_TOD_KNOWN: Int32

  @JavaStaticField(isFinal: true)
  public var STATE_MSEC_AMBIGUOUS: Int32

  @JavaStaticField(isFinal: true)
  public var STATE_SBAS_SYNC: Int32

  @JavaStaticField(isFinal: true)
  public var STATE_SUBFRAME_SYNC: Int32

  @JavaStaticField(isFinal: true)
  public var STATE_SYMBOL_SYNC: Int32

  @JavaStaticField(isFinal: true)
  public var STATE_TOW_DECODED: Int32

  @JavaStaticField(isFinal: true)
  public var STATE_TOW_KNOWN: Int32

  @JavaStaticField(isFinal: true)
  public var STATE_UNKNOWN: Int32
}
