// Auto-generated by Java-to-Swift wrapper generator.
import AndroidOS
import CSwiftJavaJNI
import SwiftJava

@JavaClass("android.location.GnssAutomaticGainControl", implements: Parcelable.self)
open class GnssAutomaticGainControl: JavaObject {
  /// Java method `getConstellationType`.
  ///
  /// ### Java method signature
  /// ```java
  /// public int android.location.GnssAutomaticGainControl.getConstellationType()
  /// ```
@JavaMethod
  open func getConstellationType() -> Int32

  /// Java method `getCarrierFrequencyHz`.
  ///
  /// ### Java method signature
  /// ```java
  /// public long android.location.GnssAutomaticGainControl.getCarrierFrequencyHz()
  /// ```
@JavaMethod
  open func getCarrierFrequencyHz() -> Int64

  /// Java method `describeContents`.
  ///
  /// ### Java method signature
  /// ```java
  /// public int android.location.GnssAutomaticGainControl.describeContents()
  /// ```
@JavaMethod
  open func describeContents() -> Int32

  /// Java method `writeToParcel`.
  ///
  /// ### Java method signature
  /// ```java
  /// public void android.location.GnssAutomaticGainControl.writeToParcel(android.os.Parcel,int)
  /// ```
@JavaMethod
  open func writeToParcel(_ arg0: Parcel?, _ arg1: Int32)

  /// Java method `getLevelDb`.
  ///
  /// ### Java method signature
  /// ```java
  /// public double android.location.GnssAutomaticGainControl.getLevelDb()
  /// ```
@JavaMethod
  open func getLevelDb() -> Double

  /// Java method `equals`.
  ///
  /// ### Java method signature
  /// ```java
  /// public boolean android.location.GnssAutomaticGainControl.equals(java.lang.Object)
  /// ```
@JavaMethod
  open override func equals(_ arg0: JavaObject?) -> Bool

  /// Java method `toString`.
  ///
  /// ### Java method signature
  /// ```java
  /// public java.lang.String android.location.GnssAutomaticGainControl.toString()
  /// ```
@JavaMethod
  open override func toString() -> String

  /// Java method `hashCode`.
  ///
  /// ### Java method signature
  /// ```java
  /// public int android.location.GnssAutomaticGainControl.hashCode()
  /// ```
@JavaMethod
  open override func hashCode() -> Int32
}
extension JavaClass<GnssAutomaticGainControl> {
  @JavaStaticField(isFinal: true)
  public var CREATOR: Parcelable.Creator<GnssAutomaticGainControl>!
}
