// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

@JavaClass("android.util.DebugUtils")
open class DebugUtils: JavaObject {

}
extension JavaClass<DebugUtils> {
  @JavaStaticMethod
  public func isObjectSelected(_ arg0: JavaObject?) -> Bool
}
