// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

@JavaClass("android.util.MonthDisplayHelper")
open class MonthDisplayHelper: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: Int32, _ arg1: Int32, _ arg2: Int32, environment: JNIEnvironment? = nil)

  @JavaMethod
  @_nonoverride public convenience init(_ arg0: Int32, _ arg1: Int32, environment: JNIEnvironment? = nil)

  @JavaMethod
  open func getWeekStartDay() -> Int32

  @JavaMethod
  open func getFirstDayOfMonth() -> Int32

  @JavaMethod
  open func getNumberOfDaysInMonth() -> Int32

  @JavaMethod
  open func getDigitsForRow(_ arg0: Int32) -> [Int32]

  @JavaMethod
  open func getDayAt(_ arg0: Int32, _ arg1: Int32) -> Int32

  @JavaMethod
  open func getRowOf(_ arg0: Int32) -> Int32

  @JavaMethod
  open func getColumnOf(_ arg0: Int32) -> Int32

  @JavaMethod
  open func previousMonth()

  @JavaMethod
  open func nextMonth()

  @JavaMethod
  open func isWithinCurrentMonth(_ arg0: Int32, _ arg1: Int32) -> Bool

  @JavaMethod
  open func getOffset() -> Int32

  @JavaMethod
  open func getYear() -> Int32

  @JavaMethod
  open func getMonth() -> Int32
}
