// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

@JavaClass("java.io.BufferedReader")
open class BufferedReader: Reader {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: Reader?, environment: JNIEnvironment? = nil)

  @JavaMethod
  @_nonoverride public convenience init(_ arg0: Reader?, _ arg1: Int32, environment: JNIEnvironment? = nil)

  @JavaMethod
  open override func ready() throws -> Bool

  @JavaMethod
  open override func reset() throws

  @JavaMethod
  open func readLine() throws -> String

  @JavaMethod
  open override func close() throws

  @JavaMethod
  open override func mark(_ arg0: Int32) throws

  @JavaMethod
  open override func read() throws -> Int32

  @JavaMethod
  open override func read(_ arg0: [UInt16], _ arg1: Int32, _ arg2: Int32) throws -> Int32

  @JavaMethod
  open override func skip(_ arg0: Int64) throws -> Int64

  @JavaMethod
  open override func markSupported() -> Bool
}
