// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

@JavaInterface("java.io.Externalizable", extends: Serializable.self)
public struct Externalizable {
  @JavaMethod
  public func writeExternal(_ arg0: ObjectOutput?) throws

  @JavaMethod
  public func readExternal(_ arg0: ObjectInput?) throws
}
