// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

@JavaClass("java.io.PipedOutputStream")
open class PipedOutputStream: OutputStream {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: PipedInputStream?, environment: JNIEnvironment? = nil) throws

  @JavaMethod
  @_nonoverride public convenience init(environment: JNIEnvironment? = nil)

  @JavaMethod
  open func connect(_ arg0: PipedInputStream?) throws

  @JavaMethod
  open override func flush() throws

  @JavaMethod
  open override func write(_ arg0: [Int8], _ arg1: Int32, _ arg2: Int32) throws

  @JavaMethod
  open override func write(_ arg0: Int32) throws

  @JavaMethod
  open override func close() throws
}
