// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava
import CSwiftJavaJNI

/// Thrown when a `Parcelable` encounters an error during marshalling or unmarshalling,
/// such as when a class cannot be found or data is malformed.
///
/// See also: [android.os.BadParcelableException](https://developer.android.com/reference/android/os/BadParcelableException)
@JavaClass("android.os.BadParcelableException")
open class BadParcelableException: RuntimeException {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: String, environment: JNIEnvironment? = nil)

  @JavaMethod
  @_nonoverride public convenience init(_ arg0: Exception?, environment: JNIEnvironment? = nil)
}
