// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava
import CSwiftJavaJNI

/// Provides information about battery state and charging status.
///
/// Obtain an instance via `Context.getSystemService(Context.BATTERY_SERVICE)`.
///
/// See [android.os.BatteryManager](https://developer.android.com/reference/android/os/BatteryManager)
@available(Android 21, *)
@JavaClass("android.os.BatteryManager")
open class BatteryManager: JavaObject {
  /// Returns whether the device is currently charging.
  @JavaMethod
  open func isCharging() -> Bool

  /// Returns an estimate of how long until the battery is fully charged, in milliseconds, or `-1` if unknown.
  @JavaMethod
  open func computeChargeTimeRemaining() -> Int64

  /// Returns the value of the given integer battery property (e.g., `BATTERY_PROPERTY_CAPACITY`).
  @JavaMethod
  open func getIntProperty(_ arg0: Int32) -> Int32

  /// Returns the value of the given long battery property (e.g., `BATTERY_PROPERTY_ENERGY_COUNTER`).
  @JavaMethod
  open func getLongProperty(_ arg0: Int32) -> Int64
}
extension JavaClass<BatteryManager> {
  @JavaStaticField(isFinal: true)
  public var ACTION_CHARGING: String

  @JavaStaticField(isFinal: true)
  public var ACTION_DISCHARGING: String

  @JavaStaticField(isFinal: true)
  public var BATTERY_HEALTH_COLD: Int32

  @JavaStaticField(isFinal: true)
  public var BATTERY_HEALTH_DEAD: Int32

  @JavaStaticField(isFinal: true)
  public var BATTERY_HEALTH_GOOD: Int32

  @JavaStaticField(isFinal: true)
  public var BATTERY_HEALTH_OVERHEAT: Int32

  @JavaStaticField(isFinal: true)
  public var BATTERY_HEALTH_OVER_VOLTAGE: Int32

  @JavaStaticField(isFinal: true)
  public var BATTERY_HEALTH_UNKNOWN: Int32

  @JavaStaticField(isFinal: true)
  public var BATTERY_HEALTH_UNSPECIFIED_FAILURE: Int32

  @JavaStaticField(isFinal: true)
  public var BATTERY_PLUGGED_AC: Int32

  @JavaStaticField(isFinal: true)
  public var BATTERY_PLUGGED_DOCK: Int32

  @JavaStaticField(isFinal: true)
  public var BATTERY_PLUGGED_USB: Int32

  @JavaStaticField(isFinal: true)
  public var BATTERY_PLUGGED_WIRELESS: Int32

  @JavaStaticField(isFinal: true)
  public var BATTERY_PROPERTY_CAPACITY: Int32

  @JavaStaticField(isFinal: true)
  public var BATTERY_PROPERTY_CHARGE_COUNTER: Int32

  @JavaStaticField(isFinal: true)
  public var BATTERY_PROPERTY_CURRENT_AVERAGE: Int32

  @JavaStaticField(isFinal: true)
  public var BATTERY_PROPERTY_CURRENT_NOW: Int32

  @JavaStaticField(isFinal: true)
  public var BATTERY_PROPERTY_ENERGY_COUNTER: Int32

  @JavaStaticField(isFinal: true)
  public var BATTERY_PROPERTY_STATUS: Int32

  @JavaStaticField(isFinal: true)
  public var BATTERY_STATUS_CHARGING: Int32

  @JavaStaticField(isFinal: true)
  public var BATTERY_STATUS_DISCHARGING: Int32

  @JavaStaticField(isFinal: true)
  public var BATTERY_STATUS_FULL: Int32

  @JavaStaticField(isFinal: true)
  public var BATTERY_STATUS_NOT_CHARGING: Int32

  @JavaStaticField(isFinal: true)
  public var BATTERY_STATUS_UNKNOWN: Int32

  @JavaStaticField(isFinal: true)
  public var EXTRA_BATTERY_LOW: String

  @JavaStaticField(isFinal: true)
  public var EXTRA_HEALTH: String

  @JavaStaticField(isFinal: true)
  public var EXTRA_ICON_SMALL: String

  @JavaStaticField(isFinal: true)
  public var EXTRA_LEVEL: String

  @JavaStaticField(isFinal: true)
  public var EXTRA_PLUGGED: String

  @JavaStaticField(isFinal: true)
  public var EXTRA_PRESENT: String

  @JavaStaticField(isFinal: true)
  public var EXTRA_SCALE: String

  @JavaStaticField(isFinal: true)
  public var EXTRA_STATUS: String

  @JavaStaticField(isFinal: true)
  public var EXTRA_TECHNOLOGY: String

  @JavaStaticField(isFinal: true)
  public var EXTRA_TEMPERATURE: String

  @JavaStaticField(isFinal: true)
  public var EXTRA_VOLTAGE: String
}
