// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

extension Build {
  @JavaClass("android.os.Build$VERSION_CODES")
  open class VERSION_CODES: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(environment: JNIEnvironment? = nil)
  }
}
extension JavaClass<Build.VERSION_CODES> {
  @JavaStaticField(isFinal: true)
  public var BASE: Int32

  @JavaStaticField(isFinal: true)
  public var BASE_1_1: Int32

  @JavaStaticField(isFinal: true)
  public var CUPCAKE: Int32

  @JavaStaticField(isFinal: true)
  public var CUR_DEVELOPMENT: Int32

  @JavaStaticField(isFinal: true)
  public var DONUT: Int32

  @JavaStaticField(isFinal: true)
  public var ECLAIR: Int32

  @JavaStaticField(isFinal: true)
  public var ECLAIR_0_1: Int32

  @JavaStaticField(isFinal: true)
  public var ECLAIR_MR1: Int32

  @JavaStaticField(isFinal: true)
  public var FROYO: Int32

  @JavaStaticField(isFinal: true)
  public var GINGERBREAD: Int32

  @JavaStaticField(isFinal: true)
  public var GINGERBREAD_MR1: Int32

  @JavaStaticField(isFinal: true)
  public var HONEYCOMB: Int32

  @JavaStaticField(isFinal: true)
  public var HONEYCOMB_MR1: Int32

  @JavaStaticField(isFinal: true)
  public var HONEYCOMB_MR2: Int32

  @JavaStaticField(isFinal: true)
  public var ICE_CREAM_SANDWICH: Int32

  @JavaStaticField(isFinal: true)
  public var ICE_CREAM_SANDWICH_MR1: Int32

  @JavaStaticField(isFinal: true)
  public var JELLY_BEAN: Int32

  @JavaStaticField(isFinal: true)
  public var JELLY_BEAN_MR1: Int32

  @JavaStaticField(isFinal: true)
  public var JELLY_BEAN_MR2: Int32

  @JavaStaticField(isFinal: true)
  public var KITKAT: Int32

  @JavaStaticField(isFinal: true)
  public var KITKAT_WATCH: Int32

  @JavaStaticField(isFinal: true)
  public var LOLLIPOP: Int32

  @JavaStaticField(isFinal: true)
  public var LOLLIPOP_MR1: Int32

  @JavaStaticField(isFinal: true)
  public var M: Int32

  @JavaStaticField(isFinal: true)
  public var N: Int32

  @JavaStaticField(isFinal: true)
  public var N_MR1: Int32

  @JavaStaticField(isFinal: true)
  public var O: Int32

  @JavaStaticField(isFinal: true)
  public var O_MR1: Int32

  @JavaStaticField(isFinal: true)
  public var P: Int32

  @JavaStaticField(isFinal: true)
  public var Q: Int32

  @JavaStaticField(isFinal: true)
  public var R: Int32

  @JavaStaticField(isFinal: true)
  public var S: Int32

  @JavaStaticField(isFinal: true)
  public var S_V2: Int32

  @JavaStaticField(isFinal: true)
  public var TIRAMISU: Int32
}
