// Auto-generated by Java-to-Swift wrapper generator.
import JavaLang
import JavaKit
import JavaRuntime

@JavaClass("android.os.Looper")
open class Looper: JavaObject {
  @JavaMethod
  open func isCurrentThread() -> Bool

  @JavaMethod
  open func quit()

  @JavaMethod
  open func quitSafely()

  @JavaMethod
  open func getThread() -> Thread!

  @JavaMethod
  open override func toString() -> String

  @JavaMethod
  open func getQueue() -> MessageQueue!
}
extension JavaClass<Looper> {
  @JavaStaticMethod
  public func prepareMainLooper()

  @JavaStaticMethod
  public func getMainLooper() -> Looper!

  @JavaStaticMethod
  public func myLooper() -> Looper!

  @JavaStaticMethod
  public func myQueue() -> MessageQueue!

  @JavaStaticMethod
  public func prepare()

  @JavaStaticMethod
  public func loop()
}
