// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

@JavaInterface("android.os.OutcomeReceiver")
public struct OutcomeReceiver<R: AnyJavaObject, E: AnyJavaObject> {
  @JavaMethod
  public func onResult(_ arg0: JavaObject?)

  @JavaMethod
  public func onError(_ arg0: Throwable?)
}
