// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

@JavaClass("android.os.PerformanceHintManager")
open class PerformanceHintManager: JavaObject {
  @JavaMethod
  open func createHintSession(_ arg0: [Int32], _ arg1: Int64) -> PerformanceHintManager.Session!

  @JavaMethod
  open func getPreferredUpdateRateNanos() -> Int64
}
