// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

extension PowerManager {
  @JavaInterface("android.os.PowerManager$WakeLockStateListener")
  public struct WakeLockStateListener {
  @JavaMethod
  public func onStateChanged(_ arg0: Bool)
  }
}
