// Auto-generated by Java-to-Swift wrapper generator.
import JavaUtil
import JavaLangUtil
import SwiftJava
import CSwiftJavaJNI

@JavaClass("android.os.ext.SdkExtensions")
open class SdkExtensions: JavaObject {

}
extension JavaClass<SdkExtensions> {
  @JavaStaticMethod
  public func getExtensionVersion(_ arg0: Int32) -> Int32

  @JavaStaticMethod
  public func getAllExtensionVersions() -> Map<JavaInteger, JavaInteger>!
}
