// Auto-generated by Java-to-Swift wrapper generator.
import AndroidJavaIO
import AndroidJavaUtil
import JavaKit
import JavaRuntime

@JavaClass("android.os.storage.StorageVolume", implements: Parcelable.self)
open class StorageVolume: JavaObject {
  @JavaMethod
  open func getDirectory() -> File!

  @JavaMethod
  open func isPrimary() -> Bool

  @JavaMethod
  open func isRemovable() -> Bool

  @JavaMethod
  open func isEmulated() -> Bool

  @JavaMethod
  open func getStorageUuid() -> UUID!

  @JavaMethod
  open func getMediaStoreVolumeName() -> String

  @JavaMethod
  open func describeContents() -> Int32

  @JavaMethod
  open func writeToParcel(_ arg0: Parcel?, _ arg1: Int32)

  @JavaMethod
  open func getUuid() -> String

  @JavaMethod
  open override func equals(_ arg0: JavaObject?) -> Bool

  @JavaMethod
  open override func toString() -> String

  @JavaMethod
  open override func hashCode() -> Int32

  @JavaMethod
  open func getState() -> String

  @JavaMethod
  open func getOwner() -> UserHandle!
}
extension JavaClass<StorageVolume> {
  @JavaStaticField(isFinal: true)
  public var CREATOR: Parcelable.Creator<StorageVolume>!

  @JavaStaticField(isFinal: true)
  public var EXTRA_STORAGE_VOLUME: String

  @JavaStaticField(isFinal: true)
  public var CONTENTS_FILE_DESCRIPTOR: Int32

  @JavaStaticField(isFinal: true)
  public var PARCELABLE_WRITE_RETURN_VALUE: Int32
}
