// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava
import CSwiftJavaJNI

@JavaClass("android.os.strictmode.UntaggedSocketViolation")
open class UntaggedSocketViolation: Violation {

}
