// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

extension UserManager {
  @JavaClass("android.os.UserManager$UserOperationException")
  open class UserOperationException: RuntimeException {
  @JavaMethod
  open func getUserOperationResult() -> Int32
  }
}
