// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

extension R {
  @JavaClass("android.R$style")
  open class style: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(environment: JNIEnvironment? = nil)
  }
}
extension JavaClass<R.style> {
  @JavaStaticField(isFinal: true)
  public var Animation: Int32

  @JavaStaticField(isFinal: true)
  public var Animation_Activity: Int32

  @JavaStaticField(isFinal: true)
  public var Animation_Dialog: Int32

  @JavaStaticField(isFinal: true)
  public var Animation_InputMethod: Int32

  @JavaStaticField(isFinal: true)
  public var Animation_Toast: Int32

  @JavaStaticField(isFinal: true)
  public var Animation_Translucent: Int32

  @JavaStaticField(isFinal: true)
  public var DeviceDefault_ButtonBar: Int32

  @JavaStaticField(isFinal: true)
  public var DeviceDefault_ButtonBar_AlertDialog: Int32

  @JavaStaticField(isFinal: true)
  public var DeviceDefault_Light_ButtonBar: Int32

  @JavaStaticField(isFinal: true)
  public var DeviceDefault_Light_ButtonBar_AlertDialog: Int32

  @JavaStaticField(isFinal: true)
  public var DeviceDefault_Light_SegmentedButton: Int32

  @JavaStaticField(isFinal: true)
  public var DeviceDefault_SegmentedButton: Int32

  @JavaStaticField(isFinal: true)
  public var Holo_ButtonBar: Int32

  @JavaStaticField(isFinal: true)
  public var Holo_ButtonBar_AlertDialog: Int32

  @JavaStaticField(isFinal: true)
  public var Holo_Light_ButtonBar: Int32

  @JavaStaticField(isFinal: true)
  public var Holo_Light_ButtonBar_AlertDialog: Int32

  @JavaStaticField(isFinal: true)
  public var Holo_Light_SegmentedButton: Int32

  @JavaStaticField(isFinal: true)
  public var Holo_SegmentedButton: Int32

  @JavaStaticField(isFinal: true)
  public var MediaButton: Int32

  @JavaStaticField(isFinal: true)
  public var MediaButton_Ffwd: Int32

  @JavaStaticField(isFinal: true)
  public var MediaButton_Next: Int32

  @JavaStaticField(isFinal: true)
  public var MediaButton_Pause: Int32

  @JavaStaticField(isFinal: true)
  public var MediaButton_Play: Int32

  @JavaStaticField(isFinal: true)
  public var MediaButton_Previous: Int32

  @JavaStaticField(isFinal: true)
  public var MediaButton_Rew: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_DeviceDefault: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_DeviceDefault_DialogWindowTitle: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_DeviceDefault_Headline: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_DeviceDefault_Inverse: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_DeviceDefault_Large: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_DeviceDefault_Large_Inverse: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_DeviceDefault_Medium: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_DeviceDefault_Medium_Inverse: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_DeviceDefault_SearchResult_Subtitle: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_DeviceDefault_SearchResult_Title: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_DeviceDefault_Small: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_DeviceDefault_Small_Inverse: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_DeviceDefault_Widget: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_DeviceDefault_Widget_ActionBar_Menu: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_DeviceDefault_Widget_ActionBar_Subtitle: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_DeviceDefault_Widget_ActionBar_Subtitle_Inverse: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_DeviceDefault_Widget_ActionBar_Title: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_DeviceDefault_Widget_ActionBar_Title_Inverse: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_DeviceDefault_Widget_ActionMode_Subtitle: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_DeviceDefault_Widget_ActionMode_Subtitle_Inverse: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_DeviceDefault_Widget_ActionMode_Title: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_DeviceDefault_Widget_ActionMode_Title_Inverse: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_DeviceDefault_Widget_Button: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_DeviceDefault_Widget_DropDownHint: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_DeviceDefault_Widget_DropDownItem: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_DeviceDefault_Widget_EditText: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_DeviceDefault_Widget_IconMenu_Item: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_DeviceDefault_Widget_PopupMenu: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_DeviceDefault_Widget_PopupMenu_Large: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_DeviceDefault_Widget_PopupMenu_Small: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_DeviceDefault_Widget_TabWidget: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_DeviceDefault_Widget_TextView: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_DeviceDefault_Widget_TextView_PopupMenu: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_DeviceDefault_Widget_TextView_SpinnerItem: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_DeviceDefault_WindowTitle: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_DialogWindowTitle: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_Holo: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_Holo_DialogWindowTitle: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_Holo_Inverse: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_Holo_Large: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_Holo_Large_Inverse: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_Holo_Medium: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_Holo_Medium_Inverse: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_Holo_SearchResult_Subtitle: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_Holo_SearchResult_Title: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_Holo_Small: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_Holo_Small_Inverse: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_Holo_Widget: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_Holo_Widget_ActionBar_Menu: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_Holo_Widget_ActionBar_Subtitle: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_Holo_Widget_ActionBar_Subtitle_Inverse: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_Holo_Widget_ActionBar_Title: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_Holo_Widget_ActionBar_Title_Inverse: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_Holo_Widget_ActionMode_Subtitle: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_Holo_Widget_ActionMode_Subtitle_Inverse: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_Holo_Widget_ActionMode_Title: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_Holo_Widget_ActionMode_Title_Inverse: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_Holo_Widget_Button: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_Holo_Widget_DropDownHint: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_Holo_Widget_DropDownItem: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_Holo_Widget_EditText: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_Holo_Widget_IconMenu_Item: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_Holo_Widget_PopupMenu: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_Holo_Widget_PopupMenu_Large: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_Holo_Widget_PopupMenu_Small: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_Holo_Widget_TabWidget: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_Holo_Widget_TextView: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_Holo_Widget_TextView_PopupMenu: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_Holo_Widget_TextView_SpinnerItem: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_Holo_WindowTitle: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_Inverse: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_Large: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_Large_Inverse: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_Material: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_Material_Body1: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_Material_Body2: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_Material_Button: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_Material_Caption: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_Material_DialogWindowTitle: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_Material_Display1: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_Material_Display2: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_Material_Display3: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_Material_Display4: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_Material_Headline: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_Material_Inverse: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_Material_Large: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_Material_Large_Inverse: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_Material_Medium: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_Material_Medium_Inverse: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_Material_Menu: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_Material_Notification: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_Material_Notification_Emphasis: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_Material_Notification_Info: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_Material_Notification_Line2: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_Material_Notification_Time: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_Material_Notification_Title: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_Material_SearchResult_Subtitle: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_Material_SearchResult_Title: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_Material_Small: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_Material_Small_Inverse: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_Material_Subhead: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_Material_Title: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_Material_Widget: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_Material_Widget_ActionBar_Menu: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_Material_Widget_ActionBar_Subtitle: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_Material_Widget_ActionBar_Subtitle_Inverse: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_Material_Widget_ActionBar_Title: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_Material_Widget_ActionBar_Title_Inverse: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_Material_Widget_ActionMode_Subtitle: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_Material_Widget_ActionMode_Subtitle_Inverse: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_Material_Widget_ActionMode_Title: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_Material_Widget_ActionMode_Title_Inverse: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_Material_Widget_Button: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_Material_Widget_Button_Borderless_Colored: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_Material_Widget_Button_Colored: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_Material_Widget_Button_Inverse: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_Material_Widget_DropDownHint: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_Material_Widget_DropDownItem: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_Material_Widget_EditText: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_Material_Widget_IconMenu_Item: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_Material_Widget_PopupMenu: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_Material_Widget_PopupMenu_Large: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_Material_Widget_PopupMenu_Small: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_Material_Widget_TabWidget: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_Material_Widget_TextView: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_Material_Widget_TextView_PopupMenu: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_Material_Widget_TextView_SpinnerItem: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_Material_Widget_Toolbar_Subtitle: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_Material_Widget_Toolbar_Title: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_Material_WindowTitle: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_Medium: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_Medium_Inverse: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_Small: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_Small_Inverse: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_StatusBar_EventContent: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_StatusBar_EventContent_Title: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_StatusBar_Icon: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_StatusBar_Title: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_SuggestionHighlight: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_Theme: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_Theme_Dialog: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_Widget: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_Widget_Button: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_Widget_DropDownHint: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_Widget_DropDownItem: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_Widget_EditText: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_Widget_IconMenu_Item: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_Widget_PopupMenu_Large: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_Widget_PopupMenu_Small: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_Widget_TabWidget: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_Widget_TextView: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_Widget_TextView_PopupMenu: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_Widget_TextView_SpinnerItem: Int32

  @JavaStaticField(isFinal: true)
  public var TextAppearance_WindowTitle: Int32

  @JavaStaticField(isFinal: true)
  public var Theme: Int32

  @JavaStaticField(isFinal: true)
  public var ThemeOverlay: Int32

  @JavaStaticField(isFinal: true)
  public var ThemeOverlay_DeviceDefault_Accent_DayNight: Int32

  @JavaStaticField(isFinal: true)
  public var ThemeOverlay_Material: Int32

  @JavaStaticField(isFinal: true)
  public var ThemeOverlay_Material_ActionBar: Int32

  @JavaStaticField(isFinal: true)
  public var ThemeOverlay_Material_Dark: Int32

  @JavaStaticField(isFinal: true)
  public var ThemeOverlay_Material_Dark_ActionBar: Int32

  @JavaStaticField(isFinal: true)
  public var ThemeOverlay_Material_Dialog: Int32

  @JavaStaticField(isFinal: true)
  public var ThemeOverlay_Material_Dialog_Alert: Int32

  @JavaStaticField(isFinal: true)
  public var ThemeOverlay_Material_Light: Int32

  @JavaStaticField(isFinal: true)
  public var Theme_Black: Int32

  @JavaStaticField(isFinal: true)
  public var Theme_Black_NoTitleBar: Int32

  @JavaStaticField(isFinal: true)
  public var Theme_Black_NoTitleBar_Fullscreen: Int32

  @JavaStaticField(isFinal: true)
  public var Theme_DeviceDefault: Int32

  @JavaStaticField(isFinal: true)
  public var Theme_DeviceDefault_DayNight: Int32

  @JavaStaticField(isFinal: true)
  public var Theme_DeviceDefault_Dialog: Int32

  @JavaStaticField(isFinal: true)
  public var Theme_DeviceDefault_DialogWhenLarge: Int32

  @JavaStaticField(isFinal: true)
  public var Theme_DeviceDefault_DialogWhenLarge_NoActionBar: Int32

  @JavaStaticField(isFinal: true)
  public var Theme_DeviceDefault_Dialog_Alert: Int32

  @JavaStaticField(isFinal: true)
  public var Theme_DeviceDefault_Dialog_MinWidth: Int32

  @JavaStaticField(isFinal: true)
  public var Theme_DeviceDefault_Dialog_NoActionBar: Int32

  @JavaStaticField(isFinal: true)
  public var Theme_DeviceDefault_Dialog_NoActionBar_MinWidth: Int32

  @JavaStaticField(isFinal: true)
  public var Theme_DeviceDefault_InputMethod: Int32

  @JavaStaticField(isFinal: true)
  public var Theme_DeviceDefault_Light: Int32

  @JavaStaticField(isFinal: true)
  public var Theme_DeviceDefault_Light_DarkActionBar: Int32

  @JavaStaticField(isFinal: true)
  public var Theme_DeviceDefault_Light_Dialog: Int32

  @JavaStaticField(isFinal: true)
  public var Theme_DeviceDefault_Light_DialogWhenLarge: Int32

  @JavaStaticField(isFinal: true)
  public var Theme_DeviceDefault_Light_DialogWhenLarge_NoActionBar: Int32

  @JavaStaticField(isFinal: true)
  public var Theme_DeviceDefault_Light_Dialog_Alert: Int32

  @JavaStaticField(isFinal: true)
  public var Theme_DeviceDefault_Light_Dialog_MinWidth: Int32

  @JavaStaticField(isFinal: true)
  public var Theme_DeviceDefault_Light_Dialog_NoActionBar: Int32

  @JavaStaticField(isFinal: true)
  public var Theme_DeviceDefault_Light_Dialog_NoActionBar_MinWidth: Int32

  @JavaStaticField(isFinal: true)
  public var Theme_DeviceDefault_Light_NoActionBar: Int32

  @JavaStaticField(isFinal: true)
  public var Theme_DeviceDefault_Light_NoActionBar_Fullscreen: Int32

  @JavaStaticField(isFinal: true)
  public var Theme_DeviceDefault_Light_NoActionBar_Overscan: Int32

  @JavaStaticField(isFinal: true)
  public var Theme_DeviceDefault_Light_NoActionBar_TranslucentDecor: Int32

  @JavaStaticField(isFinal: true)
  public var Theme_DeviceDefault_Light_Panel: Int32

  @JavaStaticField(isFinal: true)
  public var Theme_DeviceDefault_NoActionBar: Int32

  @JavaStaticField(isFinal: true)
  public var Theme_DeviceDefault_NoActionBar_Fullscreen: Int32

  @JavaStaticField(isFinal: true)
  public var Theme_DeviceDefault_NoActionBar_Overscan: Int32

  @JavaStaticField(isFinal: true)
  public var Theme_DeviceDefault_NoActionBar_TranslucentDecor: Int32

  @JavaStaticField(isFinal: true)
  public var Theme_DeviceDefault_Panel: Int32

  @JavaStaticField(isFinal: true)
  public var Theme_DeviceDefault_Settings: Int32

  @JavaStaticField(isFinal: true)
  public var Theme_DeviceDefault_Wallpaper: Int32

  @JavaStaticField(isFinal: true)
  public var Theme_DeviceDefault_Wallpaper_NoTitleBar: Int32

  @JavaStaticField(isFinal: true)
  public var Theme_Dialog: Int32

  @JavaStaticField(isFinal: true)
  public var Theme_Holo: Int32

  @JavaStaticField(isFinal: true)
  public var Theme_Holo_Dialog: Int32

  @JavaStaticField(isFinal: true)
  public var Theme_Holo_DialogWhenLarge: Int32

  @JavaStaticField(isFinal: true)
  public var Theme_Holo_DialogWhenLarge_NoActionBar: Int32

  @JavaStaticField(isFinal: true)
  public var Theme_Holo_Dialog_MinWidth: Int32

  @JavaStaticField(isFinal: true)
  public var Theme_Holo_Dialog_NoActionBar: Int32

  @JavaStaticField(isFinal: true)
  public var Theme_Holo_Dialog_NoActionBar_MinWidth: Int32

  @JavaStaticField(isFinal: true)
  public var Theme_Holo_InputMethod: Int32

  @JavaStaticField(isFinal: true)
  public var Theme_Holo_Light: Int32

  @JavaStaticField(isFinal: true)
  public var Theme_Holo_Light_DarkActionBar: Int32

  @JavaStaticField(isFinal: true)
  public var Theme_Holo_Light_Dialog: Int32

  @JavaStaticField(isFinal: true)
  public var Theme_Holo_Light_DialogWhenLarge: Int32

  @JavaStaticField(isFinal: true)
  public var Theme_Holo_Light_DialogWhenLarge_NoActionBar: Int32

  @JavaStaticField(isFinal: true)
  public var Theme_Holo_Light_Dialog_MinWidth: Int32

  @JavaStaticField(isFinal: true)
  public var Theme_Holo_Light_Dialog_NoActionBar: Int32

  @JavaStaticField(isFinal: true)
  public var Theme_Holo_Light_Dialog_NoActionBar_MinWidth: Int32

  @JavaStaticField(isFinal: true)
  public var Theme_Holo_Light_NoActionBar: Int32

  @JavaStaticField(isFinal: true)
  public var Theme_Holo_Light_NoActionBar_Fullscreen: Int32

  @JavaStaticField(isFinal: true)
  public var Theme_Holo_Light_NoActionBar_Overscan: Int32

  @JavaStaticField(isFinal: true)
  public var Theme_Holo_Light_NoActionBar_TranslucentDecor: Int32

  @JavaStaticField(isFinal: true)
  public var Theme_Holo_Light_Panel: Int32

  @JavaStaticField(isFinal: true)
  public var Theme_Holo_NoActionBar: Int32

  @JavaStaticField(isFinal: true)
  public var Theme_Holo_NoActionBar_Fullscreen: Int32

  @JavaStaticField(isFinal: true)
  public var Theme_Holo_NoActionBar_Overscan: Int32

  @JavaStaticField(isFinal: true)
  public var Theme_Holo_NoActionBar_TranslucentDecor: Int32

  @JavaStaticField(isFinal: true)
  public var Theme_Holo_Panel: Int32

  @JavaStaticField(isFinal: true)
  public var Theme_Holo_Wallpaper: Int32

  @JavaStaticField(isFinal: true)
  public var Theme_Holo_Wallpaper_NoTitleBar: Int32

  @JavaStaticField(isFinal: true)
  public var Theme_InputMethod: Int32

  @JavaStaticField(isFinal: true)
  public var Theme_Light: Int32

  @JavaStaticField(isFinal: true)
  public var Theme_Light_NoTitleBar: Int32

  @JavaStaticField(isFinal: true)
  public var Theme_Light_NoTitleBar_Fullscreen: Int32

  @JavaStaticField(isFinal: true)
  public var Theme_Light_Panel: Int32

  @JavaStaticField(isFinal: true)
  public var Theme_Light_WallpaperSettings: Int32

  @JavaStaticField(isFinal: true)
  public var Theme_Material: Int32

  @JavaStaticField(isFinal: true)
  public var Theme_Material_Dialog: Int32

  @JavaStaticField(isFinal: true)
  public var Theme_Material_DialogWhenLarge: Int32

  @JavaStaticField(isFinal: true)
  public var Theme_Material_DialogWhenLarge_NoActionBar: Int32

  @JavaStaticField(isFinal: true)
  public var Theme_Material_Dialog_Alert: Int32

  @JavaStaticField(isFinal: true)
  public var Theme_Material_Dialog_MinWidth: Int32

  @JavaStaticField(isFinal: true)
  public var Theme_Material_Dialog_NoActionBar: Int32

  @JavaStaticField(isFinal: true)
  public var Theme_Material_Dialog_NoActionBar_MinWidth: Int32

  @JavaStaticField(isFinal: true)
  public var Theme_Material_Dialog_Presentation: Int32

  @JavaStaticField(isFinal: true)
  public var Theme_Material_InputMethod: Int32

  @JavaStaticField(isFinal: true)
  public var Theme_Material_Light: Int32

  @JavaStaticField(isFinal: true)
  public var Theme_Material_Light_DarkActionBar: Int32

  @JavaStaticField(isFinal: true)
  public var Theme_Material_Light_Dialog: Int32

  @JavaStaticField(isFinal: true)
  public var Theme_Material_Light_DialogWhenLarge: Int32

  @JavaStaticField(isFinal: true)
  public var Theme_Material_Light_DialogWhenLarge_DarkActionBar: Int32

  @JavaStaticField(isFinal: true)
  public var Theme_Material_Light_DialogWhenLarge_NoActionBar: Int32

  @JavaStaticField(isFinal: true)
  public var Theme_Material_Light_Dialog_Alert: Int32

  @JavaStaticField(isFinal: true)
  public var Theme_Material_Light_Dialog_MinWidth: Int32

  @JavaStaticField(isFinal: true)
  public var Theme_Material_Light_Dialog_NoActionBar: Int32

  @JavaStaticField(isFinal: true)
  public var Theme_Material_Light_Dialog_NoActionBar_MinWidth: Int32

  @JavaStaticField(isFinal: true)
  public var Theme_Material_Light_Dialog_Presentation: Int32

  @JavaStaticField(isFinal: true)
  public var Theme_Material_Light_LightStatusBar: Int32

  @JavaStaticField(isFinal: true)
  public var Theme_Material_Light_NoActionBar: Int32

  @JavaStaticField(isFinal: true)
  public var Theme_Material_Light_NoActionBar_Fullscreen: Int32

  @JavaStaticField(isFinal: true)
  public var Theme_Material_Light_NoActionBar_Overscan: Int32

  @JavaStaticField(isFinal: true)
  public var Theme_Material_Light_NoActionBar_TranslucentDecor: Int32

  @JavaStaticField(isFinal: true)
  public var Theme_Material_Light_Panel: Int32

  @JavaStaticField(isFinal: true)
  public var Theme_Material_Light_Voice: Int32

  @JavaStaticField(isFinal: true)
  public var Theme_Material_NoActionBar: Int32

  @JavaStaticField(isFinal: true)
  public var Theme_Material_NoActionBar_Fullscreen: Int32

  @JavaStaticField(isFinal: true)
  public var Theme_Material_NoActionBar_Overscan: Int32

  @JavaStaticField(isFinal: true)
  public var Theme_Material_NoActionBar_TranslucentDecor: Int32

  @JavaStaticField(isFinal: true)
  public var Theme_Material_Panel: Int32

  @JavaStaticField(isFinal: true)
  public var Theme_Material_Settings: Int32

  @JavaStaticField(isFinal: true)
  public var Theme_Material_Voice: Int32

  @JavaStaticField(isFinal: true)
  public var Theme_Material_Wallpaper: Int32

  @JavaStaticField(isFinal: true)
  public var Theme_Material_Wallpaper_NoTitleBar: Int32

  @JavaStaticField(isFinal: true)
  public var Theme_NoDisplay: Int32

  @JavaStaticField(isFinal: true)
  public var Theme_NoTitleBar: Int32

  @JavaStaticField(isFinal: true)
  public var Theme_NoTitleBar_Fullscreen: Int32

  @JavaStaticField(isFinal: true)
  public var Theme_NoTitleBar_OverlayActionModes: Int32

  @JavaStaticField(isFinal: true)
  public var Theme_Panel: Int32

  @JavaStaticField(isFinal: true)
  public var Theme_Translucent: Int32

  @JavaStaticField(isFinal: true)
  public var Theme_Translucent_NoTitleBar: Int32

  @JavaStaticField(isFinal: true)
  public var Theme_Translucent_NoTitleBar_Fullscreen: Int32

  @JavaStaticField(isFinal: true)
  public var Theme_Wallpaper: Int32

  @JavaStaticField(isFinal: true)
  public var Theme_WallpaperSettings: Int32

  @JavaStaticField(isFinal: true)
  public var Theme_Wallpaper_NoTitleBar: Int32

  @JavaStaticField(isFinal: true)
  public var Theme_Wallpaper_NoTitleBar_Fullscreen: Int32

  @JavaStaticField(isFinal: true)
  public var Theme_WithActionBar: Int32

  @JavaStaticField(isFinal: true)
  public var Widget: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_AbsListView: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_ActionBar: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_ActionBar_TabBar: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_ActionBar_TabText: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_ActionBar_TabView: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_ActionButton: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_ActionButton_CloseMode: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_ActionButton_Overflow: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_AutoCompleteTextView: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Button: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Button_Inset: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Button_Small: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Button_Toggle: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_CalendarView: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_CompoundButton: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_CompoundButton_CheckBox: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_CompoundButton_RadioButton: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_CompoundButton_Star: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_DatePicker: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_DeviceDefault: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_DeviceDefault_ActionBar: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_DeviceDefault_ActionBar_Solid: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_DeviceDefault_ActionBar_TabBar: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_DeviceDefault_ActionBar_TabText: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_DeviceDefault_ActionBar_TabView: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_DeviceDefault_ActionButton: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_DeviceDefault_ActionButton_CloseMode: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_DeviceDefault_ActionButton_Overflow: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_DeviceDefault_ActionButton_TextButton: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_DeviceDefault_ActionMode: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_DeviceDefault_AutoCompleteTextView: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_DeviceDefault_Button: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_DeviceDefault_Button_Borderless: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_DeviceDefault_Button_Borderless_Colored: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_DeviceDefault_Button_Borderless_Small: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_DeviceDefault_Button_Colored: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_DeviceDefault_Button_Inset: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_DeviceDefault_Button_Small: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_DeviceDefault_Button_Toggle: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_DeviceDefault_CalendarView: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_DeviceDefault_CheckedTextView: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_DeviceDefault_CompoundButton_CheckBox: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_DeviceDefault_CompoundButton_RadioButton: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_DeviceDefault_CompoundButton_Star: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_DeviceDefault_DatePicker: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_DeviceDefault_DropDownItem: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_DeviceDefault_DropDownItem_Spinner: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_DeviceDefault_EditText: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_DeviceDefault_ExpandableListView: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_DeviceDefault_FastScroll: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_DeviceDefault_GridView: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_DeviceDefault_HorizontalScrollView: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_DeviceDefault_ImageButton: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_DeviceDefault_Light: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_DeviceDefault_Light_ActionBar: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_DeviceDefault_Light_ActionBar_Solid: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_DeviceDefault_Light_ActionBar_Solid_Inverse: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_DeviceDefault_Light_ActionBar_TabBar: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_DeviceDefault_Light_ActionBar_TabBar_Inverse: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_DeviceDefault_Light_ActionBar_TabText: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_DeviceDefault_Light_ActionBar_TabText_Inverse: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_DeviceDefault_Light_ActionBar_TabView: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_DeviceDefault_Light_ActionBar_TabView_Inverse: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_DeviceDefault_Light_ActionButton: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_DeviceDefault_Light_ActionButton_CloseMode: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_DeviceDefault_Light_ActionButton_Overflow: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_DeviceDefault_Light_ActionMode: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_DeviceDefault_Light_ActionMode_Inverse: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_DeviceDefault_Light_AutoCompleteTextView: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_DeviceDefault_Light_Button: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_DeviceDefault_Light_Button_Borderless_Small: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_DeviceDefault_Light_Button_Inset: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_DeviceDefault_Light_Button_Small: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_DeviceDefault_Light_Button_Toggle: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_DeviceDefault_Light_CalendarView: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_DeviceDefault_Light_CheckedTextView: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_DeviceDefault_Light_CompoundButton_CheckBox: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_DeviceDefault_Light_CompoundButton_RadioButton: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_DeviceDefault_Light_CompoundButton_Star: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_DeviceDefault_Light_DropDownItem: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_DeviceDefault_Light_DropDownItem_Spinner: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_DeviceDefault_Light_EditText: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_DeviceDefault_Light_ExpandableListView: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_DeviceDefault_Light_FastScroll: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_DeviceDefault_Light_GridView: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_DeviceDefault_Light_HorizontalScrollView: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_DeviceDefault_Light_ImageButton: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_DeviceDefault_Light_ListPopupWindow: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_DeviceDefault_Light_ListView: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_DeviceDefault_Light_ListView_DropDown: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_DeviceDefault_Light_MediaRouteButton: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_DeviceDefault_Light_PopupMenu: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_DeviceDefault_Light_PopupWindow: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_DeviceDefault_Light_ProgressBar: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_DeviceDefault_Light_ProgressBar_Horizontal: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_DeviceDefault_Light_ProgressBar_Inverse: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_DeviceDefault_Light_ProgressBar_Large: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_DeviceDefault_Light_ProgressBar_Large_Inverse: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_DeviceDefault_Light_ProgressBar_Small: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_DeviceDefault_Light_ProgressBar_Small_Inverse: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_DeviceDefault_Light_ProgressBar_Small_Title: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_DeviceDefault_Light_RatingBar: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_DeviceDefault_Light_RatingBar_Indicator: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_DeviceDefault_Light_RatingBar_Small: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_DeviceDefault_Light_ScrollView: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_DeviceDefault_Light_SeekBar: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_DeviceDefault_Light_Spinner: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_DeviceDefault_Light_StackView: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_DeviceDefault_Light_Tab: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_DeviceDefault_Light_TabWidget: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_DeviceDefault_Light_TextView: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_DeviceDefault_Light_TextView_SpinnerItem: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_DeviceDefault_Light_WebTextView: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_DeviceDefault_Light_WebView: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_DeviceDefault_ListPopupWindow: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_DeviceDefault_ListView: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_DeviceDefault_ListView_DropDown: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_DeviceDefault_MediaRouteButton: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_DeviceDefault_PopupMenu: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_DeviceDefault_PopupWindow: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_DeviceDefault_ProgressBar: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_DeviceDefault_ProgressBar_Horizontal: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_DeviceDefault_ProgressBar_Large: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_DeviceDefault_ProgressBar_Small: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_DeviceDefault_ProgressBar_Small_Title: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_DeviceDefault_RatingBar: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_DeviceDefault_RatingBar_Indicator: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_DeviceDefault_RatingBar_Small: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_DeviceDefault_ScrollView: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_DeviceDefault_SeekBar: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_DeviceDefault_Spinner: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_DeviceDefault_StackView: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_DeviceDefault_Tab: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_DeviceDefault_TabWidget: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_DeviceDefault_TextView: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_DeviceDefault_TextView_SpinnerItem: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_DeviceDefault_WebTextView: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_DeviceDefault_WebView: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_DropDownItem: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_DropDownItem_Spinner: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_EditText: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_ExpandableListView: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_FastScroll: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_FragmentBreadCrumbs: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Gallery: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_GridView: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Holo: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Holo_ActionBar: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Holo_ActionBar_Solid: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Holo_ActionBar_TabBar: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Holo_ActionBar_TabText: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Holo_ActionBar_TabView: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Holo_ActionButton: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Holo_ActionButton_CloseMode: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Holo_ActionButton_Overflow: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Holo_ActionButton_TextButton: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Holo_ActionMode: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Holo_AutoCompleteTextView: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Holo_Button: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Holo_Button_Borderless: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Holo_Button_Borderless_Small: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Holo_Button_Inset: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Holo_Button_Small: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Holo_Button_Toggle: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Holo_CalendarView: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Holo_CheckedTextView: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Holo_CompoundButton_CheckBox: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Holo_CompoundButton_RadioButton: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Holo_CompoundButton_Star: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Holo_DatePicker: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Holo_DropDownItem: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Holo_DropDownItem_Spinner: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Holo_EditText: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Holo_ExpandableListView: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Holo_GridView: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Holo_HorizontalScrollView: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Holo_ImageButton: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Holo_Light: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Holo_Light_ActionBar: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Holo_Light_ActionBar_Solid: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Holo_Light_ActionBar_Solid_Inverse: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Holo_Light_ActionBar_TabBar: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Holo_Light_ActionBar_TabBar_Inverse: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Holo_Light_ActionBar_TabText: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Holo_Light_ActionBar_TabText_Inverse: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Holo_Light_ActionBar_TabView: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Holo_Light_ActionBar_TabView_Inverse: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Holo_Light_ActionButton: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Holo_Light_ActionButton_CloseMode: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Holo_Light_ActionButton_Overflow: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Holo_Light_ActionMode: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Holo_Light_ActionMode_Inverse: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Holo_Light_AutoCompleteTextView: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Holo_Light_Button: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Holo_Light_Button_Borderless_Small: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Holo_Light_Button_Inset: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Holo_Light_Button_Small: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Holo_Light_Button_Toggle: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Holo_Light_CalendarView: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Holo_Light_CheckedTextView: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Holo_Light_CompoundButton_CheckBox: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Holo_Light_CompoundButton_RadioButton: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Holo_Light_CompoundButton_Star: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Holo_Light_DropDownItem: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Holo_Light_DropDownItem_Spinner: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Holo_Light_EditText: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Holo_Light_ExpandableListView: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Holo_Light_GridView: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Holo_Light_HorizontalScrollView: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Holo_Light_ImageButton: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Holo_Light_ListPopupWindow: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Holo_Light_ListView: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Holo_Light_ListView_DropDown: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Holo_Light_MediaRouteButton: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Holo_Light_PopupMenu: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Holo_Light_PopupWindow: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Holo_Light_ProgressBar: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Holo_Light_ProgressBar_Horizontal: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Holo_Light_ProgressBar_Inverse: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Holo_Light_ProgressBar_Large: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Holo_Light_ProgressBar_Large_Inverse: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Holo_Light_ProgressBar_Small: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Holo_Light_ProgressBar_Small_Inverse: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Holo_Light_ProgressBar_Small_Title: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Holo_Light_RatingBar: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Holo_Light_RatingBar_Indicator: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Holo_Light_RatingBar_Small: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Holo_Light_ScrollView: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Holo_Light_SeekBar: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Holo_Light_Spinner: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Holo_Light_Tab: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Holo_Light_TabWidget: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Holo_Light_TextView: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Holo_Light_TextView_SpinnerItem: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Holo_Light_WebTextView: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Holo_Light_WebView: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Holo_ListPopupWindow: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Holo_ListView: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Holo_ListView_DropDown: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Holo_MediaRouteButton: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Holo_PopupMenu: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Holo_PopupWindow: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Holo_ProgressBar: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Holo_ProgressBar_Horizontal: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Holo_ProgressBar_Large: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Holo_ProgressBar_Small: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Holo_ProgressBar_Small_Title: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Holo_RatingBar: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Holo_RatingBar_Indicator: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Holo_RatingBar_Small: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Holo_ScrollView: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Holo_SeekBar: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Holo_Spinner: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Holo_Tab: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Holo_TabWidget: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Holo_TextView: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Holo_TextView_SpinnerItem: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Holo_WebTextView: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Holo_WebView: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_ImageButton: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_ImageWell: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_KeyboardView: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_ListPopupWindow: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_ListView: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_ListView_DropDown: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_ListView_Menu: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_ListView_White: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Material: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Material_ActionBar: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Material_ActionBar_Solid: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Material_ActionBar_TabBar: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Material_ActionBar_TabText: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Material_ActionBar_TabView: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Material_ActionButton: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Material_ActionButton_CloseMode: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Material_ActionButton_Overflow: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Material_ActionMode: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Material_AutoCompleteTextView: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Material_Button: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Material_ButtonBar: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Material_ButtonBar_AlertDialog: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Material_Button_Borderless: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Material_Button_Borderless_Colored: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Material_Button_Borderless_Small: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Material_Button_Colored: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Material_Button_Inset: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Material_Button_Small: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Material_Button_Toggle: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Material_CalendarView: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Material_CheckedTextView: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Material_CompoundButton_CheckBox: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Material_CompoundButton_RadioButton: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Material_CompoundButton_Star: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Material_CompoundButton_Switch: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Material_DatePicker: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Material_DropDownItem: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Material_DropDownItem_Spinner: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Material_EditText: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Material_ExpandableListView: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Material_FastScroll: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Material_GridView: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Material_HorizontalScrollView: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Material_ImageButton: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Material_Light: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Material_Light_ActionBar: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Material_Light_ActionBar_Solid: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Material_Light_ActionBar_TabBar: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Material_Light_ActionBar_TabText: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Material_Light_ActionBar_TabView: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Material_Light_ActionButton: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Material_Light_ActionButton_CloseMode: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Material_Light_ActionButton_Overflow: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Material_Light_ActionMode: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Material_Light_AutoCompleteTextView: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Material_Light_Button: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Material_Light_ButtonBar: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Material_Light_ButtonBar_AlertDialog: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Material_Light_Button_Borderless: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Material_Light_Button_Borderless_Colored: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Material_Light_Button_Borderless_Small: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Material_Light_Button_Inset: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Material_Light_Button_Small: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Material_Light_Button_Toggle: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Material_Light_CalendarView: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Material_Light_CheckedTextView: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Material_Light_CompoundButton_CheckBox: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Material_Light_CompoundButton_RadioButton: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Material_Light_CompoundButton_Star: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Material_Light_CompoundButton_Switch: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Material_Light_DatePicker: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Material_Light_DropDownItem: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Material_Light_DropDownItem_Spinner: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Material_Light_EditText: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Material_Light_ExpandableListView: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Material_Light_FastScroll: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Material_Light_GridView: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Material_Light_HorizontalScrollView: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Material_Light_ImageButton: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Material_Light_ListPopupWindow: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Material_Light_ListView: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Material_Light_ListView_DropDown: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Material_Light_MediaRouteButton: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Material_Light_NumberPicker: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Material_Light_PopupMenu: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Material_Light_PopupMenu_Overflow: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Material_Light_PopupWindow: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Material_Light_ProgressBar: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Material_Light_ProgressBar_Horizontal: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Material_Light_ProgressBar_Inverse: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Material_Light_ProgressBar_Large: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Material_Light_ProgressBar_Large_Inverse: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Material_Light_ProgressBar_Small: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Material_Light_ProgressBar_Small_Inverse: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Material_Light_ProgressBar_Small_Title: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Material_Light_RatingBar: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Material_Light_RatingBar_Indicator: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Material_Light_RatingBar_Small: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Material_Light_ScrollView: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Material_Light_SearchView: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Material_Light_SeekBar: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Material_Light_SegmentedButton: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Material_Light_Spinner: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Material_Light_Spinner_Underlined: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Material_Light_StackView: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Material_Light_Tab: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Material_Light_TabWidget: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Material_Light_TextView: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Material_Light_TextView_SpinnerItem: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Material_Light_TimePicker: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Material_Light_WebTextView: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Material_Light_WebView: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Material_ListPopupWindow: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Material_ListView: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Material_ListView_DropDown: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Material_MediaRouteButton: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Material_NumberPicker: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Material_PopupMenu: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Material_PopupMenu_Overflow: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Material_PopupWindow: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Material_ProgressBar: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Material_ProgressBar_Horizontal: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Material_ProgressBar_Large: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Material_ProgressBar_Small: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Material_ProgressBar_Small_Title: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Material_RatingBar: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Material_RatingBar_Indicator: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Material_RatingBar_Small: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Material_ScrollView: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Material_SearchView: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Material_SeekBar: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Material_SeekBar_Discrete: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Material_SegmentedButton: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Material_Spinner: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Material_Spinner_Underlined: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Material_StackView: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Material_Tab: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Material_TabWidget: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Material_TextView: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Material_TextView_SpinnerItem: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Material_TimePicker: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Material_Toolbar: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Material_Toolbar_Button_Navigation: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Material_WebTextView: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Material_WebView: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_PopupMenu: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_PopupWindow: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_ProgressBar: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_ProgressBar_Horizontal: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_ProgressBar_Inverse: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_ProgressBar_Large: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_ProgressBar_Large_Inverse: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_ProgressBar_Small: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_ProgressBar_Small_Inverse: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_RatingBar: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_ScrollView: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_SeekBar: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Spinner: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Spinner_DropDown: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_StackView: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_TabWidget: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_TextView: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_TextView_PopupMenu: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_TextView_SpinnerItem: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Toolbar: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_Toolbar_Button_Navigation: Int32

  @JavaStaticField(isFinal: true)
  public var Widget_WebView: Int32
}
