// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaKitNetwork
import JavaRuntime

@JavaClass("java.net.JarURLConnection")
open class JarURLConnection: URLConnection {
  @JavaMethod
  open func getJarFileURL() -> URL!

  @JavaMethod
  open func getEntryName() -> String
}
