// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

@JavaClass("java.net.Proxy")
open class Proxy: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: ProxyType?, _ arg1: SocketAddress?, environment: JNIEnvironment? = nil)

  @JavaMethod
  open func type() -> ProxyType!

  @JavaMethod
  open override func equals(_ arg0: JavaObject?) -> Bool

  @JavaMethod
  open override func toString() -> String

  @JavaMethod
  open override func hashCode() -> Int32

  @JavaMethod
  open func address() -> SocketAddress!
}
extension JavaClass<Proxy> {
  @JavaStaticField(isFinal: true)
  public var NO_PROXY: Proxy!
}
