// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

@JavaInterface("java.net.SocketOptions")
public struct SocketOptions {
  @JavaMethod
  public func setOption(_ arg0: Int32, _ arg1: JavaObject?) throws

  @JavaMethod
  public func getOption(_ arg0: Int32) throws -> JavaObject!
}
extension JavaClass<SocketOptions> {
  @JavaStaticField(isFinal: true)
  public var TCP_NODELAY: Int32

  @JavaStaticField(isFinal: true)
  public var SO_BINDADDR: Int32

  @JavaStaticField(isFinal: true)
  public var SO_REUSEADDR: Int32

  @JavaStaticField(isFinal: true)
  public var SO_REUSEPORT: Int32

  @JavaStaticField(isFinal: true)
  public var SO_BROADCAST: Int32

  @JavaStaticField(isFinal: true)
  public var IP_MULTICAST_IF: Int32

  @JavaStaticField(isFinal: true)
  public var IP_MULTICAST_IF2: Int32

  @JavaStaticField(isFinal: true)
  public var IP_MULTICAST_LOOP: Int32

  @JavaStaticField(isFinal: true)
  public var IP_TOS: Int32

  @JavaStaticField(isFinal: true)
  public var SO_LINGER: Int32

  @JavaStaticField(isFinal: true)
  public var SO_TIMEOUT: Int32

  @JavaStaticField(isFinal: true)
  public var SO_SNDBUF: Int32

  @JavaStaticField(isFinal: true)
  public var SO_RCVBUF: Int32

  @JavaStaticField(isFinal: true)
  public var SO_KEEPALIVE: Int32

  @JavaStaticField(isFinal: true)
  public var SO_OOBINLINE: Int32
}
