// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaKitNetwork
import JavaRuntime

@JavaClass("java.net.URLStreamHandler")
open class URLStreamHandler: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(environment: JNIEnvironment? = nil)

  @JavaMethod
  open func equals(_ arg0: URL?, _ arg1: URL?) -> Bool

  @JavaMethod
  open func hashCode(_ arg0: URL?) -> Int32

  @JavaMethod
  open func parseURL(_ arg0: URL?, _ arg1: String, _ arg2: Int32, _ arg3: Int32)

  @JavaMethod
  open func getDefaultPort() -> Int32

  @JavaMethod
  open func sameFile(_ arg0: URL?, _ arg1: URL?) -> Bool

  @JavaMethod
  open func toExternalForm(_ arg0: URL?) -> String

  @JavaMethod
  open func openConnection(_ arg0: URL?, _ arg1: Proxy?) throws -> URLConnection!

  @JavaMethod
  open func openConnection(_ arg0: URL?) throws -> URLConnection!

  @JavaMethod
  open func getHostAddress(_ arg0: URL?) -> InetAddress!

  @JavaMethod
  open func hostsEqual(_ arg0: URL?, _ arg1: URL?) -> Bool

  @JavaMethod
  open func setURL(_ arg0: URL?, _ arg1: String, _ arg2: String, _ arg3: Int32, _ arg4: String, _ arg5: String)

  @JavaMethod
  open func setURL(_ arg0: URL?, _ arg1: String, _ arg2: String, _ arg3: Int32, _ arg4: String, _ arg5: String, _ arg6: String, _ arg7: String, _ arg8: String)
}
