// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

@JavaInterface("java.net.URLStreamHandlerFactory")
public struct URLStreamHandlerFactory {
  @JavaMethod
  public func createURLStreamHandler(_ arg0: String) -> URLStreamHandler!
}
