// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

@JavaClass("java.awt.font.TextAttribute")
open class TextAttribute: JavaObject {
  @JavaMethod
  open func readResolve() throws -> JavaObject!
}
extension JavaClass<TextAttribute> {
  @JavaStaticField(isFinal: true)
  public var FAMILY: TextAttribute!

  @JavaStaticField(isFinal: true)
  public var WEIGHT: TextAttribute!

  @JavaStaticField(isFinal: true)
  public var WEIGHT_EXTRA_LIGHT: JavaFloat!

  @JavaStaticField(isFinal: true)
  public var WEIGHT_LIGHT: JavaFloat!

  @JavaStaticField(isFinal: true)
  public var WEIGHT_DEMILIGHT: JavaFloat!

  @JavaStaticField(isFinal: true)
  public var WEIGHT_REGULAR: JavaFloat!

  @JavaStaticField(isFinal: true)
  public var WEIGHT_SEMIBOLD: JavaFloat!

  @JavaStaticField(isFinal: true)
  public var WEIGHT_MEDIUM: JavaFloat!

  @JavaStaticField(isFinal: true)
  public var WEIGHT_DEMIBOLD: JavaFloat!

  @JavaStaticField(isFinal: true)
  public var WEIGHT_BOLD: JavaFloat!

  @JavaStaticField(isFinal: true)
  public var WEIGHT_HEAVY: JavaFloat!

  @JavaStaticField(isFinal: true)
  public var WEIGHT_EXTRABOLD: JavaFloat!

  @JavaStaticField(isFinal: true)
  public var WEIGHT_ULTRABOLD: JavaFloat!

  @JavaStaticField(isFinal: true)
  public var WIDTH: TextAttribute!

  @JavaStaticField(isFinal: true)
  public var WIDTH_CONDENSED: JavaFloat!

  @JavaStaticField(isFinal: true)
  public var WIDTH_SEMI_CONDENSED: JavaFloat!

  @JavaStaticField(isFinal: true)
  public var WIDTH_REGULAR: JavaFloat!

  @JavaStaticField(isFinal: true)
  public var WIDTH_SEMI_EXTENDED: JavaFloat!

  @JavaStaticField(isFinal: true)
  public var WIDTH_EXTENDED: JavaFloat!

  @JavaStaticField(isFinal: true)
  public var POSTURE: TextAttribute!

  @JavaStaticField(isFinal: true)
  public var POSTURE_REGULAR: JavaFloat!

  @JavaStaticField(isFinal: true)
  public var POSTURE_OBLIQUE: JavaFloat!

  @JavaStaticField(isFinal: true)
  public var SIZE: TextAttribute!

  @JavaStaticField(isFinal: true)
  public var TRANSFORM: TextAttribute!

  @JavaStaticField(isFinal: true)
  public var SUPERSCRIPT: TextAttribute!

  @JavaStaticField(isFinal: true)
  public var SUPERSCRIPT_SUPER: JavaInteger!

  @JavaStaticField(isFinal: true)
  public var SUPERSCRIPT_SUB: JavaInteger!

  @JavaStaticField(isFinal: true)
  public var FONT: TextAttribute!

  @JavaStaticField(isFinal: true)
  public var CHAR_REPLACEMENT: TextAttribute!

  @JavaStaticField(isFinal: true)
  public var FOREGROUND: TextAttribute!

  @JavaStaticField(isFinal: true)
  public var BACKGROUND: TextAttribute!

  @JavaStaticField(isFinal: true)
  public var UNDERLINE: TextAttribute!

  @JavaStaticField(isFinal: true)
  public var UNDERLINE_ON: JavaInteger!

  @JavaStaticField(isFinal: true)
  public var STRIKETHROUGH: TextAttribute!

  @JavaStaticField(isFinal: true)
  public var STRIKETHROUGH_ON: JavaBoolean!

  @JavaStaticField(isFinal: true)
  public var RUN_DIRECTION: TextAttribute!

  @JavaStaticField(isFinal: true)
  public var RUN_DIRECTION_LTR: JavaBoolean!

  @JavaStaticField(isFinal: true)
  public var RUN_DIRECTION_RTL: JavaBoolean!

  @JavaStaticField(isFinal: true)
  public var BIDI_EMBEDDING: TextAttribute!

  @JavaStaticField(isFinal: true)
  public var JUSTIFICATION: TextAttribute!

  @JavaStaticField(isFinal: true)
  public var JUSTIFICATION_FULL: JavaFloat!

  @JavaStaticField(isFinal: true)
  public var JUSTIFICATION_NONE: JavaFloat!

  @JavaStaticField(isFinal: true)
  public var INPUT_METHOD_HIGHLIGHT: TextAttribute!

  @JavaStaticField(isFinal: true)
  public var INPUT_METHOD_UNDERLINE: TextAttribute!

  @JavaStaticField(isFinal: true)
  public var UNDERLINE_LOW_ONE_PIXEL: JavaInteger!

  @JavaStaticField(isFinal: true)
  public var UNDERLINE_LOW_TWO_PIXEL: JavaInteger!

  @JavaStaticField(isFinal: true)
  public var UNDERLINE_LOW_DOTTED: JavaInteger!

  @JavaStaticField(isFinal: true)
  public var UNDERLINE_LOW_GRAY: JavaInteger!

  @JavaStaticField(isFinal: true)
  public var UNDERLINE_LOW_DASHED: JavaInteger!

  @JavaStaticField(isFinal: true)
  public var SWAP_COLORS: TextAttribute!

  @JavaStaticField(isFinal: true)
  public var SWAP_COLORS_ON: JavaBoolean!

  @JavaStaticField(isFinal: true)
  public var NUMERIC_SHAPING: TextAttribute!

  @JavaStaticField(isFinal: true)
  public var KERNING: TextAttribute!

  @JavaStaticField(isFinal: true)
  public var KERNING_ON: JavaInteger!

  @JavaStaticField(isFinal: true)
  public var LIGATURES: TextAttribute!

  @JavaStaticField(isFinal: true)
  public var LIGATURES_ON: JavaInteger!

  @JavaStaticField(isFinal: true)
  public var TRACKING: TextAttribute!

  @JavaStaticField(isFinal: true)
  public var TRACKING_TIGHT: JavaFloat!

  @JavaStaticField(isFinal: true)
  public var TRACKING_LOOSE: JavaFloat!
}
