name: Swift
on:
  push:
    branches: [master]
  workflow_dispatch:
  pull_request:

jobs:
  android:
    name: Android
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-24.04', 'macos-15-intel']
        swift: ['6.2.3', 'nightly-6.3']
        arch: ['aarch64', 'x86_64', 'armv7']
        sdk: ['28', '29', '31', '33']
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v6
      - uses: skiptools/actions/setup-skip@v1
        with:
          install-swift-android-sdk: true
          gradle-version: 'none'
          swift-version: ${{ matrix.swift }}
          swift-android-sdk-version: ${{ matrix.swift }}
      - name: "Build Swift Package for Android"
        run: |
          ANDROID_NDK_ROOT="" ANDROID_SDK_VERSION=${{ matrix.sdk }} skip android build --arch ${{ matrix.arch }} --android-api-level ${{ matrix.sdk }}
      - name: "Install and launch emulator"
        run: |
          skip android emulator create --android-api-level ${{ matrix.sdk }}
          skip android emulator launch --background
      - name: "Test Swift package on emulator"
        run: |
          skip android test --apk

